### ISSUE TITLE
Backend: Main menu in sidebar

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#100]
**Describe the solution you'd like**
Move the main menu to a sidebar. This can be done before or after the theme change in #99, but maybe it is better to do the theme change first, as the theme might give an impression on how to design the menu.

Then change the page layouts so that contents are displayed on the right of the menu (therefore the menu is always visible). Also all overlays such as sanity check and navigation tree should be changed to be displayed inline.

The menu should have a collapse button to give the content more space.

At the top of the menu, add a search input field, which filters the menu items directly on typing (comparable to e.g. the settings dialog of PHPStorm). The filter function should also display matching menu items that are NOT part of the current perspective. In the future we might extend this search field to also find other contents.

This whole change should be done in a way that allows users to still use the old concept ("classic main menu").

**Comment by UlrichKu** [comment]
Probably it would be feasible to fix the menu to the top with css only.

**Comment by esono-anja** [comment]
1. Menu is expanded: If you open the lowest item "System", you won't see that there are still many items following in the submenu. You can navigate to them, but first you can't see that more points follow.
![menu1](https://user-images.githubusercontent.com/15125103/53029577-7aebe080-3469-11e9-96c0-9031a0dc64c8.png)

2. Menu collapsed (you only see the icons): it is not possible to navigate to the submenu items which are outside of the screen
![menu2](https://user-images.githubusercontent.com/15125103/53029601-87703900-3469-11e9-8b43-74c7c6f375d7.png)

3. It would be awesome if the selected submenu on the left remained open. Let's say I go to products. The submenu on the left closes again after I have selected the menu item. Now I want to go to product categories. It would be much easer if the submenu "Products & Categories" were still open.

**Comment by umulmrum** [comment]
1: There is a scrollbar indicating further menu items, and even if the user misses it on the first glance, a second look should be enough. So I'd say we leave it as is for the moment and only make changes if users get confused.

2: Maybe @pixeljunkie can help?

3: That's right - I'll have a look.

**Comment by umulmrum** [comment]
@esono-anja Could you test no. 3?

@pixeljunkie We already spoke about no. 2, but these JS changes would cost me a lot of time and maybe you're faster - do you have some spare time?

**Comment by esono-anja** [comment]
@umulmrum 
3. Doesn't work yet. Now always the submenu items of "Analytics" are expanded, no matter which menu item i called before.
![analytics](https://user-images.githubusercontent.com/15125103/53506441-4229b800-3ab6-11e9-852b-2601e1ea50f4.png)

**Comment by esono-anja** [comment]
no 3.:
It does work now. However, I would expect the sidebar menu to close completely, when I go to the home screen. Currently the once opened category on the left remains open until you open another category.

**Comment by umulmrum** [comment]
@esono-anja I'd like to discuss this in a future version - if a user is annoyed by the open category, they can still close it manually.
