### ISSUE TITLE
Backend: Breadcrumb instead of history

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#101]
**Describe the solution you'd like**
Currently we show a history of the previously viewed pages on every backend page. This looks like a breadcrumb but isn't one - we should show a real breadcrumb instead. Problem is that currently there is no hierarchy between pages so that we can only display a depth of 1 (maybe this is enough for now, though).

**Comment by pixeljunkie** [comment]
After a longer discussion and some insights... we should not remove the history feature, because it makes sense working with the CMS on deeper levels, but we should check where the history needs to be reset. The overall level should not exceed 4 or 5. We need to check what makes sense.
