### ISSUE TITLE
Backend: Improve list usability (filters)

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#102]
**Describe the solution you'd like**
We should improve how backend lists are displayed. While this is potentially a huge topic, this issue should limit its scope to the rendering and configuration part, NOT the technical basis.

- Users should be able to define custom filters easily (persisted?). Alternatively it might be OK to use fixed filters, but one for each column (e.g. a dropdown containing Yes/No/Undefined for a boolean field).
- Users should be able to modify which columns are displayed.

**Comment by UlrichKu** [comment]
Similar topic #88
