### ISSUE TITLE
Backend: Improve navigation tree

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#107]
**Describe the solution you'd like**
The navigation tree should be improved:
- Use a newer tree component; the tree from the media manager should fit (and we only have one tree component then). This should also be used for navigation node/page fields.
- Maybe we should move the navigation management from the top to the side menu as proposed in #100.
- I'd prefer not having to use right-clicks as they are normally reserved for browser functions; we should think about a concept that uses only web-style controls (but not at any cost).
- It should be easier to handle multiple portals. Currently the user has to minify other portal trees to find portals at the end of the tree (a choice that is not persisted). Maybe it is generally advisable to introduce the concept of the current portal so that all actions in the backend refer to that portal.
- Performance with multiple portals or lots of navigation nodes could be improved.
- The tree should be usable on tablets and phones.

**Comment by esono-anja** [comment]
#548

**Comment by esono-anja** [comment]
#550

**Comment by esono-anja** [comment]
Testing results see issues #548 and #550

**Comment by UlrichKu** [comment]
Double clicking an entry should open the (first) connected page (as it was before).

**Comment by ckleis** [comment]
Because the link to the page can be reached quickly via the right-click menu, it remains to be considered whether a link by double-click is useful. Double-clicking sometimes moves the node by mistake.
