### ISSUE TITLE
Media manager: too high, popup with unnecessary scrollbars

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#108]
**Describe the bug**
Media manager itself has a page that is very high - without content.
Furthermore the media popup for an image has an addtional scrollbar although there is no content for it (see screenshot).

**Affected version(s)**
6.2

**To Reproduce**
1. Open media manager page by clicking "Media" in the backend.
2. Browse in the tree on the right; ie to Media>Website>Slider
3. Click the edit button at the bottom right of an image

**Expected behavior**
Probably the media manager page should only be as big as necessary.
The popup view for an image should not contain a scrollbar if not needed.

**Screenshots**
![selection_092](https://user-images.githubusercontent.com/20949224/46197984-a2e87500-c30b-11e8-86bf-b4e48ae86d80.png)

**Comment by UlrichKu** [comment]
See #217 for an adjacent ticket/change.

**Comment by UlrichKu** [comment]
Note: Here is also the question what to do with the mediaManager.less - which at the moment is abandoned.

**Comment by esono-anja** [comment]
500 Internal Server Error, when trying to open an image data record (see point 3. Click the edit button at the bottom right of an image)

**Comment by UlrichKu** [comment]
Reason for 500: An exception occurred while executing 'SELECT * FROM `pkg_cms_credit_check` WHERE `text_credit_check_pending` LIKE ? OR `text_credit_check_pending__de` LIKE ?' with params ["%cmsmedia=\"9927eff6-9bfa-0588-057c-6e29b8715fe9%", "%cmsmedia=\"9927eff6-9bfa-0588-057c-6e29b8715fe9%"]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'text_credit_check_pending__de' in 'where clause'

**Comment by esono-anja** [comment]
the scrollbar of an opened image data record is still there.
![scrollbar](https://user-images.githubusercontent.com/15125103/49865342-00696980-fe05-11e8-8d04-0fdb1e59e2b0.png)

**Comment by umulmrum** [comment]
Good explanation :-) - merged.
