### ISSUE TITLE
Media manager: smaller display widths: content is moved below content area

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#109]
**Describe the bug**
For smaller displays (ie my portrait rotated one with 1200 pixel width) the content display of the media manager is moved to the bottom of the page - outside of the white content area.

This looks as if the content is completely empty/missing.

**Affected version(s)**
6.2

**Technical details**
On other displays (after a reload) this is ok.
Probably the javascript for .split-horizontal provides unsuitable values here ("width: calc(80% - 5px)").

**Comment by rnuernberg** [comment]
This does not appear to be a display size problem - but rather a combination of content and display size. I have the same problem in a project with a much larger display using a window size of around 2000 px.

**Comment by rnuernberg** [comment]
sorry, my bad. my browser was using zoom - for whatever reason. When I disable it, I no longer have the problem.

**Comment by ckleis** [comment]
The problem occurs with zoom-in and reload

**Comment by ckleis** [comment]
The dynamic calculation of the width disregarded the existing padding of the edit-container. Without changing the zoom, deviations due to rounding were sufficient to compensate. With zoom greater than 100% the elements together were greater than 100% width.
