### ISSUE TITLE
Deactivated article and (thus) empty category: no 404 page

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#112]
Shows best once #181 is fixed. Otherwise you might need to remove addition URL parameters.

**Affected version(s)**
\>=6.1

**To Reproduce**
0. Make sure to have an article that is the only one in its category and the shop setting _Show empty categories in shop_ is No
1. Call the detail page of this article
2. Deactivate the article and clear cache
3. Call the page again
4. In dev mode an unhandled exception is shown for NotFoundHttpException
5. Subsequent calls (which will be served from the cache in TPkgShopRouteControllerArticle) will notice access to a not existing object field

**Technical details**
vendor/chameleon-system/chameleon-shop/src/ShopBundle/objects/TCMSSmartURLHandler/TPkgShopRouteControllerArticle.class.php:164

The category reports false for `AllowDisplayInShop()` and then the function `prepareArticleResponseWhenDetailViewNotAllowed()` is not executed.

**Comment by umulmrum** [comment]
@UlrichKu I followed the steps you provided, but couldn't reproduce the issue. Is there anything else I need to configure (e.g. other product categories besides the main category)?
