### ISSUE TITLE
Command for number of updates

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#116]
**Describe the solution you'd like**
There should be a console command for getting the number of updates that is active / would be executed.

Something like: 
app/console chameleon_system:update:list --count

**Comment by UlrichKu** [comment]
PR now introduces a new command: chameleon_system:update:count

**Comment by umulmrum** [comment]
The command returns 1 even if there are 2 updates for one single bundle. This is because TCMSUpdateManager::getAllUpdateFilesToProcess() does not return a flat list but a nested array.

@UlrichKu, could you have a look at this today?
