### ISSUE TITLE
Buying last product: still visible in category (cache)

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#121]
**Describe the bug**
Buying the last item of a product with variants will not hide it on the respective category (frontend) page.

Also see #83, #84, #86 with similar bugs/topics.

**Affected version(s)**
\>= 6.0

**To Reproduce**
0. Make sure you have a product with variants and the stock of the variants is 0 except for one with 1, cache (or production mode) should be activated
1. Buy this product/variant (= finish a purchase)
2. Click on the category again: product will still be visible
3. Click on this product: a 404 page is shown
4. Clear the cache in the backend and reload category page: product is not shown

**Comment by esono-anja** [comment]
After purchasing the last variant article, the product is no longer displayed.
