### ISSUE TITLE
Controller missing in modules defined as service

### ISSUE THREAD

**Issue by rnuernberg** [chameleon-system/chameleon-system#122]
**System behavior before the change**
Calling \TModelBase::_OutputForAjax on a module defined as a service would work.

**System behavior after the change**
Since the controller used in the method is no longer set, an exception is thrown

**Affected version(s)**
6.2

**Comment by umulmrum** [comment]
The controller was never set for modules defined as services, so we should not change this. The injected controller was not used before 6.2.0, so I added a fallback to the controller from the service container.

**Comment by rnuernberg** [comment]
That would mean, that all OuputForAjax would fail for oder versions and modules defined as service. i have a very hard time believing that. I have hat least one project in 6.1 that used the method in a class defined as a service.
