### ISSUE TITLE
Main product of variants still shown with no stock (cache)

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#124]
Extracted from #83.

**Describe the bug**
Sometimes the main product is still shown (on a category page) although all variants have stock 0 and the shop setting "Variant parents can be purchased" is false

**Affected version(s)**
\>=6.0

**Comment by umulmrum** [comment]
Looks like a duplicate of #121 - please reopen if it is a separate issue (more details would be great then).

**Comment by UlrichKu** [comment]
I'm 98% certain this is separate.

**Comment by UlrichKu** [comment]
I'm 98% certain this is separate.

**Comment by UlrichKu** [comment]
Might indeed be fixed by #121
