### ISSUE TITLE
Cronjob activation toggle

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#135]
**Describe the solution you'd like**
For deployments we should be able to deactivate cronjobs externally.

**Possible solution (if any)**
- Add a field "Cronjobs active yes/no" to cms_config. This field can then of course be set manually in the backend.
- The field should be used at a central place such as CMSRunCrons or TCMSCronJob.
- The flag should be checked for each cronjob, i.e. if cronjobs get deactivated while one cronjob is running, the following jobs should not be executed (and not postponed).
- Add a command that sets this flag and one that unsets this flag.

**Comment by UlrichKu** [comment]
NOTE There is already a sanity check that checks for long inactivity of cronjobs - so warning when this option is on by accident.
