### ISSUE TITLE
Improve naming of views

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#137]
**Describe the solution you'd like**
Currently the module views bear names like "standard", "full", "smallcol" etc. These names can be improved to simplify backend usage (maybe the views named "standard" are OK in most cases, but let's have a look at them).

Step 1: Make suggestions for new names (@proligde ).
Step 2: Do changes in the official database distribution (@umulmrum ).

**Comment by pixeljunkie** [comment]
It is already possible to translate the view names with a mapping field in the modules. Changing the views itself is not a must have as long as we have longer descriptions of what the views are meant for, i think.

**Comment by umulmrum** [comment]
Should have written this, but that's actually the plan :-)
