### ISSUE TITLE
module_fnc on access-restricted pages

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#139]
**Describe the bug**
When calling a link to an access-restricted page, and the session has expired, the access-restriction error is shown instead and the user may directly login to proceed. If the request contained a module_fnc, things happen:
- If the module function refers to a spot that exists on the access-restricted page, but the called method does not exist in the referenced module, a method-does-not-exist-error is returned.
- Login is not possible; instead the access-restricted page is shown again after submitting credentials.

**Affected version(s)**
All Chameleon versions.

**To Reproduce**
<handed in later, sorry :-) >

**Expected behavior**
The access-restricted page should be displayed. After login, the originally requested action should be executed.

**Technical details**
The reason for the login problem is as follows: When submitting the login form, a module_fnc parameter is sent both by GET and by POST, with the login data in POST and the original request in GET. The GET parameters have precedence and therefore the login data are never read by the system.

**Comment by umulmrum** [comment]
This is actually really tricky and I currently have no idea what to do.

**Comment by UlrichKu** [comment]
Solved now with the support of module functions in POST and GET at the same time. POST has precedence.

**Comment by UlrichKu** [comment]
Additionally solved with accessing the correct page on login - which masks the first fix.
