### ISSUE TITLE
Deleting a field of type "Value list from several tables" does not work

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#141]
**Affected version(s)**
Probably all; happened with 6.2

**To Reproduce**
1. Create a new table
2. Add a field of type "Value list from several tables (extended)" - pointing for example to "sTables=shop_article_type,shop_article_stock"
3. Delete this field

-> The following error appears: 
An exception occurred while executing 'ALTER TABLE `test_table_x` DROP INDEX `type_stock`':
SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'type_stock'; check that column/key exists

However the field is actually missing from the database - so it seems to have been deleted correctly/already.

**Comment by bestform** [comment]
This is connected to a closed issue.
