### ISSUE TITLE
Tables not shown for different backend languages

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#143]
**Affected version(s)**
6.2

**To Reproduce**
1. Switch profile backend language to "German"
2. Create a table (and set access rights, group)
3. Make sure it is shown in backend (ie below "Shop settings")
4. Switch profile backend language to "English"

-> Table is not shown

The reverse is not the case starting with English as profile language: then it is still shown when switching to profile language German.

**Comment by umulmrum** [comment]
@UlrichKu is the table shown when you log out and log in again?

**Comment by UlrichKu** [comment]
> @UlrichKu is the table shown when you log out and log in again?

Hm, not (easily) reproducible with 6.2.4...
