### ISSUE TITLE
Field "Value list from several tables" cannot connect to every table

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#144]
**Affected version(s)**
Probably all; seen with 6.2

**To Reproduce**
1. Add a table field of type "Value list from several tables (extended)", it should connect to sTables=shop_article_type,shop_article_stock
2. Access table list in backend and add an entry to the table

-> The multi select field has a button for "Article type" but none for "Article stock".

**Technical details**
Probably because the table is configured as "contains only one entry".

**Comment by bestform** [comment]
@UlrichKu can you confirm that this is due to the mentioned setting? If so, I think we can just close this issue.
