### ISSUE TITLE
Update overwrites the custom default image

### ISSUE THREAD

**Issue by pSpeck** [chameleon-system/chameleon-system#146]
**Describe the bug**
Update Build #1530018334 changes the default image file. The check if image was customized should be changed. It checks the database field 'filesize'. But if someone changes the real image file, they did not change the file size in the database. So custom imgae will be replaced.

**Affected version(s)**
6.2

**Comment by umulmrum** [comment]
I'm not sure if we should fix this issue. Of course it's a bit of a hassle, but changing the image "responsibly" in the first place avoids it.
