### ISSUE TITLE
CronJobs fail silently on php notices/warnings

### ISSUE THREAD

**Issue by rnuernberg** [chameleon-system/chameleon-system#148]
**System behavior before the change**
Running a cronjob that produced a php notice would work. If a cronjob did fail, it would be marked as blocked allowing a user to see a problem via backend

**System behavior after the change**
Running a cronjob fails with 500 even in production mode. The cronjob unlocked after the error - so there is no way to see via backend that there is an error.

**Affected version(s)**
6.2

This is very urgent as it breaks many legacy cronjobs.

**Comment by umulmrum** [comment]
@rnuernberg 
The error should have been logged on level critical in the database log - is this the case?

Looking at the code in TCMSCronJob::RunScript and TCMSCronJob::setExceptionErrorHandler, I'd assume that notices go unchecked if error reporting is not active for the notice level (can't currently test it). Could you check the error reporting level?
