### ISSUE TITLE
Backend Media Search does not Work when assigning an Image

### ISSUE THREAD

**Issue by rnuernberg** [chameleon-system/chameleon-system#149]
**Describe the bug**
Given an Image field with an Image assigned to it. If you then klick on the "assign" button to assign a new image and type in a search in the media manager window that opens, then no image will be found - regardless of the search.

**Affected version(s)**
6.2

**To Reproduce**
1. Given an image field with an image assigned to it
2. klick on "assign"
3. type in a search in the media manager window

**Expected behavior**
Images matching the query should be shown. Instead, no images are shown.

Typing in the same search when opening the media manager via the top navigation will produce the expected results.

**Screenshots**
![2018-10-22-001](https://user-images.githubusercontent.com/1104497/47283826-2b91c280-d5e5-11e8-8a8f-b379b025e666.png)

![2018-10-22-002](https://user-images.githubusercontent.com/1104497/47283852-46643700-d5e5-11e8-8878-e0c352e15be7.png)

**Comment by umulmrum** [comment]
I could only reproduce the bug with the old media manager as described in your other ticket #150. Is there also a problem in the new media manager or can we close this issue?

**Comment by rnuernberg** [comment]
Problem occurs only in the old media manager. There where problems with github yesterday which prevented me from changing the original ticket. I will close it now
