### ISSUE TITLE
Backend: Perspectives

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#156]
**Describe the solution you'd like**
Currently the backend is quite overwhelming, as it offers lots of options, but doesn't do a good job at restricting information to those that are currently relevant. Solving this takes a lot of effort - in the scope of this ticket we mainly introduce a solution concerning the main menu.

For this we introduce the concept of "perspectives". A perspective is a narrowed view on the main menu items so that items that are currently not needed are not displayed.

First we change the main menu to a sidebar (see #100). This sidebar contains only those category boxes that are defined in the perspective [to be tested: Should we also use perspectives to control which menu items are displayed?].

Then we add a new menu item in the top navigation. This item shows the current perspective and can be expanded (similar to the language selector); the expanded panel contains the following controls:
- A button that enables edit mode for the current perspective.
- A list of defined perspectives; the user can select another perspective here.
- A button to create a new perspective (opens edit mode of a new perspective).

In edit mode we stay on the current page [or navigate to the main page? We will use this mode to change the dashboard as well, see below], but add a few controls:
- Perspective name.
- Delete button for each category box.
- Button to add another existing category box that is not yet part of the perspective.
- Controls to change category box order.

Discussion in the team showed that perspectives should also control which menu items are displayed in each category box. I suggest to first build the feature without this enhancement and find out experimentally if it is really needed.

Likewise, being able to sort menu items within a category box as part of a perspective was requested. I suggest to experiment with this requirement after the base functionality was implemented.

In future versions we intend to extend the perspective concept, so that the (to-be-defined) dashboard can also be customized, as well as other elements, e.g. fields or tabs in the table editor.

**Comment by UlrichKu** [comment]
Dashboard is #103

**Comment by bestform** [comment]
With new concepts like the dashboard and searchable menu, this issue is obsolete. We can still think about something like perspectives, but it isn't a hard requirement anymore.
