### ISSUE TITLE
Yes/No Field does not always work

### ISSUE THREAD

**Issue by rnuernberg** [chameleon-system/chameleon-system#158]
**Describe the bug**
Occasionally changing the yes/no field will not change the value in the database (the old value is shown after a reload of the record).
I have had this in at least two situations: a) changing the primary domain of a portal. b) disabling all websites via cms config.

I think it occurred only when only the yes/no field was changed - but I can not be sure of this. 

I also think, that this only ever happend when changing the field from no to yes - but again, i am not 100% sure.

**Affected version(s)**
6.1/6.2

**To Reproduce**
I am not able to consistently reproduce the behavior.

**Expected behavior**
Changing the yes/no field and saving the record should update the field in the database every time a change is made.

**Desktop (please complete the following information):**
 - OS: ubuntu Linux
 - Browser: Chrome
 - Version: Unknown since I am reporting it a few days after I had the problem last. My current version is 70.0.3538.67 - so anything below this is a good bet.

**Comment by umulmrum** [comment]
In 6.3.0 the bool widget is replaced - we should test that this is fixed then.

**Comment by UlrichKu** [comment]
> In 6.3.0 the bool widget is replaced - we should test that this is fixed then.

When should this be the case?

With the current master (18.12.18) I don't see a change - in behavior or appearance.

This also happens when switching from Yes to No.

**Comment by pixeljunkie** [comment]
Not yet merged into master. Try this fork for a sneak peak: https://github.com/pixeljunkie/chameleon-base/tree/feature/99-add-coreui-theme

**Comment by esono-anja** [comment]
I only found one case where the Yes/No button change was not saved. It happened when changing a product category that is also a main shop navigation point (such as jewelry) from yes to no. The error message appears: Error!  Ajax Answer: Internal Server Error 
However, the change will be saved anyway.

**Comment by umulmrum** [comment]
OK, that error is unrelated to this change, so I filed a new issue: https://github.com/chameleon-system/chameleon-system/issues/331
