### ISSUE TITLE
There are Field Types without a valid indextype

### ISSUE THREAD

**Issue by rnuernberg** [chameleon-system/chameleon-system#167]
**Describe the bug**
Several field types (table `cms_field_type`) have no value for the enum field `indextype`. This causes no problem, until someone opens the field type via backend and saves it. Doing so will change the `indextype` from nothing to `index` causing all new fields created with this type to suddenly add an index entry.

**Affected version(s)**
6.1.x, 6.2.x

**To Reproduce**
1. The field type `CMSFIELD_NUMBER` currently has no `indextype` set. Open it via backend - you will see the indextype field to have the value "index". 
2. Save the record
3. Check the value of the field via database - it will now hold the value "index"

**Expected behavior**
There should be no entries without a value for `indextype`. Those that currently hold no value, should have the value set to 'none'

**Screenshots**
![2018-10-25-003](https://user-images.githubusercontent.com/1104497/47502655-aa4a6200-d868-11e8-8408-9b8300ebf6e8.png)

**Comment by UlrichKu** [comment]
@rnuernberg There is already an update for 6.2 (?) doing that: 1526484793

So this only affects 6.1? Where did you have this problem?

What could be done here still: 
- Update the indextype generally where empty.
- Set it to mandatory.
- (The default value für this field is already "none")

**Comment by rnuernberg** [comment]
This should be done for ever shop - not just the demo shop.
