### ISSUE TITLE
Notice: Undefined index: aMapper

### ISSUE THREAD

**Issue by TorbenBr** [chameleon-system/chameleon-system#17]
**Describe the bug**
I get php notice when running updates

Notice: Undefined index: aMapper
File: src/ViewRendererBundle/objects/ViewMapperConfig.class.php
Line: 284

Updates:
- pkgnewsletter - Build #1527064977
- pkgnewsletter - Build #1527064944
- pkgnewsletter - Build #1527064958
- pkgnewsletter - Build #1527065005
- pkgnewsletter - Build #1527065020
- pkgnewsletter - Build #1527064992

**Affected version(s)**
6.2.0

**Comment by umulmrum** [comment]
@TorbenBr I submitted a PR for this issue. Could you test if this fixes your problem? --> https://github.com/chameleon-system/chameleon-base/pull/14

If not, then I require an example failing mapper configuration in the database (I think the easiest way to find one is searching the cms_tpl_module table for entries that contain "TPkgCmsTextBlockMapper_GetText" in the view_mapper_config field).

Thanks!

**Comment by TorbenBr** [comment]
An example where the error occurs

```SQL
SELECT `classname`, `view_mapper_config` FROM `cms_tpl_module` WHERE `view_mapper_config` != '' OR `mapper_chain` != '';
```
```
[..]
MTFeedback	standard
[..]
```

```php
isset($configToChange['aMapper']) === false
```
