### ISSUE TITLE
Tag for mappers

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#170]
**Describe the solution you'd like**
With Symfony 3.4 there will be a lot of deprecation warnings because of the implictly public mapper services retrieved from the service container. We need to get rid of those warnings as they litter the deprecation dialog and the log and decrease performance.

The conceptually easy way is to declare all mappers public, but this is discouraged in the Symfony world.

Therefore I suggest to make adding a tag `chameleon_system.mapper` mandatory for all mappers, so that we can gather those services in a compiler pass and inject them into the MapperLoader (similar to cron jobs and modules in the PR for chameleon-system/chameleon-system#77). This means a bit of migration work and additional work when defining mappers, so we should decide if this is OK. I think we should have a look at autoconfiguration of services which allows to add the tag automatically.

**Comment by UlrichKu** [comment]
After research/tries: This seems to be involved.

It should be doable with two simple steps:
- Auto-tag all mappers (\IViewMapper::class) in ChameleonAppKernel (`registerForAutoconfiguration` + `addTag`).
- Use a compiler pass to collect those (`findTaggedServiceIds`) and add them to the MapperLoader.

See ChameleonModulePass for example.
Note: It is not possible to use the even simpler "tagged" service argument - as this does not inject service references but instances.

**Problem**
However `findTaggedServiceIds` will never return anything that is only tagged by way of `registerForAutoconfiguration`.

Maybe this only works if everything is autoconfigured/autowired?

An (ugly) workaround might be to actually check all services (in ChameleonAppKernel) with `is_subclass_of` and add the tag to all of them directly there. However for this also #257 needs to be solved.

**Comment by UlrichKu** [comment]
Here something similar is described (solved?): https://medium.com/manomano-tech/diving-into-symfonys-dependencyinjection-part-2-symbiosis-with-the-config-component-b535c5a2c591

**Comment by UlrichKu** [comment]
The same problem happens/occurs if I remove the tag "twig.extension" from "chameleon_system_view_renderer.twig.chameleon_standard_extension".

TwigExtension::load() should autoconfigure this. However in TwigEnvironmentPass this service is then missing.

**Comment by UlrichKu** [comment]
Solved/found it now:

`registerForAutoconfiguration` only has effects if autoconfiguration is actually enabled for the respective target service:

Add `autoconfigure="true"` to the service itself or `<defaults autoconfigure="true"/>` to the services.xml.
