### ISSUE TITLE
Saving a table: inconsistent state on validation error

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#171]
**Affected version(s)**
\>= 6.0

**To Reproduce**
1. Create a table ("New")
2. Change name (in text field) and Save
-> There will be a validation error about the missing translation (OK)
-> In the database a table with the changed name exists (WRONG)
-> In the table cms_tbl_conf this new entry still shows "data_new_table" as table name (OK)

**Technical details**
\TCMSTableWriter::Save() executes database changes before the metadata is validated and saved in \TCMSTableEditorEndPoint::Save()

**Comment by UlrichKu** [comment]
This _should_ be a transparent change. So it might be scheduled also for 6.2.

**Comment by UlrichKu** [comment]
NOTE this change has a medium side-effect/bug risk. Extended test is needed.

**Comment by umulmrum** [comment]
Saving a table works. Saving a state where a required field is not set, fails as expected. But I expect an error message - no message is displayed.

**Comment by UlrichKu** [comment]
> Saving a table works. Saving a state where a required field is not set, fails as expected. But I expect an error message - no message is displayed.

The reason here is a JS error in this line:
$('#fieldname_translation').addClass('bg-'+CHAMELEON.CORE.MTTableEditor.mapChameleonMessageTypeToBootstrapStyle(ERROR));
toasterMessage('Field "Title" is required.', 'ERROR'); });

-> ReferenceError: ERROR is not defined.

This is unrelated to the change here.

**Comment by pixeljunkie** [comment]
ERROR should be a string here: 
mapChameleonMessageTypeToBootstrapStyle(ERROR)
