### ISSUE TITLE
confirm step should use explicit system page

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#179]
**Problem**

The confirm step during a checkout (ShopBundle; chameleon-system/chameleon-shop-theme-bundle/Resources/views/snippets/pkgShop/shopBasket/shopBasketCheckoutConfirmStep.html.twig:69) uses a system page (link) for "checkout".

Here the very general mapper TPkgShopMapper_SystemPageLinks is used.

**Describe the solution you'd like**
This system page should be requested specifically (and written as explicit value for the view).

A second question (issue) might be to remove the mapper TPkgShopMapper_SystemPageLinks as it is too general.
Especially it leads to problems (error log) if some (unrelated) pages for system pages are missing.

**Comment by bestform** [comment]
I do not see a particular problem in this approach. It might not be purist to use such a general mapper, but on the other hand it is very practical and has no real drawbacks.
