### ISSUE TITLE
Error handling early in the request lifecycle

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#189]
**Describe the solution you'd like**
If an error occurs early in the request lifecycle (before container build is finished), an error message that is quite cryptic in this context is logged (caution: NOT in dev mode):

"You have requested a non-existent service "You requested the container in a state where it is not available. Use this method only after container initialization.""

Although the real error message is also logged, this makes understanding what's going on a bit difficult and we should avoid it.

**Possible solution (if any)**
This behavior is caused by TCMSErrorHandler::ShutdownHandler where TGlobal::instance() is called which accesses the service container. This error handler is even registered twice: The first time in chameleon::boot(), the second time in RequestInitializer::registerErrorHandler(). I can't imagine a sane reason why this was doubled, so we should remove the call in boot() so that the error handler is only registered after container compilation. The RequestInitializer is still called very early during the request lifecycle, so we only lose the ability to send emails during container compilation, which happens during or directly after deployment, so the administrator is already aware of the problem.

**Comment by UlrichKu** [comment]
Easy way to force this (before 6.2.4): put an error in the parameters.yml - ie a single @ in a value.
