### ISSUE TITLE
Upload dialog in new media manager crashes

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#190]
**Describe the bug**
Type error: Argument 1 passed to TPkgSnippetRenderer_TranslationNode::__construct() must be an instance of Twig_NodeInterface, instance of Twig_Node_Text given, called in vendor/chameleon-system/chameleon-base/src/SnippetRendererBundle/objects/customTags/TPkgSnippetRenderer_TranslationTokenParser.class.php on line 64

**Affected version(s)**
6.3

**To Reproduce**
1. Open new media manager
2. Click on Edit icon of any image for the details view
3. Click on "replace"

**Expected behavior**
no error 500, show upload form

**Screenshots**

**Desktop (please complete the following information):**
- all

**Smartphone (please complete the following information):**
 - all

**Technical details**
Looks like a bug with new symfony version or twig upgrade

**Comment by UlrichKu** [comment]
It seems to be the notation {% trans %}key{% endtrans %} that is problematic here.

Somewhat odd because symfony has at least still test cases for this.
