### ISSUE TITLE
Backend: remove MTVersionInfo template and pagedef

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#192]
**Describe the bug**
MTVersionInfo never existed in the core.
The pagedef and module view was added to the core without the module 5 years ago and is not used anywhere (impossible without the module)

**Affected version(s)**
4.0 or newer

**To Reproduce**
1. call ?pagedef=versioninfo
4. See error 500 because of missing module

**Expected behavior**
Files should not exist

**Desktop (please complete the following information):**
 - all

**Smartphone (please complete the following information):**
 - all

**Technical details**
remove:
- chameleon-base/src/CoreBundle/private/rendering/pages/versioninfo.pagedef.php
- chameleon-base/src/CoreBundle/private/modules/esono_cmsversioninfo_MTVersionInfo/views/standard.view.php

**Comment by pixeljunkie** [comment]
The old internal issue from the past says that this feature was experimental and not ready. I think we can skip deprecation here and remove the 2 files. No one will miss anything.

**Comment by umulmrum** [comment]
See https://github.com/chameleon-system/chameleon-system/issues/193#issuecomment-438638297 - could you file a deprecation PR @pixeljunkie?

**Comment by umulmrum** [comment]
OK, I changed my mind about being that 100% strict a bit. Could you rechange the PR to remove those files? Sorry for chasing you around here.

If you cannot do this just now, we can still keep the files for a while as they don't hurt.

**Comment by pixeljunkie** [comment]
done.
