### ISSUE TITLE
Backend: remove orphaned LicenseManager files

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#193]
**Describe the bug**
The PkgLicenseManager was removed in 6.1 but we forgot to remove some core files. We can skip deprecation here because these files are not usable on their own and deprecation was set in a 5.x version.
There is a deprecated/unusable stub class for the login page that was needed for the 6.1 release to be able to login and run updates. The database table for licenses does not exist anymore (removed with 6.1) so the class extension is an orphan, too.

**Affected version(s)**
6.3

**To Reproduce**
1. Check for files with LicenseManager in the filename

**Expected behavior**
Files should not exist since version 6.2.

**Technical details**
Remove:
- CoreBundle/private/modules/TPkgCmsLicenseManager_MTLicenseManager/*
- CoreBundle/private/modules/MTLogin/TPkgCmsLicenseManager_MTLogin.class.php
- CoreBundle/private/rendering/pages/pkgCmsLicenseManager.pagedef.php

**Comment by umulmrum** [comment]
@pixeljunkie Although I'm a big fan of cleaning things up, we shouldn't skip the deprecation step. Maybe the files are no longer needed, but we can't know for sure (and should also not guess, but stubbornly follow semantic versioning). There are cases where we delete files directly, but that should be a rare exception.

The PR is fine as long as we don't merge it yet - in time the master branch will be used for version 7.0, then we can merge. Could you also open another PR that deprecates those files (also against master)?

**Comment by pixeljunkie** [comment]
changed the deletions to deprecations
