### ISSUE TITLE
Missing Data Attributes on Table Fields

### ISSUE THREAD

**Issue by ApricumMedia** [chameleon-system/chameleon-system#194]
**Describe the bug**
Data attributes appended to individual cells of managed tables have been lost to cleanup effort in commit `2d87a250` (original repository). Features depending on these data attrbutes have been non-functional since the removal (primarily inline-, overlay-, and bulk editing).

**Affected version(s)**
All versions after the noted commit are affected, since the introduction of these attributes to the public branch.

**To Reproduce**
No reproduction required, all versions affected.

**Expected behavior**
Data attributes with extended information on the table and its fields are expected to be present on the `<table>`, its `<tr>` table rows and respective `<td>` table data cells.

**Desktop (please complete the following information):**
Not a front-end issue, all platforms affected.

**Smartphone (please complete the following information):**
Not a front-end issue, all platforms affected.

**Comment by umulmrum** [comment]
I think we found the underlying issue and it's not related to chameleon-base - please reopen if there is still a problem.
