### ISSUE TITLE
List queries get overwritten on update to Chameleon 6.2

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#20]
**Describe the bug**
It is not the best idea to overwrite list queries in Chameleon updates, yet we did it. This leads to broken backend list views for pages in multi-portal systems.

**Affected version(s)**
6.2.0

**To Reproduce**
1. Go to the "Pages" view in the Chameleon backend (multi-portal system, maybe a custom query is required to reproduce).
2. The page crashes.

**Expected behavior**
The pages view should be displayed as before the migration.

**Technical details**
The list query was changed in src/CoreBundle/Bridge/Chameleon/Migration/Script/update-1527678214.inc.php (as well as another list query in src/CoreBundle/Bridge/Chameleon/Migration/Script/update-1527678214.inc.php which could lead to another problem). This messes things up when a custom query was used before.

**Comment by bestform** [comment]
This is fixed with the merged PR.
