### ISSUE TITLE
Broken detail url for products without category or manufacturer

### ISSUE THREAD

**Issue by pSpeck** [chameleon-system/chameleon-system#201]
**Describe the bug**
If a product has no category connection and no manufactuerer the product url will look like
//productname_pid_0_7696.html. This double slash leads to the browser just adding https:// https://productname_pid_0_7696.html. In this url the portal domain is missing.

If you add the missing portal domain https://domain.de/productname_pid_0_7696.html the shop will display the 404 page. But for https://domain.de//productname_pid_0_7696.html the product page is displayed.
 
**Affected version(s)**
6.2

**To Reproduce**
1. Search for article in shop search
2. Go to cms and remove category and manufacturere connection for article displayed in search
3. Redo Search
4. klick changed article
5. Invalid url

**Expected behavior**
I think the second / should be removed on link generation.So the it will alway display the correct detail page.

**Comment by UlrichKu** [comment]
Relevant location: vendor/chameleon-system/chameleon-shop/src/ShopBundle/mappers/article/TPkgShopMapper_ArticleTeaserBase.class.php:72

**Comment by UlrichKu** [comment]
The main problem here is/was: the "productPath" part of an article url could be empty but that was not expected in other locations.
Now they are always set (default - so here -/-)
