### ISSUE TITLE
Improved Error Reporting for Missing Routes

### ISSUE THREAD

**Issue by ApricumMedia** [chameleon-system/chameleon-system#202]
**Describe the solution you'd like**
If a route with improper configuration is requested, the usual returned exception is mainly an unhandled index-out-of-range-error for the ordered collection of routes. The message reads as:

```
Undefined offset: 9
```

Instead, information about the accessed route and its parameters should be provided.

**Possible solution (if any)**
Baseline suggestion: https://github.com/chameleon-system/chameleon-base/pull/89

**Comment by umulmrum** [comment]
It was never intended that an error can occur at this stage. Before improving the error message at that spot, we should check if we can avoid the error altogether (guess: The error is caused by incomplete tree/page data in one or more languages).
