### ISSUE TITLE
Backend: replace jQuery UI components with bootstrap 4 components

### ISSUE THREAD

**Issue by ckleis** [chameleon-system/chameleon-system#204]
**Describe the solution you'd like**
Some components in the backend are based on a very old version of jQuery UI. We want to replace all of them with bootstrap 4 (or compatible) components.

Components:
- tabs
- date/time picker
- overlays
- autocomplete/typeahead
- maybe dropdown buttons?

**Possible solution (if any)**
Replace all components with basic bootstrap 4 components and add BS4 compatible components where needed (datepicker)

**Comment by esono-anja** [comment]
Picked date is not saved.
![datepicker](https://user-images.githubusercontent.com/15125103/53030205-ab804a00-346a-11e9-92f3-795a50b6023e.png)

**Comment by esono-anja** [comment]
Search field in lists:
The list with search field wobbles a little bit after hitting enter 
- enter a general search term, e.g. bracelet (do not select a specific record) => hit enter
=> the list, especially the search button, wobbles a bit. Same behaviour, when you click the close-cross
![liste1](https://user-images.githubusercontent.com/15125103/53496218-d3426400-3aa1-11e9-8ee1-0039823d1889.png)

**Comment by esono-anja** [comment]
Filter product list by type - hitting the search button is required
![liste2](https://user-images.githubusercontent.com/15125103/53496508-7d21f080-3aa2-11e9-9533-b3b7f8480b49.png)

 - open the product list and filter according to product type (at the very left)
=> you have to click on the search button to get the results. I would expect it to work right after the selection. This is actually the behaviour in editorial article lists, but not for the product list. I would expect the same behaviour for all lists.

**Comment by ckleis** [comment]
Error with saving a changed date with time is solved:
With commit "ref #306: TCMSFieldDateTime with seconds" the format has changed from "" to "LTS". This was not considered in the corresponding tableEditor.js yet and led to the error.

**Comment by ckleis** [comment]
A search and the reset of the search triggers a reload of the page. The icons are reloaded and placed. Is that what you mean by wobbling?

**Comment by ckleis** [comment]
Yes, it is true that the selection for the product type and for Active is only executed when you click on the Search button. This was already the case before. However, the new text search is executed at once.
This was discussed with Sven, but can be weighed up again.

**Comment by ckleis** [comment]
With Issue #256 the functionality has been added that the form is sent on change of the select fields product type and active.

**Comment by esono-anja** [comment]
> A search and the reset of the search triggers a reload of the page. The icons are reloaded and placed. Is that what you mean by wobbling?

Yes, that's what I mean. It's not a tragedy, just thought, I should mention it. Can it be fixed easily? Or should it be fixed at all, @umulmrum ?

**Comment by umulmrum** [comment]
I think we can yet live with that :-)
