### ISSUE TITLE
Wrong discount Voucher Handling on Payment Transactions (credit and debit)

### ISSUE THREAD

**Issue by pSpeck** [chameleon-system/chameleon-system#208]
Describe the bug
If you use a discount voucher within your order and pay items partially. 
After you refund an item the used voucher value for this item will be added to the next item to capture without a check if the voucher is allowed for this item. 

If you now want to refund this item too the cms wants to refund more than is has captured before because is takes only the discount set in the order item not the used from the transaction.

**Affected version(s)**
6.2

**To Reproduce**
1. Make an order with a discount voucher.and more than one item
2. Capture first itme and than refund it
3. Capture second item -> transaction now uses discount from the before refunded item
4. Refund the second item -> discount was lower than before captured.

**Expected behavior**
The cms should only capture and debit discounts that are set in the order item. 
So on refunds no voucher value will not be able to use again in  following captures.

**Comment by esono-anja** [comment]
Payment method Payone returns 500er internal server error after confirmation (after clicking buy now).

**Comment by pSpeck** [comment]
It seams that payone is not configured.

**Comment by umulmrum** [comment]
Fixed this on the test server - could you retry?
