### ISSUE TITLE
MediaManagerBundle: module needs header less template for image picking mode

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#217]
**Describe the bug**
Currently the new mediaManager has only one possible state.
Open it in a new window with the full CMS header or iframe/header less mode.
But we need both at the same time. In image picking mode of image fields the media manager is opened in an iframe dialog to select the image. Here we need an iframe mode without the CMS header.

**Affected version(s)**
6.2.x

**To Reproduce**
1. Open a record with an image field TCMSFieldMedia
2. Click on the icon to select an image.
3. The media manager opens
4. It has a full CMS header with breadcrumb

**Expected behavior**
In this mode the header should not be shown.

**Desktop (please complete the following information):**
 - All

**Smartphone (please complete the following information):**
 - All

**Technical details**
MediaManagerUrlGenerator needs to use a different pagedef in method: getUrlToPickImage

**Comment by pixeljunkie** [comment]
1. The title is mandatory at the moment... and a placeholder. It could be changed to something like "pick your desired image"
2. The inner scrollbar is there because this is a dialog with an iframe. There is no way around it. It was fixed in Full mode, where the media manager is opened as part of the outer page.

**Comment by umulmrum** [comment]
OK, I think we can leave it as is for the moment.
