### ISSUE TITLE
MediaManagerBundle: search uses OR instead of AND now

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#219]
**System behavior before the change**
The search in the media manager used AND for the search terms.

**System behavior after the change**
The search in the media manager is not very usefull now, because it changed from an AND search to an OR search.
That means looking for "t-shirt blue" finds everything including "blue" instead of filtered by t-shirt and blue. This makes it hard to find images in bigger libraries.

**Affected version(s)**
6.2.x

**Comment by pixeljunkie** [comment]
The problem is not so easy to fix. because it is not a full replacement from OR to AND. We need  handle the fields and tables differently in the query and not just combine them all with OR.

Current query parts example all of them combined with OR.
![selection_068](https://user-images.githubusercontent.com/958920/49211002-cfc61080-f3be-11e8-928e-6a64c86e5c56.png)

Instead the query should look like this to get the best matching results:

* id and cmsident needs to be searched with OR and fullTerm of course.
* description and path with AND between any search term part
* descriptions in ALL languages, not just the active language, because in most of the cases the name is only set in the base language
* tags with AND

WHERE 
id LIKE fullTerm 
OR 
cmsident LIKE fullTerm) 
OR 
(description__de LIKE term1 AND description__de LIKE term2)
OR 
(description LIKE term1 AND description LIKE term2)
OR
(path LIKE term1 AND path LIKE term2)
OR
id IN (SELECT tags subquery... cms_tags LIKE term1 AND cms_tags LIKE term2)

**Comment by umulmrum** [comment]
(labelled as feature, as the media manager is completely new and therefore not subject to BC breaks, although I understand that user perspective might vary)

**Comment by esono-anja** [comment]
1. Tags should work with AND. (Currently it looks like OR b/c the tag "bunt anja" finds also the tags "anja" and "bunt".)
2. Fields "Alt Tag" and "System Name" should be searched as well.

**Comment by umulmrum** [comment]
@pixeljunkie Could you have a look at note 1?

I added a separate issue for note 2: #262.

**Comment by umulmrum** [comment]
We're running out of time in this release, and the fix for tags isn't that simple, so I filed a separate issue #266.
