### ISSUE TITLE
Media manager: Hidden fields are saved?

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#222]
Noticed during #30.

**Describe the bug**
Not really sure if this _is_ a bug (and where):

When saving the replacement image in the new media manager finally the central TCMSTableEditorEndPoint::_WriteDataToDatabase() is called.
Here the "height" field is defined as hidden and this could/should lead to it not being saved (line 1677).
In fact maybe due to this there is an extra save for height in \TCMSTableEditorMedia::PostSaveHook() - which however should not work either.

However the basic \TCMSField::GetDisplayType() returns "none" - the data from the sqlData['modifier'].
This does not correspond to the fieldModifier though (which is correctly "hidden").

Seen most generally this could mean that hidden fields generally are saved although they should not be.

**Comment by bestform** [comment]
I do not see why hidden fields should not be saved. It is "hidden", not "read only". If I am mistaken, please reopen the issue with further information.

**Comment by UlrichKu** [comment]
If I remember correctly (two) things: The "height" of an image is a rather strange/legacy field with special handling.

Also that "hidden" leads to it being (should) not overwritable might also be a legacy behavior.

However there are cases where these two combined lead to unexpected results.

(not reopening it though as too outdated and strange)
