### ISSUE TITLE
Media manager: lines not easy to distinguish

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#223]
**Current situation**
The lines and contents an (overview) view of the media manager are not visually separated.

This is the current view of "Jewelry":
![selection_106](https://user-images.githubusercontent.com/20949224/49231224-c609d080-f3f1-11e8-9ed2-7da374d4bc88.png)

There is no real separation between images, icons, texts and the next line.

**Describe the solution you'd like**
Visual elements to separate them.
Ie use alternating background colors for different lines and maybe a border around each element (image + icon + text).

**Comment by pixeljunkie** [comment]
I will address this in the 6.3 backend changes.

**Comment by pixeljunkie** [comment]
We should use bootstrap cards here: https://getbootstrap.com/docs/4.1/components/card/

**Comment by umulmrum** [comment]
@pixeljunkie We should be careful not to overextend ourselves on the redesign. I think this issue is not *that* urgent, so we should get the more important things done first (unless this is really minor work).

**Comment by pixeljunkie** [comment]
@umulmrum The new media manager borrowed some styles from bootstrap 4 already and so i had to work on the styling here as part of #99. They image containers now have borders and the classic list view has some borders, too. Looks way better now.

**Comment by umulmrum** [comment]
Was implemented as part of #99.
