### ISSUE TITLE
Field Document (TCMSFieldDocument) shows no directories for upload in select-Field

### ISSUE THREAD

**Issue by ckleis** [chameleon-system/chameleon-system#239]
**Describe the bug**
The select field to choose a directory for upload contains only ">>"

**Affected version(s)**
6.2.4.3

**To Reproduce**
1. I created a new field of type Document (TCMSFieldDocument) with name cms_document_id
2. When testing the field I wanted to upload a file, but the select field to choose the upload directory only shows double arrows.

**Screenshots**
![selection_236](https://user-images.githubusercontent.com/26296728/49860729-ad8ab480-fdfa-11e8-9fa3-4afeecce6984.jpg)

**Comment by umulmrum** [comment]
Test: Please test by using German as display language. When using English as display language, there is no change, this is OK for now (English translation missing, see #240 ).
