### ISSUE TITLE
Backend: Wysiwyg does not find "chameleon.css"

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#246]
**Describe the bug**
(Backend) WYSIWYG fields need an additional css file. While loading it there will be a 404 or 500 error.

**Affected version(s)**
\>= 6.2

**To Reproduce**
1. Clear cache
2. Open the page of a main product
-> In the network tab of the browser tools there will be two error messages for "chameleon.css".

**Technical details**
The file web/assets/wysiwyg/default.css will try to import /assets/less/chameleon.css which does not exist.
(Loaded from \TCMSFieldWYSIWYG::getEditorCSSUrl())

**Comment by umulmrum** [comment]
I think we can simply remove the import statement.
