### ISSUE TITLE
Remove legacy media manager

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#25]
**Describe the solution you'd like**
The new media manager introduced in Chameleon 6.2.0 completely replaces the old one, but the latter does still exist for BC reasons. In this issue the old media manager should be removed. 

Tasks:
- Remove deprecated code entities (classes, methods, properties, ...).
- Hide or remove the database field cms_media.time_stamp (check if it is still used for other purposes).
- Remove the container parameter "chameleon_system_core.render_media_properties_field" and all usages (main use is in TCMSFieldMediaProperties which should be removed at the same time).

Maybe other tasks, be sure to check.

**Comment by umulmrum** [comment]
Also see comments in duplicate issue #220

**Comment by UlrichKu** [comment]
Is there a need for any migration work? Configuration change?
