### ISSUE TITLE
Backend: replace search field in lists with autocomplete select2 box

### ISSUE THREAD

**Issue by ckleis** [chameleon-system/chameleon-system#256]
**Describe the solution you'd like**
In most of the cases the search term field in backend lists is uses to search a single record. So it should be possible to get an autocomplete of records here and allow an explicit selection of a record instead of performing a full search with page reload which is much slower.
This will make it faster and easier to get to the target record.
Nevertheless it needs to be possible to perform a search for a substring of course.

**Possible solution (if any)**
We already have the same feature in the tableEditor head. 
The select2 features a tag mode which allows creation of new items which would be the equivalent of running a substring search like the current behaviour.
(We already tested this feature)
Note: It should be checked if it possible to send the whole form with filter settings, so the autocomplete lookup is accurate and filtered, too.

**Comment by umulmrum** [comment]
I think we're already good here, aren't we? @ckleis @pixeljunkie

**Comment by esono-anja** [comment]
Pages do not have the autocomplete select2 box. 
I haven't checked all of the lists - should I? Or can you check faster if any other list does not have the new search field?

**Comment by umulmrum** [comment]
You mean the "Pages" list? Right, it's missing there. Could you have a look @ckleis?

I think it's OK if we miss a few lists. It's quite unlikely that other lists behave differently, and we can live with this risk.

@ckleis Could you also have a look at the search functionality per se? It doesn't really work for me. If for example I search in the product category list for "earrings", and press enter, nothing happens and the search string disappears after pressing the Enter key.

**Comment by ckleis** [comment]
The select2 field searches via ajax for the available records and suggests them.
Then there are basically 2 functionalities.

First, you select a record or enter exactly one search term that matches a record, then this record is edited directly after selection. This works well.

Secondly, a search term is entered that does not exactly match ONE data record. Now a search should be executed with the entered search string. Unfortunately, this does not always work. Sometimes/often the search is simply not triggered. When debugging I saw that sometimes it doesn't go to on('select:select') or if it does, it sometimes doesn't go to newOption (see table.js, line 158). This looks like an error of the select2()-plugin.

Another error is reproducible:
1. a search is executed correctly.
2 The search is reset with the x within the select field. So far it works.
3. don't change the select2 field anymore and send the form with the send button.
=> Then suddenly the previous search term is again in the select2 field and the selection is executed again.
I couldn't find out where the program remembered the already cleared search string and restored it.

**Comment by esono-anja** [comment]
If you enter a search term in the autocomplete search box in Firefox, a strange page opens:
![ff_liste](https://user-images.githubusercontent.com/15125103/54546630-5ae60900-49a4-11e9-8641-d19e01bd10c9.png)

To reproduce:
1. Open a list, e.g. the product list.
2. Enter a searchterm and hit enter or the search button.
=> The odd page opens.

**Comment by ckleis** [comment]
https://shop-demo-master.devbox-ckleis.intra/cms?_user_data=&_sort_order=&_listName=cmstablelistObj238&pagedef=tablemanager&id=238&_histid=0&_rmhist=true&_startRecord=0&cmsauthenticitytoken=7tNzlZ9bfTbcglI6XZaVMl9ReQLT6w3UOk6wPSEDkow&module_fnc%5Bsidebar%5D=ExecuteAjaxCall&_fnc=saveActiveCategory&categoryId=e59efad6-1d30-0a6c-f46b-065b41ba0b5a&filterArticleType=parents&is_active=all&_search_word=cham&_limit=20&cmsauthenticitytoken=7tNzlZ9bfTbcglI6XZaVMl9ReQLT6w3UOk6wPSEDkow&_search_word=cham

**Comment by umulmrum** [comment]
I think I found a valid (but ugly because of an ugly underlying problem) solution.

As we had difficulties when trying to reproduce: The problem occurs when on a list page and then opening another sidebar category. After that the problem wasn't completely reliable but occurred for me after some playing with search field searching and search term resetting.
