### ISSUE TITLE
Media Manager "find usages" should be optional on the edit media page

### ISSUE THREAD

**Issue by rnuernberg** [chameleon-system/chameleon-system#258]
**Describe the solution you'd like**
When editing an existing image via the media manager, the view that opens includes a list of usages of the image. This is a nice feature when the database that needs to be searched for this has a reasonable size. 
As soon as the database becomes larger, finding usages takes a prohibitive long time resulting in a long wait when opening the edit window.

**Possible solution (if any)**
The simplest solution would be, to make loading the usages list optional on opening the edit view. Instead, the usages could then be requested via the click of a button.

A better solution would be, to reduce the time it takes to generate the usages list.

**Comment by bestform** [comment]
I will close this as a duplicate for #455
