### ISSUE TITLE
MediaManager: deleting directory without confirmation / not user friendly

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#276]
**Describe the bug**
If you delete a folder in the new media manager there are a few things that should not happen:

1. There is no confirmation asked if you are really sure you want to delete ALL the images in this folder and all folders below. I think, this is fatal! One click... everything is gone.
2. It looks like the deletion is done without checking the system for usages. Is this intended? I don't think so. And if (would be o.k. with me), we would need a warning text that tells me this.
3. After the click, the node is gone, but the real process of deleting the images and all of its relations is done afterwards. So, if the deletion process breaks, because of too many images this would lead to orphans in the database that are not accessible.
4. The deletion process is non blocking. It is done in the background. This means, if you reload the page the process would stop. And because the user gets no message, that the process is running, the user thinks it did not work and goes on using the backend, which of course kills the process.

**Affected version(s)**
6.2.x

**To Reproduce**
1. new media manager
2. right click on any node (choose a sub node with many images)
3. click delete
4. See the problems described above

**Expected behavior**
1. open a modal dialog showing a text and confirmation button
2. run usage check and show found items
2. if some where found, ask if they should be deleted anyway
3. ask for another confirmation or if not found go on
4. delete the images and update relations
5. delete node after all images where deleted

I would recommend to make it possible via config parameter if images should be deleted without the usage check. In projects with a very big database the usage check runs a very long time.
For this problem an index or something is need, but this is a very big, complex issue. 

**Desktop (please complete the following information):**
- All

**Smartphone (please complete the following information):**
 - All

**Comment by UlrichKu** [comment]
Adding a confirmation dialog is the minimum functionality here.

The remainder might be another ticket.

**Comment by UlrichKu** [comment]
With https://github.com/chameleon-system/chameleon-base/pull/326 added only a confirmation dialog.
