### ISSUE TITLE
Change log: Record position changes lead to Internal server error

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#279]
**Describe the bug**
Changing the position of a table entry with activated change log recording leads to the display of a "Ajax response: Internal server error" popup.

The position is still changed but the change not recorded.

**Affected version(s)**
6.2.6

**Technical details**
Introduced with #230.

**Comment by esono-anja** [comment]
Not working:
`Error! Ajax response: error
`
The position is not changed and the change is not recorded.

**Comment by UlrichKu** [comment]
Probably (only) the wrong thing deployed.

**Comment by esono-anja** [comment]
The position is changed (no error notification anymore), but the change is not recorded.
It seems as if the changelog is not working at all at the moment, no changes whatsoever are recorded today.
