### ISSUE TITLE
Backend: list filter in shop bundle needs bootstrap 4 modifications

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#280]
**Describe the bug**
In 6.3.0 the backend is upgraded to bootstrap4.
There may be some migrations needed in the shop bundle to fix styling issues.
I found one already. In the product list, the select boxes for product type and active state miss a "form-group" container which leads to non floating form elements.

**Affected version(s)**
6.3.0

**To Reproduce**
1. Go to products table
4. See form elements with breaks instead of floating left

**Expected behavior**
form elements should float left

**Screenshots**
![selection_132](https://user-images.githubusercontent.com/958920/51681802-03e83700-1fe6-11e9-8ef0-d682612d869a.png)

**Desktop (please complete the following information):**
 - All

**Smartphone (please complete the following information):**
 - All

**Technical details**
TCMSListManagerShopArticles::PostCreateTableObjectHook

**Comment by pixeljunkie** [comment]
Added a closing div and form group div as test.
Works, but we need an additional bottom align as default for form-groups at this position for form elements without a label above

```
        $filterSection .= $this->getFilterFieldArticleType($filterArticleType);
        $filterSection .= "\n</div>\n";
        $filterSection .= "<div class=\"form-group\">\n";
        $filterSection .= $this->getFilterFieldActive($isActive);
```

**Comment by umulmrum** [comment]
Looks good to me in current master. WDYT @pixeljunkie @ckleis?

**Comment by umulmrum** [comment]
Looks good to others, too :-)

**Comment by esono-anja** [comment]
Looks good to me, too ;)
