### ISSUE TITLE
Two portals with the same domain name possible

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#284]
**Describe the bug**
It is possible to add two portals which both have the same (or missing) "Identifier/prefix" and both have at least intersecting "Domains" (domain names).

In such a case routing is generally not possible: Which portal and thus for example different language belongs to which page/URL?

**Affected version(s)**
\>=6.0

**Comment by UlrichKu** [comment]
A minor problem that also appears here:
Also (only) setting the same address for two domains in different portals is possible. This leads to confusing effects like the language being wrong from _some_ parts of a page.

**Comment by bestform** [comment]
This is basically a "sh*t in, sh*t out"-Problem. We could work around that with a check when saving the settings but this again would make it more difficult to edit if you want to move a setting from one portal to the other. So I will close this, but if you have strong objections, feel free to reopen.
