### ISSUE TITLE
Backend: record editing: buttons styling responsive

### ISSUE THREAD

**Issue by ckleis** [chameleon-system/chameleon-system#285]
**Record-Editing**
![selection_247](https://user-images.githubusercontent.com/26296728/51820316-9da93000-22d5-11e9-8634-ba22261c3ee0.jpg)
When editing the record the buttons should be made with bootstrap-navbar, with space between and for the icons the font Awesome should be used.

**Comment by ckleis** [comment]
Button navigation: Bootstrap navigation wasn't necessary.
But responsive styling with Font Awesome Icons:
![Uploading Selection_248.jpg…]()

**Comment by ckleis** [comment]
![selection_248](https://user-images.githubusercontent.com/26296728/51841893-eda4e880-230f-11e9-8798-e1f9974b6887.jpg)

**Comment by esono-anja** [comment]
tested: ok
Just one question: The button "table configuration" is grey in the list and yellow in the record itself. 
Is that a bug or a feature?

**Comment by ckleis** [comment]
Neither a bug nor a feature ;-)
But it should look like the same, so I changed it in the lists that the "Table configuration" button is yellow and the "Delete" button is red.

![selection_286](https://user-images.githubusercontent.com/26296728/53323056-6e3e1100-38dd-11e9-85cd-c7268eae593c.jpg)
