### ISSUE TITLE
Backend: replace button icons with font awesome icons

### ISSUE THREAD

**Issue by ckleis** [chameleon-system/chameleon-system#288]
There're still many old icons that should be replaced by Font Awesome icons.
For example: 
![selection_249](https://user-images.githubusercontent.com/26296728/51910117-8e59dd80-23ce-11e9-9844-b460e6d45561.jpg)

**Comment by esono-anja** [comment]
Looks good to me, I didn't go through all of the tables, but through many, and it looks like the icons are replaced everywhere.
The only icon I don't understand is this one:
![transl](https://user-images.githubusercontent.com/15125103/53105155-e3ea5b80-3530-11e9-801a-c03603a0112f.png)
I think it is the "not translated yet" icon. But I cannot detect it as such, at least not intuitively.

**Comment by umulmrum** [comment]
The icon was inspired by the Wikipedia language switch icon, so some users might be familiar with this. Even if not, the icon's tooltip explains its purpose. Do you think this is enough? Or do you have an idea how to improve?

**Comment by esono-anja** [comment]
Ok, I learned something new here. It is obviously a commonly used icon for translation, as the internet tells me. I didn't know it and still find it a bit odd, but since it is common, let's use it.
