### ISSUE TITLE
Ugly sort view in backend

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#295]
**Describe the bug**
When sorting records in a field of type "value list from table (multiple selection possible)", the resulting view is obviously unstyled (but seems to work anyway).

**Affected version(s)**
6.3.0

**To Reproduce**
1. Configure a field as "value list from table (multiple selection possible)" and set bAllowCustomSortOrder=true
2. In the table view of the table with this field, add at least 2 items.
3. Click the "Order records" button (could have been renamed to "Sort records" in the meantime).
4. See error.

**Expected behavior**
Style should look the same as for other sorting views.

**Comment by esono-anja** [comment]
No error anymore, but the styling still looks a bit odd.
![295_1](https://user-images.githubusercontent.com/15125103/53494493-2f0aee00-3a9e-11e9-9533-13309e13348b.png)
It should look like this:
![295_2](https://user-images.githubusercontent.com/15125103/53494504-37fbbf80-3a9e-11e9-9a5a-b52bafa8d221.png)

**Comment by umulmrum** [comment]
@pixeljunkie Could you ..?

**Comment by esono-anja** [comment]
Just found an error: it is not possible to drag and drop an item to the very top. You can only move the line up to the 2nd position. To get it to the first place, you have to drag the top line down.
![pos_drag1](https://user-images.githubusercontent.com/15125103/53560246-38eb2a80-3b4c-11e9-8ed9-5890025d7a9a.png)

Result:
![pos_drag2](https://user-images.githubusercontent.com/15125103/53560257-3e487500-3b4c-11e9-9ff4-1410a21a7c94.png)

**Comment by pixeljunkie** [comment]
> styling still looks a bit odd

Changed the styling of table based sortable list to look like the field sort list.

**Comment by pixeljunkie** [comment]
> it is not possible to drag and drop an item to the very top. You can only move the line up to the 2nd position. To get it to the first place, you have to drag the top line down.

Fixed. There was simply no room for the drag&drop, so adding a padding top to the list fixed the problem.
