### ISSUE TITLE
Backend: statistics styling

### ISSUE THREAD

**Issue by ckleis** [chameleon-system/chameleon-system#297]
The statistics are not styled yet:
![selection_255](https://user-images.githubusercontent.com/26296728/52394956-95f34380-2aac-11e9-8369-3e28bbc2d926.jpg)

Styling should be also responsive.

**Comment by esono-anja** [comment]
Styling is fine.
But the "bar chart" view is not quite right yet:
a) the bar does not start at zero 
b) the print view is broken (no bar is displayed)

**Comment by pixeljunkie** [comment]
I think you can not test this without a lot of orders as statistic data. We should check this with some test data again. 
And of course it would be quite nice to have some fancy charts here (like with chart.js) which we should add in one of the next releases.

**Comment by umulmrum** [comment]
I'd say this is good enough for now :-)
