### ISSUE TITLE
MediaManagerBundle: legacy list view mode crashes

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#3]
**Describe the bug**
The old list view, that is available in the media manager record listing as an option to view the records crashes fatal, because class MediaManagerShowAsTableManagerListModule was not found.

**Affected version(s)**
6.2

**To Reproduce**
1. Open new MediaManager
2. Click on the last icon above the list of media records
3. See error

**Expected behavior**
Show the media list in legacy mode.

**Screenshots**
![screenshot-2018 07 27-17-30-20](https://user-images.githubusercontent.com/958920/43330230-e5c5fb2e-91c2-11e8-84ad-af8b91267b3b.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser chrome, ff

**Technical details**

> Attempted to load class "MediaManagerShowAsTableManagerListModule" from namespace "ChameleonSystem\MediaManagerBundle\Bridge\Chameleon\BackendModule".
> Did you forget a "use" statement for another namespace?

Looks like the filename of this class has a typo.

**Comment by pixeljunkie** [comment]
This is not an issue on my dev system where german is the primary language. Maybe this is an issue with english as primary language only. I would suggest adding another issue because the original bug subject is fixed.

**Comment by umulmrum** [comment]
I added another issue to rethink the legacy list altogether: https://github.com/chameleon-system/chameleon-system/issues/28

Until then I deactivated the list as it isn't usable and isn't that essential.
