### ISSUE TITLE
Media manager: Replace image keeps old image's dimensions

### ISSUE THREAD

**Issue by proligde** [chameleon-system/chameleon-system#30]
**Describe the bug**
When an image is replaced within the media manager, the resolution of the old image is kept which leads to strange effects.

**Affected version(s)**
6.2.1, 6.2.0

**To Reproduce**
1. Go to Media Manager
2. Click on an existing image (edit in the bottom right corner). See the dimension i.e. 540x75px
3. Click on "Replace" and replace with an image of a completely different resolution i.e. 191x75px
4. The resolution is still shown as 540x75 and is used for any further image size recalculation which leads to broken image sizes everywhere this image has been used.

**Expected behavior**
The image resolution should be that of the new image

**Comment by UlrichKu** [comment]
Seems to happen only if the height stays the same.
