### ISSUE TITLE
Backend: Products: styling error with field "Is a variant of"

### ISSUE THREAD

**Issue by ckleis** [chameleon-system/chameleon-system#308]
**Describe the bug**
Incorrect distance in field "Is a variant of". The button must be left-justified.
![selection_269](https://user-images.githubusercontent.com/26296728/52618750-f533c800-2e9f-11e9-9453-78b589363f23.jpg)

**Comment by pixeljunkie** [comment]
Normally, there should be a name of the variant placed left to the button. Maybe this is misconfiguration?

**Comment by esono-anja** [comment]
I could also only find examples where the product is to the left of the button. I would say it is ok.
![variante_308](https://user-images.githubusercontent.com/15125103/53428041-56a07e80-39ea-11e9-9b2a-43f4a292a686.png)
