### ISSUE TITLE
Back End: List status gets lost on back or on breadcrumb-click

### ISSUE THREAD

**Issue by proligde** [chameleon-system/chameleon-system#31]
**Describe the bug**
When searching something in / or changing sort order of a list in the back end - this info is lost on a breadcrumb-click or on a back-click.

**Affected version(s)**
6.2.0, 6.2.1

**To Reproduce**
1. Go to any list in the back end. For example on "My Pages"
2. Search for something - for example "Impressum"
3. Click "My Pages" in the breadcrumb navi

**Expected behavior**
the Settings should be kept - I expect to have still my search vor "Impressum" active

**Comment by umulmrum** [comment]
Workaround: Use the chameleon-base branch from this PR: https://github.com/chameleon-system/chameleon-base/pull/21 (or chameleon-base 6.2.x after merge, or chameleon-base 6.2.2 after release).
