### ISSUE TITLE
Welcome screen

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#312]
**Describe the solution you'd like**
As we don't have time for a complete dashboard solution in this release, we should add a welcome screen. This avoids having duplicate main menus which would confuse users, and we can add meaningful information for users after login (yet to be decided what to write).

To provide a fallback for users who are used to the classic main menu, we should add configuration to get back that menu on demand.

**Comment by umulmrum** [comment]
@pixeljunkie Could you add content for the welcome page? There are two views in chameleon-base/src/CoreBundle/Resources/views/snippets-cms/StaticView/en/cms_welcome.html.twig (and "de" for German) which need some love.

**Comment by umulmrum** [comment]
General note for testing. In this issue we introduced two new features which should also be tested (by technical people):
- Added a StaticViewModule that allows to display static content from Twig templates.
- Added configuration for the home pagedef which is displayed after login and in any place where users can click some "to home" button. It should be tested that this pagedef can be configured and that this configuration takes effect "everywhere".

**Comment by esono-anja** [comment]
From my side only a few orthography and link issues:
1. Besuchen Sie die Github Projektwebsite, um Fragen zu stellen, Funktionsideen einzureichen und Fehler zu melden. => "um zu" requires a comma
2. Welcome to your Chameleon System backend. (not in)
3. If the profile language is English, the links to external websites should link to the English version:
https://www.chameleon-system.de/en/
https://www.esono.de/en/

For further testing see https://github.com/chameleon-system/chameleon-system/issues/312#issuecomment-463643592 the issue has to be passed on to someone else.

**Comment by esono-anja** [comment]
> General note for testing. In this issue we introduced two new features which should also be tested (by technical people):
> 
> * Added a StaticViewModule that allows to display static content from Twig templates.
> * Added configuration for the home pagedef which is displayed after login and in any place where users can click some "to home" button. It should be tested that this pagedef can be configured and that this configuration takes effect "everywhere".

=< still needs testing. 
The rest is alright.
