### ISSUE TITLE
Backend: Change the order of submenu items

### ISSUE THREAD

**Issue by esono-anja** [chameleon-system/chameleon-system#324]
Follow-up ticket from #155 

I would change the order of the submenu points as follows:

=> Produkte & Kategorien
Produkte
Produktkategorien
Produktattribute
Produktmerkmale
Produkttypen
Warengruppen
Variantenset anlegen
Hersteller/Marken
Vorgemerkte Produkte
Umsatzsteuergruppen
Maßeinheiten
Beitragende Personen
Arten der beitragenden Personen
Dokumentart bei Produkten

=> Produktlisten
Listenfilter
Listensortierung
Produktauswahlfilter
Filtertypen

=> Kommunikation
E-Mail-Vorlagen
Newsletter-Abonnenten
Newsletter-Sperrliste
Newsletter-Empfängerlisten
Newsletter-Kampagnen

=> Layout
Seitenvorlagen / Templates
Website Themes
Theme Blöcke
Systemnachrichten / Fehlercodes
Auswahlmöglichkeiten für Variantenset
Anzeige von Variantenwerten
CMS Themes
CMS Textimage

=> Logs
Logs
Bestellexport-Logs
Suchanfragen
IPN-Meldungen
IPN-Weiterleitungen
Log-Channels

**Comment by umulmrum** [comment]
Re-ordered as per your suggestion. Removed the menu items for logs and log channels, as they are no longer used from release 6.3.0 on.
