### ISSUE TITLE
Backend: tableEditor and listManager targets inside a modal overlay should not have target top in forms

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#328]
**Describe the bug**
If you create a new record or enter a record editor inside of an iframe the target for all operations is "top", so we leave the iframe. This leads to an new entry in the breadcrumb/history which allows us to get back to the previews record, but... if we are inside an overlay the overlay will close and we don't have the ability to go back to the previews record.

**Affected version(s)**
6.2

**To Reproduce**
I have no demo shop test case for this in 6.2. Only in project setups with modified backends. :-(
I was 100% that i had a case found in 6.3 demo shop, but i can't find it at the moment. (will add the test case later)

**Expected behavior**
The forms targets should check for the existence of an open modal. If it exists, the form targets should change from "top" to nothing so that list and edit dialogs are opened inside the current iframe.
In addition the pagedefs need to change to the inline ones with suffix "component".

**Desktop (please complete the following information):**
 - All

**Smartphone (please complete the following information):**
 - Al

**Technical details**
The init of this script should be called in table.js and tableEditor.js
The modal in 6.3 changed from jQueryUI to bootstrap, so the fix needs a slightly different check for the existence of the modal.

**Comment by pixeljunkie** [comment]
This is a follow up to #327 which handles the iframe mode.

**Comment by umulmrum** [comment]
@pixeljunkie Could you create a separate issue for 6.3.0 so we can test the fix in both versions (because 6.3.x requires a different solution)?

**Comment by pixeljunkie** [comment]
I would not make an extra effort here, because it is only one line that changes for 6.3.0 PR is ready in a few minutes.

**Comment by umulmrum** [comment]
OK, I thought the change would be significantly different.
