### ISSUE TITLE
Add CoreUI sources

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#332]
**Describe the solution you'd like**
The CoreUI sources should be included to make it easy to change variables.
Also we should add a short manual on how to build the theme.

(we already changed the sidebar width, this change should be included in the sources)

**Comment by pixeljunkie** [comment]
Already tested.

**Comment by UlrichKu** [comment]
Documentation, configuration and dependency (and compiled files) present.
