### ISSUE TITLE
generator tag refers to chameleon page without https

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#337]
**Describe the bug**
In MTPageMetaCoreEndPoint there is a default generator meta tag with the text:
"Chameleon CMS/Shop System - http://www.chameleon-system.de"

**Affected version(s)**
6.2.x

**To Reproduce**
1. Open any page
2. Show html code of page
3. See meta generator tag in head

**Expected behavior**
The link should have "https" as protocol and and refer to the .com domain.

**Technical details**
While changing the text here, we maybe should introduce a protected method which allows us to overwrite/disable the generator. Not everyone wants to show which is the underlying content management system. Or a config parameter?

**Comment by umulmrum** [comment]
I don't think that we need a possibility to hide the generator. On the first glance this looks like a potential security issue, but attackers will always find a way to determine which system the site is based on (in Chameleon one can just call "/cms", and there will always be characteristics in HTML, CSS and JS that make identification trivial).

**Comment by pixeljunkie** [comment]
Changed the meta tag in 6.3
