### ISSUE TITLE
Backend: deleting a navigation point does not work

### ISSUE THREAD

**Issue by esono-anja** [chameleon-system/chameleon-system#338]
Deleting a navigation point is not possible.

![nav_point1](https://user-images.githubusercontent.com/15125103/53505007-5324fa00-3ab3-11e9-97c6-aaf208ceb756.png)
![nav_point](https://user-images.githubusercontent.com/15125103/53505022-55875400-3ab3-11e9-948b-94d6bb16802b.png)

**Comment by umulmrum** [comment]
When testing the fix, please also have a look at moving tree nodes, as this was also broken,
