### ISSUE TITLE
Backend: mouse pointer does not change

### ISSUE THREAD

**Issue by esono-anja** [chameleon-system/chameleon-system#339]
**Describe the bug**
If you want to assign an instance to a spot (loading an instance), the list is opened, but the mouse pointer does not change. So it is not clear that you can pick an instance from the list and load it to the spot.

**Affected version(s)**
6.3

**To Reproduce**
1. Open any page. 
2. Open the right-click menu and load an instance (existing or copy doesn't matter) 
3. A list with all instances is shown.
4. Select an instance by clicking in the line.
=> The instance is loaded, but there is no hint before that an action will be executed by clicking the line.

**Expected behavior**
The mouse pointer changes when you move the mouse over the line.

**Screenshots**
![instanzen](https://user-images.githubusercontent.com/15125103/53505705-b19ea800-3ab4-11e9-8ffb-38d3ca9f4788.png)

**Comment by pixeljunkie** [comment]
There is the CSS class .action that should be added to the rows here.
