### ISSUE TITLE
PageMeta module does not cache if backend session is open

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#340]
**Describe the bug**
If you are logged in to the backend the MTPageMeta module does not cache. This is not only a performance issue, because the module is loaded 3 times in any page doing a lot of work, but trolls you massively if you add cache keys for title or canonical url loading. You will think your cache keys work, but instead you were fooled. 

**Affected version(s)**
6.x

**To Reproduce**
1. Activate prod mode (caching)
2. Login to backend
3. Open a new tab in the same browser
4. Set your debug point in MTPageMeta or any extension in _GetCacheParameters
5. You will never get there, because caching is disabled even it is enabled

**Expected behavior**
Module should always cache

**Technical details**
In MTPageMetaCoreEndPoint::_AllowCache is a check for a backend user session.
A comment says: "if user is logged in to CMS the cache will be disabled to allow output of CMS only content"
I checked the GIT history but i could not find any reason why this was added and it is older than 7 years.
I remember, that in early days we had 2 admin only outputs in this module which added a comment block stating the page ID and a render time.
As far as i know both were removed.
I'm sure we can remove this behavior, but need deeper checks where this did came from and if it has any reason.
@rnuernberg thought, that the module adds the backend related jquery version and other includes for the template engine edit mode, but this is not the case. The module really does only frontend things.

**Comment by pixeljunkie** [comment]
Already tried, what happens if i remove the lines. Looks good in frontend and backend opening the same pages here. Template engine works.
Oh and i found the reason i think! 
In MTPageMetaCoreEndPoint::_GetCustomHeaderData() is the page id output.
I think we don't need this and can remove it. Or if we decide to let it there add the cache key isLoggedIn so this is only added to cache elements for backend users.
But i think nobody even knows that this info exists in the page head. So i would vote for removal.

**Comment by UlrichKu** [comment]
> In MTPageMetaCoreEndPoint::_GetCustomHeaderData() is the page id output.

I remember requesting such a feature (more debug information) as a ticket here - which I can't find at the moment.

**Comment by UlrichKu** [comment]
Tested with 6.3 (locally).
