### ISSUE TITLE
Backend: Deleting records from a list opens the frontend

### ISSUE THREAD

**Issue by esono-anja** [chameleon-system/chameleon-system#343]
**Describe the bug**
Deleting records in the backend does not work. It affects deleting from lists as well as opened records.

**Affected version(s)**
6.3

**To Reproduce**
1. Open a list, such as products.
2. Click on the waste basket icon.
3. The frontend is now opened in the same window with the 404 page.
4. go back to the backend: the record is deleted.

**Expected behavior**
=> Deleting a record should not result in opening the frontend.

**Comment by pixeljunkie** [comment]
is fixed with PR from #344
