### ISSUE TITLE
Backend: deleting an open record does not work

### ISSUE THREAD

**Issue by esono-anja** [chameleon-system/chameleon-system#344]
**Describe the bug**
Deleting an opened record in the backend does not work.

**Affected version(s)**
6.3

**To Reproduce**
1. Open a record, i.e. a product.
2. Click on the red delete button.
3. Nothing happens, the record is not deleted.

**Expected behavior**
The record should be deleted.

**Comment by esono-anja** [comment]
The record is now deleted. However, you will jump to the start screen instead of the list which was opened before.

Steps to reproduce:
1. Open a list, i.g. products.
2. Open a record.
3. Delete it.
4. Now you'll see the home screen instead of the list.

**Comment by pixeljunkie** [comment]
Should work after #354 is merged.

**Comment by esono-anja** [comment]
not fixed yet, have to wait for #354
