### ISSUE TITLE
replace filetype icons

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#347]
**Describe the solution you'd like**
Currently the filetype icons (used in the document manager in the backend as well as for downloadable files in the frontend) are based on 16x16px images, which do not allow responsive rendering.
Additionaly they look very outdated.

**Possible solution (if any)**
Replace the icons with svg icons with a modern look and MIT licensed.
https://github.com/dmhendricks/file-icon-vectors/

**Comment by pixeljunkie** [comment]
The new look:
![selection_212](https://user-images.githubusercontent.com/958920/53717236-d057c280-3e57-11e9-9b58-a917f6fe2178.png)

**Comment by esono-anja** [comment]
Icons look alright in the backend as well as frontend.

But what is this plain icon next to the doc type for?
![doc_icon](https://user-images.githubusercontent.com/15125103/54217453-ee729200-44eb-11e9-8927-f2c579cbdd41.png)

**Comment by pixeljunkie** [comment]
Hmmm this is a bug. I will look into this.

**Comment by pixeljunkie** [comment]
This was an browser cache issue.

**Comment by umulmrum** [comment]
OK, I heard you checked it together - close.
