### ISSUE TITLE
Remove RSA key manager field

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#35]
**Describe the solution you'd like**
In the default database, there is a field "RSA key manager" which references the class TCMSFieldRSAKeyManager. The class was removed some while ago, but the field definition is left. It should be removed (only from the default database dump, not in general - it might be used in existing projects; maybe it makes sense to encourage users to remove the definition manually in these projects).

Also, there are CSS definitions referencing ".rsakeymanagerbox" in tableeditcontainer.css - remove those as well.

**Comment by kzorluoglu** [comment]
MR: https://github.com/chameleon-system/chameleon-resources/pull/1
