### ISSUE TITLE
Backend: select UX - selection is not possible with tab key

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#353]
**Describe the bug**
In native select boxes it is possible to select an option with tab key. This should be possible with select2, too.

**Affected version(s)**
6.3.0

**To Reproduce**
1. Go to any record with select2 enhanced lookup field
2. Click on select2 enhanced field
3. use arrow keys for your selection
4. try tab key to make the selection
5. doesn't work, only ENTER works here

**Expected behavior**
should work like a native select box with tab, too.

**Desktop (please complete the following information):**
 - All

**Technical details**
Looks like we only need to enable: "selectOnClose: true"

**Comment by pixeljunkie** [comment]
https://github.com/chameleon-system/chameleon-system/issues/352

**Comment by esono-anja** [comment]
Doesn't work with tab key yet.

**Comment by umulmrum** [comment]
@esono-anja Could you clear the browser cache and retry? Worked for me.
