### ISSUE TITLE
Backend: list autocomplete removes last element from breadcrumb history

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#354]
**Describe the bug**
The select2 autocomplete in lists uses a popLastURL=1 in the target url which removes the current List from the breadcrumb

**Affected version(s)**
6.3.0

**To Reproduce**
1. Go to any list with enabled select2 autocomplete in searchbox
2. enter existing search term and select any entry
3. The record editor opens
4. the list was removed from the breadcrumb history

**Expected behavior**
List should not removed

**Desktop (please complete the following information):**
 - All

**Smartphone (please complete the following information):**
 - All

**Technical details**
We use the same method here to get the URL as the record switcher in the table editor searchbox. While it is necessary to remove the current record from the breadcrumb if we switch records, it is not if we came from a list.
There needs to be different handling

**Comment by pixeljunkie** [comment]
I think this is the reason why deleting a record ends in the main page instead of the list. The history is broken. https://github.com/chameleon-system/chameleon-system/issues/344

**Comment by esono-anja** [comment]
The behaviour still occurs when copying an item.

1. Copy an item from the product list.
2. Go back to the list and delete the item via the red basket icon.
3. The bradcrumb item "Products" is lost, the home screen appears.

**Comment by pixeljunkie** [comment]
> The behaviour still occurs when copying an item.
> 
> 1. Copy an item from the product list.
> 2. Go back to the list and delete the item via the red basket icon.
> 3. The bradcrumb item "Products" is lost, the home screen appears.

Fixed with other PR.
Was related to: https://github.com/chameleon-system/chameleon-system/issues/356
