### ISSUE TITLE
Select fields do not work after using the browser's "back" function

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#357]
**Describe the bug**
When navigating to a page with select field, e.g. a product record in the backend, then leaving the page, then returning via the browser's "back" function, the select field does not work. It's simply empty and does nothing on click.

**Affected version(s)**
6.3.0-beta3.

**To Reproduce**
1. Go to the view of any product in the backend.
2. Go to any other page.
3. Use the browser's "back" button.
4. Click on the select field - it won't do anything.

**Expected behavior**
The select field is usable as normal.

**Desktop (please complete the following information):**
 - Firefox
 - 65.0.1

**Technical details**
The browser console shows a "too much recursion" error - don't know if related.

**Comment by pixeljunkie** [comment]
The reason ist not select2 but tempusdominus which has a problem if the html is rendered from cache.
https://github.com/tempusdominus/bootstrap-4/issues/39
https://github.com/tempusdominus/bootstrap-4/issues/123

Workaround (tested already, works):
https://github.com/TriForceX/WebsiteBase/issues/13
