### ISSUE TITLE
deprecate api.pagedef

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#360]
**Describe the bug**
This pagedef references a module that was removed from the core years ago. So the file is an orphan.

**Affected version(s)**
6.3.x

**To Reproduce**
1. Call: /cms?pagedef=api
2. See error of missing module

**Expected behavior**
should not exist

**Technical details**
The MTChameleonApi module was once created for single-sign-on purpose for a project, but was never part of the core.

**Comment by UlrichKu** [comment]
@pixeljunkie The described "error" (To reproduce) however will be the same also with this ticket / PR?

**Comment by pixeljunkie** [comment]
> @pixeljunkie The described "error" (To reproduce) however will be the same also with this ticket / PR?

The PR does not fix anything. It marks the pagedef as deprecated, which may be removed in 7.0.
