### ISSUE TITLE
Reduced side menu: entries not reachable

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#365]
**Describe the bug**
With a reduced side menu:
- Submenus on the lower display border are not fully shown - for smaller monitors this will already happen with "Products & categories"
- The list is not scrollable - so on a smaller display also the primary menu entries might not be shown and are unreachable

**Affected version(s)**
6.3.0

**Comment by bestform** [comment]
The current plan is to remove the reduced sidebar so this is no longer an issue.
