### ISSUE TITLE
Backend: parent key field does not output record name anymore in non admin mode

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#369]
**Describe the bug**
The field type TCMSFieldLookupParentID got some styling changes with 6.3.
Unfortunately the output of the parent record name got lost here for non admin mode.

**Affected version(s)**
6.3.0

**To Reproduce**
1. Go to any record with a field of type "properties". (not products with variants)
2. Got to one property record
3. See parent lookup field (normally the first field)
4. See no record name; only the button is visible

**Expected behavior**
See name of parent record

**Technical details**
Add technical context about the problem here.

**Comment by umulmrum** [comment]
Only affects 6.3.x

**Comment by esono-anja** [comment]
Example for another property field: domains (in portals / websites)
