### ISSUE TITLE
Changelog: Line breaks in WYSIWYG editor

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#379]
**Describe the bug**
When using the changelog feature for a table with at least one WYSIWYG editor, changes will be recorded for these fields even if there are none. This happens when users with different operating systems save the field in turns, as the line endings differ.

**Affected version(s)**
All versions.

**To Reproduce**
1. Go to e.g. the product table editor.
2. Assure that changelog is enabled.
3. Click "Save" without changing anything.
4. Changes will be recorded anyway. For product variants that inherit the WYSYWIG field from the main product, a change will also be recorded.
5. If saved again without changes, no further changelog is recorded.

**Expected behavior**
Changelog is only saved if the user did actually change contents.

**Comment by UlrichKu** [comment]
Configuring ckeditor doesn't seem to help.
At least not with protectedSource: [ "/\r\n/g" ]

**Comment by bestform** [comment]
I consider this solved when #653 is fixed, so I will close this as duplicate.
