### ISSUE TITLE
Regression: Table editor sorting not working as intended as of 6.2.0

### ISSUE THREAD

**Issue by proligde** [chameleon-system/chameleon-system#38]
**Describe the bug**
Sorting of Table columns does not work anymore

**Affected version(s)**
6.2.0, 6.2.1 (6.1.x works as intended - I've just verified that)

**To Reproduce**
1. LogIn to BackEnd
2. Click on "Artikel"
3. Click on "Name" multiple times

**Expected behavior**
Clicking on different column name titles should have the effect of:

1. Changing between ascending, descending an no sorting
2. Cycling through primary, secondary and tertiary sort order 

Instead now the table editor is only switching the column currently used for sorting. So there is only a primary sorting left, and I can't choose between ascending and descending anymore.

**Comment by proligde** [comment]
Before fixing this issue we should take a look at the feature completeness of the bulk edit feature as it might render this functionality obsolete anyway.

**Comment by umulmrum** [comment]
Workaround: Use the chameleon-base branch from this PR: https://github.com/chameleon-system/chameleon-base/pull/21 (or chameleon-base 6.2.x after merge, or chameleon-base 6.2.2 after release).
