### ISSUE TITLE
Wrong blue as select field highlight color

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#389]
**Current**
Any dropdown (select2) in the backend has blue as a highlight color. But this blue is different than the one in the theme.

For example the "active" selection in a product list.

**Comment by pixeljunkie** [comment]
If i see this right. The color is operating system or browser dependent, but it is possible to overwrite it.

**Comment by pixeljunkie** [comment]
I was wrong, select2 had a custom highlight color defined. Is now overwritten by backend theme styling.
