### ISSUE TITLE
Broken redirect in Url-Alias if source is full url (including domain)

### ISSUE THREAD

**Issue by pSpeck** [chameleon-system/chameleon-system#39]
If source url cotains full url (including domain) for example http://domain/source the url handler cant find a match in the url alias table for source http://domain/source because it adds an additional slash between the domain and the url path -> http://domain//source

Version 6.2

1. add url alias with full url
2. call this url 
3. Debug class TCMSSmartURLHandler_URLAlias->getUrlAliasList() build wrong url

**Comment by esono-anja** [comment]
Additional Slash is not added anymore. 
However, the alias does not work, the page is not redirected.
My test example:
Source: https://shop-demo-6-2-x.stage.esono.net/Angebote/
Target: https://shop-demo-6-2-x.stage.esono.net/Produkte/Gutscheine/
There will be no forwarding.

**Comment by umulmrum** [comment]
@esono-anja The URL alias functionality only works for invalid URLs - could you do a test with URLs that have no other meaning in the system?
