### ISSUE TITLE
White page after saving product stock

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#395]
**Describe the bug**
In the table editor view of a product, when saving stock by clicking the "Save" button within the stock window [edit: Also on the regular save button, which is why I increase priority], a white page is displayed in that window. This is a bit strange, as it isn't reliably reproducible and also shows different behavior in different Chameleon versions.
In 7.0.0 (current testing state):
- It happens e.g. for "Ocean Jewelry Set (Necklace & Bracelet) - 90 cm, 19 cm" (the first product in the demo shop when showing the product list).
- It does not happen for "Chameleon on the finger" (the first product in the demo shop when restricting to main products only).
- It doesn't happen every time, but I couldn't find a scheme yet.

In 6.2.8:
- It happens for both of these products, but redirects to the product list instead of displaying a white page. As I can use the browser's forward button, this seems to just go back in browser history.

The stock value is saved though in all cases.

**Affected version(s)**
6.2+

**To Reproduce**
See above.

**Expected behavior**
The refreshed stock value should be displayed without any page switches.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Firefox 65.0.1

**Comment by UlrichKu** [comment]
Fixed with https://github.com/chameleon-system/chameleon-base/pull/319 and a cherry-pick for 6.2.x.
