### ISSUE TITLE
Product filters do not work for "art prints" category

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#398]
**Describe the bug**
When choosing any product filters on the "art prints" product list, the result is empty. Other categories seem to work.

**Affected version(s)**
7.1.x (fixed in...)

**To Reproduce**
1. Go to the "art prints" category.
2. Click on any filter.
3. See empty result.

**Expected behavior**
Filters should be a bit lazier :-)

**Comment by esono-anja** [comment]
The page /Products/Art Prints/Chamaeleon Prints/ shows the price filter set to 10-30€, although there are products with 39€.
The correct range should be displayed (i.e. 10-40€).
