### ISSUE TITLE
Edit-on-click fields are not validated on save

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#404]
**Describe the bug**
Fields that are configured as edit-on-click fields can be saved no matter what. There are no validation errors if invalid values are entered.

**Affected version(s)**
All versions.

**To Reproduce**
1. Configure any table field so that it is required.
2. Open a suitable record and try to save it with this field left empty.
3. This will prompt an error.
4. Configure this field as edit-on-click now.
5. Open the record again and edit the value.
6. Save this field with an empty value.
7. The value will be saved.

**Expected behavior**
The same validation errors that occur for the default case should also occur in the edit-on-click window.

Setting high priority as this can cause corrupt data. Might be switched to normal priority if you decide that this feature is used too rarely to be of that much concern.

**Comment by UlrichKu** [comment]
The actual location where this is (not) checked:
\TCMSTableEditorEndPoint::SaveField()
In contrast to Save() it has no check with DataIsValid(). However the contract of this method also does not consider this case (the return value is always a TCMSstdclass).

This is the case for as long as this method exists (> 5 years).
