### ISSUE TITLE
Problems in mapper config: faulty handling; error message not helpful

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#415]
**Describe the bug**
- Change the mapper configuration for a module - ie delete one.
- Open a page where that module with that view name is (still) used.
-> There will be an exception about an illegal foreach() but no hint where exactly this happened.

For example the article list module has a view "fullWithMainHeadline" and the page "Angebote" (offerings) uses that.

**Affected version(s)**
\>= 6.1 (fixed for 7.1+)

**Expected behavior**
1. The error/exception message should be more helpful (with the exact location) - this is proably a more general problem.
2. In this case the error could be avoided if desired.

**Technical details**
\TModelBase::__invoke(): The return value of `$viewMapperConfig->getMappersForConfig($sViewName);` can be null but this is not considered.

**Comment by pixeljunkie** [comment]
I stumbled over this problem a lot the last weeks, with wrong instance ids in the database during theme installations, so now I will fix it. There are 2 problems. The missing transfer of the exception details to the ModuleExecutionFailedException and the viewMapperconfig which does not check for the return type of the mapper chain loading.

**Comment by pixeljunkie** [comment]
The exception now includes the filename and line.
```An exception has been thrown during the rendering of a template ("Error in module execution: Notice: Trying to access array offset on value of type bool in file: .../vendor/chameleon-system/chameleon-base/src/CoreBundle/private/library/classes/dbobjects/TCMSTPLModule.class.php on line: 213")```

**Comment by UlrichKu** [comment]
Fixing the error location noted in *Technical details* is not done here. The error remains the same.

(another location was changed here)
