### ISSUE TITLE
Wrong basket item discount calculation for multiple discounts

### ISSUE THREAD

**Issue by pSpeck** [chameleon-system/chameleon-system#421]
**Describe the bug**
If basket contains more than one discount (percentage), the second discount was calculated with the discounted price from the first discount. For Example if you use two 10% discounts the discounted value for both should be the same. 

This you can see in the field oActingShopDiscountList->items->dRealValueUsed.

The basket article list  contains a function (correctBasketItemDiscountPrices) which corrects some of the basket item values (dPriceAfterDiscount,dPriceTotalAfterDiscount) but not all (dPriceAfterDiscountWithoutVouchers,dPriceTotalAfterDiscountWithoutVouchers).

**Affected version(s)**
6.2

**To Reproduce**
1. Create two 10% discounts for all products (cms)
2. add product To basket
3. see wrong values in oActingShopDiscountList->items->dRealValueUsed and dPriceAfterDiscountWithoutVouchers

**Expected behavior**
The second discount was calcualtet with the before discounted product price. this shoul always be done with the originally price.

**Technical details**
The discount calculation was made in  TShopBasketArticleCore->ApplyDiscount()

**Comment by UlrichKu** [comment]
Will be masked/fixed currently by the behavior of correctBasketItemDiscountPrices().

(Thus moved to the next version.)
