### ISSUE TITLE
Backend: table list cells have nowrap so tables are too wide

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#422]
**Describe the bug**
Table cells are set to white-space: nowrap and i don't see any case why.

**Affected version(s)**
6.3.x

**To Reproduce**
1. Go to any table with a lot of columns like "products".
2. Resize the browser window to below 1280px or something smaller.
3. The table begins to scroll horizontal.
4. remove 

**Expected behavior**
Cells should not force their width by content length.

**Desktop (please complete the following information):**
 - All

**Technical details**
remove: .TCMSListManagerFullGroupTable white-space: nowrap in table.css

**Comment by UlrichKu** [comment]
Was introduced with #99 
( https://github.com/chameleon-system/chameleon-base/pull/266)
