### ISSUE TITLE
Backend: shorten GUIDs in lists

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#423]
**Describe the solution you'd like**
Currently the very long GUIDs are using a lot of space in lists, but in most cases you don't need to know the record ID at all. You may need to search for it, so that's why the id is part of the default columns. So i propose to shorten the IDs if they are GUIDs (there may be some older records with INTs that don`t need to be shorten). The full ID is shown in the record header and could be the title attribute.

**Possible solution (if any)**
I would add a callback method for IDs adding an icon and cut the IDs at the first "-".
The icon should have the full ID as title attribute, so if you really have 2 records which start with the same hash you can differentiate them already in the list without the need to go to record details.

![Selection_341](https://user-images.githubusercontent.com/958920/57127479-db17d080-6d90-11e9-83be-5d7c31e7778d.png)

**Comment by pixeljunkie** [comment]
The icon: https://fontawesome.com/icons/fingerprint?style=solid

**Comment by pixeljunkie** [comment]
Maybe shorten using text-overflow? https://developer.mozilla.org/de/docs/Web/CSS/text-overflow

**Comment by pixeljunkie** [comment]
Found out, there is no general way to identify the ID cells/columns, so simply adding some CSS does not the trick. Even if we know, that the column data is the ID field, the problem is, that there are some fields, that use the id to load the record and show something completely different (lock state for example). So not every field that is using ID is the ID at all.

A callback method is needed and we need to set the callback manually in custom column settings. This is possible with a simple update, but we than should add either a documentation what callbacks are available or add a field that allows us to select a callback (will add another issue).

**Comment by UlrichKu** [comment]
(Looks also odd with #422 - if that is merged.)

**Comment by pixeljunkie** [comment]
I already worked on this in a branch and it looks good. But there is an update missing yet, to change custom configured ID columns. Follows soon.

**Comment by pixeljunkie** [comment]
Needs: #431

**Comment by pixeljunkie** [comment]
Found out that #431 is not necessary.
Found a way to prevent the need to update all manual configured ID columns. They are handled globally. But if you want to overwrite the method this has precedence of course.
