### ISSUE TITLE
Not possible to send emails from cronjobs

### ISSUE THREAD

**Issue by fabianbarth-esono** [chameleon-system/chameleon-system#425]
Cronjobs using an email profile to send emails fail on sending the email with an exception: "In ChameleonSystem\ViewRendererBundle\Twig\Loader\ChameleonTwigLoader::findTemplate(), you must accept a second argument that when set to "false" returns "false" instead of throwing an exception. Not supporting this argument is deprecated since version 1.27."

**Affected version(s)**
6.2

**To Reproduce**

1. Add a cronjob that uses an email profile to send an email.
2. Execute the cronjob from backend.
3. See error

**Expected behavior**
E-Mail should be send.

**Technical details**
The problem seems to be findTemplate() in ChameleonTwigLoader. The method has already been updated in Chameleon 6.3. 
For 6.2, my guess would be that the problem was introduced with a new Twig version. In https://github.com/chameleon-system/chameleon-base/commit/2deb583e840ea299a0a29381bb32e673782a9f3d we cross the version mentioned in the exception message.

**Comment by UlrichKu** [comment]
This didn't / doesn't change in recent versions. And it works in prod environment.

The real reason / problem here is that message parts are tried to be processed as twig templates (files) which fails.

I entered a follow-up issue #429 for this.

**Comment by fabianbarth-esono** [comment]
> This didn't / doesn't change in recent versions. And it works in prod environment.

Additional info: The behavior did change in dev-environment when Twig-Version was updated by composer.  So it will fail in dev-mode, but doesn't need to be hotfixed.
