### ISSUE TITLE
The twig method cmsthumb() should not enlarge images. 

### ISSUE THREAD

**Issue by ckleis** [chameleon-system/chameleon-system#434]
**Describe the bug**
An image that is actually smaller than specified in the twig method cmsthumb(maxwidth,...) method must not be enlarged, it should be provided in its actual size.

**Affected version(s)**
6.2.x

**To Reproduce**
1. Take a small image within the media manager
2. Use the twig method cmsthumb(maxwidth, ...) and try to enlarge this image
3. The method produces an enlarged image, but it should produce a thumb image in the original image size.
4. If you use the php method GetThumbnail() instead, it works correctly.

**Comment by UlrichKu** [comment]
Problem does not occur if both maximum sizes are given: cmsthumb(maxwidth, maxheight)
