### ISSUE TITLE
Breadcrumb for products: link/page does not exist

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#439]
**Describe the bug**
In the demo shop select an article and on the article detail page click on the manufacturer (top right next to the price).
On that page click in the breadcrumb (top left) on "products".
-> A 404 page is shown.

**Affected version(s)**
\>= 6.1

**Expected**

The expected behavior here is not clear: according to the URL there could be a path like "manufacturers > products > manufacturer name". However the "products" alone still has not meaning here.
Maybe show it like "manufacturers > prodcuts of manufacturer name".

**Comment by UlrichKu** [comment]
#440 would probably be useful here.

**Comment by esono-anja** [comment]
Not fixed yet in 6.1. The rest of the version are ok.
