### ISSUE TITLE
Mail transformation service subject prefix is applied to all emails

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#44]
**Describe the bug**
The mail transformation service subject prefix is applied to all emails.

**Affected version(s)**
\>= 6.1
More obvious with 6.2

**To Reproduce**
* Modify the parameters.yml to contain an non-empty parameter value for _chameleon_system_core.mail_target_transformation_service.subject_prefix_
* Make sure the parameter _chameleon_system_core.mail_target_transformation_service.enabled_ is false
* Send any mail with the system (ie a contact form request)
* The resulting mail will have the above prefix in the subject

**Expected behavior**
The parameter _chameleon_system_core.mail_target_transformation_service.enabled_ should be used also for the subject prefix.

**Technical details**
The relevant line can be found here: chameleon-system/chameleon-base/src/CoreBundle/private/library/classes/TCMSMail.class.php:214

This can be more obvious / occur first after a migration from 6.1 to 6.2:
* If the parameters.yml is not adapted (or wrongly) the old config block there (under _chameleon_system_core_) will not be used anymore and the default project config is used instead - which has a "[TEST]" as default value.

**Comment by umulmrum** [comment]
I built a fix, but also improved how the service is enabled/disabled. This led to deprecations, so the fix targets 6.3 - see linked PR.
