### ISSUE TITLE
Backend: color picker shows "change warning"

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#449]
**Describe the bug**
Any dataset in the backend that shows a color picker (ie "Warning" from "System message types") will show the browser dialog when trying to leave the page: "Changes you made may not be saved."
Although no change was done.

**Affected version(s)**
\>= 6.3

**Technical details**

Look at initInputChangeObservation for a starting point: vendor/chameleon-system/chameleon-base/src/CoreBundle/Resources/public/javascript/tableEditor.js:866

**Comment by UlrichKu** [comment]
Probably solved with #459

**Comment by esono-anja** [comment]
The bug still occurs in 6.3.

**Comment by UlrichKu** [comment]
> The bug still occurs in 6.3.

Ignored for the moment.
(Issue is not so severe and it works in other versions - with the same code.)
