### ISSUE TITLE
Missing view mapper: fatal exception

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#456]
**Problem**

During development when switching between branches it can easily happen that some part needed for rendering is missing - because the current local database does not match that branch.

(Restoring appropriate database states is often not really an option as this could take rather long.)

For example for a newly added mapper something like this would be shown in another branch:

An exception has been thrown during the rendering of a template ("Error in module execution: Tried to instantiate mapper "mapper_name", but neither a service with this ID nor a class with this name was found.").

The whole page / system is then not usable (fixable).

**Describe the solution you'd like**

For example for missing view files the consequences are much less drastic: Only an inline error message (something like "View missing: view_name") is shown.

This could also be done for missing mappers (and modules and ...?):
- Show an inline error
- Log a warning/error - which would then be visible in the debug toolbar.

**Comment by UlrichKu** [comment]
For modules the (final) location is: \TModuleLoader::CreateModuleInstance()

**Comment by UlrichKu** [comment]
With #470 the consequences for missing twig views might now be more dramatic.

**Comment by bestform** [comment]
The problems you get when switching to a version not represented by the database are manyfold and a much bigger problem than that. 
Moreover, the solution in this case would be to either switch back and fix it there, or to just use the backend. This should still work. If you think, this is a major issue, feel free to reopen an issue explaining why this is severe and unfixable - which it may be.

**Comment by UlrichKu** [comment]
It is even more important in live mode (error log instead of crash) when it might "just still be missing".

And it is one step forward and there aren't so many of this type.

**Comment by bestform** [comment]
I cannot see how it would be acceptable to have a running live version with missing mappers. This state clearly indicates that something is severly wrong. How could a mapper "just still be missing" in a deployed live release? This possibility is the reason why we closed the issue in the first place. 
We do not want to ignore such inconsistencies. Nobody will see this log message and a live version with a wrong database version could be running for a long time without anyone noticing. This could lead to hard to timpossible to debug errors and even have security implications.

**Comment by rnuernberg** [comment]
@bestform This may be an issue during upgrade. An upgrade process updates the database before the code of the running live version is updated. If the upgrade removes a mapper from the database, then the running live system will crash. The only solution currently is downtime - which we should avoid as much as possible.


In my eyes, making the production mode much more robust to errors is generally welcome. Whenever possible, we should reduce the effect of an error in product as much as possible.

**Comment by bestform** [comment]
After thoughtful discussion we will close this issue. If you really want to run the page in dev mode with a db that does not correspond to the current branch and absolutely need the page to be rendered instead of looking at an exception, either run it in prod mode temporarily or hack a NullMapper into the MapperLoader (see closed PR)
