### ISSUE TITLE
Shop: Navigation shows empty sub-categories

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#457]
**Describe the bug**
Since Update 6.2.5? the shop main navigation and sub navigation shows ALL categories, even empty/disabled categories.

With shop setting "Show empty categories" set to false.

**Affected version(s)**
6.2.5+

**To Reproduce**
1. Add Category in backend without adding products to it or find an empty category
2. Open any page
3. See main navigation or sub navigation on category pages
4. See that the empty category is listed

**Expected behavior**
Empty categories should not show up

**Technical details**
TShopCategory has a method AllowDisplayInShop
In my test case the method returns true if a category is empty and has no target page.

**Comment by pixeljunkie** [comment]
Maybe it has something to do with this: https://github.com/chameleon-system/chameleon-shop/commit/1e8303f40f1849b6bf727d549b35ee5e602bc90c

**Comment by pixeljunkie** [comment]
Looks like the reason is #195

**Comment by pixeljunkie** [comment]
My findings: It is a problem with 2 components... 
1. TShopCategory returns true, even if the category is disabled at all, if the getTargetPage method returns no page... i really don't know what the reason for this was?
Wen need an early return any time the value switches to false. Other checks following are not needed then. Why should i check the access rights, if the category is disabled and not shown anyway?

`public function AllowDisplayInShop()
    {
        $bShowCat = false;

        $oShop = TdbShop::GetInstance();
        if (!is_null($oShop) && !$oShop->fieldShowEmptyCategories) {
            $bShowCat = ($this->GetNumberOfArticlesInCategory(true) > 0);
        } else {
            $bShowCat = true;
        }

        if (false == $this->fieldActive || false == $this->fieldTreeActive) {
            $bShowCat = false;
        }

        $targetPage = $this->getTargetPage();
        if (null === $targetPage || false === $targetPage) {
            return true;
        }
        // show only if the user has access to the category target page
        if (false === $targetPage->AllowAccessByCurrentUser()) {
            return false;
        }

        return $bShowCat;
    }`

2. I think the changed code in TShopCategory::getTargetPage does not work.

$defaultSystemPage has a field with the tree node of a page. NOT the page id!
But this tries to load the page using this id.

`$pageService = self::getPageService();
$defaultPage = $pageService->getById($defaultSystemPage->id);`

This looks very wrong to me and needs to be fixed, too.

**Comment by pixeljunkie** [comment]
Hotfix, that works in TShopCategory::AllowDisplayInShop():

`$oShop = TdbShop::GetInstance();
        if (!is_null($oShop) && !$oShop->fieldShowEmptyCategories) {
            $bShowCat = ($this->GetNumberOfArticlesInCategory(true) > 0);

            if (false === $bShowCat) {
                return false;
            }
        } else {
            $bShowCat = true;
        }

        if (false === $this->fieldActive || false === $this->fieldTreeActive) {
            return false;
        }`

**Comment by esono-anja** [comment]
Showing and hiding empty categories now works, but only if the page was not cached.

**Comment by UlrichKu** [comment]
> Showing and hiding empty categories now works, but only if the page was not cached.

That is "ok" for the moment. The navigation cache should not (have to) watch for actions in the article table.

I've added a followup issue #463 for this.
