### ISSUE TITLE
Regression: Copied instances don't copy connected table objects anymore

### ISSUE THREAD

**Issue by proligde** [chameleon-system/chameleon-system#47]
**Describe the bug**
When an existing module instance is copied within the page's template editor and this instance contains tables containing records - these records are missing after copying.

**Affected version(s)**
6.2.0, 6.2.1

**To Reproduce**
1. Go to a page with at least one empty module instance slot
2. Select "Functions"->"Load"->"Load (as a new instance)"
3. Select an existing module that itself has at least one table containing entries
4. Enter the copied instance

**Expected behavior**
The copied instance is in fact copied - recursively containing all connected entries. This was the case in all versions until 6.2

**Comment by umulmrum** [comment]
For the record: We traced the issue back to some field for which a translation field was expected but which did not exist (although the field was marked translatable). This was a bit too unexpected for the copy process.

So this is not an issue per se - the copy process works as intended. We need to find out why the column disappeared (it didn't disappear on the staging system which underwent the same deployment procedure). A combination of InnoDB conversion and a specific moon phase is by now the best guess.
