### ISSUE TITLE
List search field broken

### ISSUE THREAD

**Issue by rnuernberg** [chameleon-system/chameleon-system#476]
**Describe the bug**
If I go into the list of customers and want to search for a customer, then the search will
a) add the first letter of my typed search to the search field while I type - but not the other letters. If I type very quickly, then more letters will be copied.
b) It will search correctly when I press enter - unless I type an E-Mail address that exists. In that case, the search will emptied and no search is executed.

**Affected version(s)**
7.0

**To Reproduce**
see above

**Screenshots**

![2019-08-14-001](https://user-images.githubusercontent.com/1104497/62999986-5b5dcf80-be70-11e9-9e01-e71c897cf6a8.png)

![2019-08-14-002](https://user-images.githubusercontent.com/1104497/63000257-01a9d500-be71-11e9-8771-2e7a1a4eb346.png)

![2019-08-14-003](https://user-images.githubusercontent.com/1104497/63000287-11c1b480-be71-11e9-8cbf-a2e8a13b6162.png)

**Comment by UlrichKu** [comment]
Similar problem report see #378

**Comment by UlrichKu** [comment]
Noticed some things while testing (maybe the warrant new tickets):

- There is the same select2 field(s) on entry pages - but here not table.js but tableEditor.js is included: This leads to an old ill effect: Typing something and return will not start a search but simply empty the field. Even if there only is one proposal entry (highlighted) Return will not open it. Typing something will not copy it to the dropdown field. So closing the text field (click somewhere else) will loose the entered text.
- On table pages typed text will not be copied to the select field reliably: it now alternates between only one of a few characters being copied (as before) and shortly flashing the full correct content. The same goes for shortening an existing searched text. Hence the behavior described here (a) still appears.
- Searching for the exact same text (click field, press return) will do nothing. Maybe this is as desired in code (no change detected) but it is surprising for the user.

**Comment by gerritious** [comment]
> Noticed some things while testing (maybe they warrant new tickets):
> 
> * There is the same select2 field(s) on entry pages - but here not table.js but tableEditor.js is included: This leads to an old ill effect: Typing something and return will not start a search but simply empty the field. Even if there only is one proposal entry (highlighted) Return will not open it. Typing something will not copy it to the dropdown field. So closing the text field (click somewhere else) will loose the entered text.

This behaviour is indeed confusing as it is different from that on the list page.
I think a new ticket might be best. In my opinion the new ticket should include the task to check whether these two implemetations of select2 can be unified.

> * On table pages typed text will not be copied to the select field reliably: it now alternates between only one or a few characters being copied (as before) and shortly flashing the full correct content. The same goes for shortening an existing searched text. Hence the behavior described here (a) still appears.

I can confirm this behaviour. It does not occur with a  `keyup` event (instead of a `keypress` event).
I'll fix this and open another PR.

> * Searching for the exact same text (click field, press return) will do nothing. Maybe this is as desired in code (no change detected) but it is surprising for the user.

In the current implementation there is no code to prevent a second search with an unchanged search term. So this seems to a standard behaviour of select2 though I cannot find anything that about it in the documentation.

**Comment by UlrichKu** [comment]
Currently looks good for this field in tables.

Entered #484 as a followup.
