### ISSUE TITLE
Pagepreview in CMS not working in multiportal  environment

### ISSUE THREAD

**Issue by pSpeck** [chameleon-system/chameleon-system#477]
**Describe the bug**
If you have more than one portal configured in cms and you want to preview a page from the portal url you are not logged in in cms you get an empty page. With the error: 

"Load denied by X-Frame-Options: ... does not permit cross-origin framing."

**Affected version(s)**
6.2

**To Reproduce**
1. Log into CMS 
2. Go to a page within a portal with other domain
3. click page preview

**Expected behavior**
Page preview shoul show correct page from other portal

**Technical details**
in preview mode we should allow all possible domains configured in cms.

**Comment by UlrichKu** [comment]
No second portal is necessary. It is sufficient to add another (non-primary) domain with another address and access the backend with that address.
