### ISSUE TITLE
Search field on entry pages: no search possible

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#484]
Followup/sibbling of #476

**Describe the bug**
There is the same select2 field(s) on entry pages which have an old ill effect: Typing something and return will not start a search but simply empty the field. Even if there only is one proposal entry (highlighted) Return will not open it. Typing something will not copy it to the dropdown field. So closing the text field (click somewhere else) will loose the entered text.

**Affected version(s)**
\>= 6.3

**Technical details**
There is the same select2 field(s) on entry pages - but here not table.js but tableEditor.js is included:

**Comment by gerritious** [comment]
I think it's reasonable that I look into this issue. I've assigned the ticket to me.

**Comment by UlrichKu** [comment]
Should be solved with #488 .
(It should anyway be no "search" there.)
