### ISSUE TITLE
Backend search: Does not find when searching with space

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#489]
**Describe the bug**
(Changed/reworked the search functionality with #488)

In the backend in a table search field: Type a search for an entry name with space (i. e. "Color! " in the Products table).
There will be autocomplete proposals and search results for "Color!" but not for "Color! ".

**Affected version(s)**
At least since 6.2 probably longer.

**Technical details**
Problem seems to be the behavior of the LIKE operator of mysql.
(For example in \MTTableManager::getAutocompleteListQuery())

**Comment by bestform** [comment]
This bug is no longer present.
