### ISSUE TITLE
MediaManagerBundle: duplicate properties output

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#5]
**Describe the bug**
There is a special field type that outputs media properties like width, height, size a download button etc. in a compact way.
But all this is now part of the media manager detail dialog itself, so this information is a duplicate and obsolete.

**Affected version(s)**
6.2

**To Reproduce**
1. open new media manager from CMS top navigation
2. click on edit icon of an image
3. switch to "properties/Eigenschaften" tab
4. duplicate information is shown

**Expected behavior**
Should not show up. field should be hidden.

**Screenshots**
![screenshot-2018 07 30-14-53-22](https://user-images.githubusercontent.com/958920/43398606-df006160-9408-11e8-8356-12bc1bcff728.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser FF, Chrome

**Technical details**
Simple update which sets the field hidden in mediaManager bundle fixes this.

**Comment by esono-anja** [comment]
There's still redundant information in the properties: Changed / Last changed on 

![mm_duplicate](https://user-images.githubusercontent.com/15125103/44152494-f98c6dfe-a0a5-11e8-9b6e-a68ab8ff6dac.png)

**Comment by pixeljunkie** [comment]
You are right.
But unfortunately to remove the display of this field is not possible without a database update, which would remove the possibility to go back to the old media manager without manual changes for this field. So i would suggest creating a separate issue for this to change the display setting of the field in the next major release with dropping the old media manager.

**Comment by umulmrum** [comment]
I added a cleanup issue for Chameleon 7.0: https://github.com/chameleon-system/chameleon-system/issues/25
