### ISSUE TITLE
Backend: Directly copyable id

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#507]
**Affected versions**
6.3+

**Describe the solution you'd like**
The id (uuid) shown for every database entry in the backend should be copyable to the clipboard with a simple click.

**Comment by UlrichKu** [comment]
And maybe also in the list view.

**Comment by esono-anja** [comment]
It works except for pictures (media) and documents. The ID copy function is missing here.

**Comment by esono-anja** [comment]
Would be nice if the ID could be copied from the list view of a media entry, too. Right now you have to open the entry to copy.
![list](https://user-images.githubusercontent.com/15125103/70517112-5d8f1c80-1b38-11ea-8ff9-1b015c62fa16.png)
