### ISSUE TITLE
Creating new navigation tree nodes creates additional empty nodes

### ISSUE THREAD

**Issue by rnuernberg** [chameleon-system/chameleon-system#513]
**Describe the bug**
When creating new navigation nodes additional empty nodes will be created.

**Affected version(s)**
7.x

**To Reproduce**
1. Click on "Navigation"
2. Right-Click on the primary portal node
3. Click "new"
4. Enter a name (example "test") and click save
5. right click on the new node
6. click "new"
7. enter a name (example subpage 1) and select a page template (field "pages / layouts")
8. click save
9. right click again on the test node created in step 4
10. create another subnode again selecting a page template
11. once the subnode is created close the navigation editor and open it again

**Expected behavior**
There should be three nodes (test, subpage 1 and subpage 2)
Instead, there is at least one additional unnamed node

**Technical details**
When reproducing this I had the db logger active to record the changes. The unnamed entries also appear in db change log.

Since the Navigation is currently being upgraded (#107) it may make sense to look at this bug in that new context.

**Comment by ckleis** [comment]
Unfortunately I could not reproduce the error with these steps. Some particularity seems to be missing that causes the error.

**Comment by rnuernberg** [comment]
It appears that the problem occurs when working with a tree with invalid lft/rgt values. The Project I was working in I copied an existing portal - including the tree. I then removed quite a few of the nodes from the Tree.

**Comment by rnuernberg** [comment]
I am suspecting that the multi portal setup causes problems with the navigation. I reinitialized the tree. I was then able to generate two new entries using a page template restricted to my portal. After that, I had invalid lft/rgt values in my newly created node again - which in turn would provide an invalid portal id.

**Comment by UlrichKu** [comment]
(current task: check if this still is problem)

**Comment by UlrichKu** [comment]
Cannot reproduce this in the demo shop (6.3).
