### ISSUE TITLE
Deleting a page via backend will throw a 500 error

### ISSUE THREAD

**Issue by rnuernberg** [chameleon-system/chameleon-system#514]
**Describe the bug**
Deleting a Page will throw the error "Call to a member function GetPortal() on null"

**Affected version(s)**
The error occurred in 7.0 - other versions may be affected

(fixed for 6.3+)

**To Reproduce**
1. Open the list of pages
2. Click on the Edit symbol for the page
3. Click Delete
4. Confirm delete action
6. See Error

**Expected behavior**

**Screenshots**

![2019-12-01-001](https://user-images.githubusercontent.com/1104497/69912579-8114e180-142b-11ea-83b6-d0baf4c251b9.png)

**Technical details**
It looks like chameleon attempts to get the portal from the just deleted page in CMSTemplateEngine.class.php line 122

Note that this would not always happen - but almost always.

my be related to #434 or #344

**Comment by UlrichKu** [comment]
Is now fixed with: Removing entries from the breadcrumb (= history) that have to do with this entry.
