### ISSUE TITLE
Wrong labels when editing spots of a static module

### ISSUE THREAD

**Issue by rnuernberg** [chameleon-system/chameleon-system#515]
**Describe the bug**
The labels show when editing the parameters of a module are wrong

**Affected version(s)**
Testet in 7.x, fixed for 7.1

**To Reproduce**
1. Open a page template
2. Open the list of modules -> These are shown with the label "Name" which is also wrong
![2019-12-01-003](https://user-images.githubusercontent.com/1104497/69915021-be3c9c00-144a-11ea-9583-5803340f859e.png)

3. open detail page of any module
4. open list of parameters
5. add a parameter

We expect to see labels "belongs to", "name" and "value". Instead we see "value", "belongs to cms page template spot" and "belongs to cms page template"

![2019-12-01-004](https://user-images.githubusercontent.com/1104497/69915075-415df200-144b-11ea-9cbb-e11d44f95dba.png)

**Comment by kzorluoglu** [comment]
After the check this place with **German** Language, i think, translates must be like this:

 Actual | Correct Translate
---------- | ------------------
Name (from 1. Picture) | Spots
Value  (from 2. Picture) | belongs to cms page template spot
belongs to cms page template spot (from 2. Picture) | Name
belongs to cms page template (from 2. Picture) | Value

**Comment by esono-anja** [comment]
correct in 7.1, not (yet) in 7.0
=> but maybe it is not supposed to be fixed in 7.0? see issue description
**_Affected version(s)_**
_Testet in 7.x, fixed for 7.1_
