### ISSUE TITLE
Backend: Navigation: Difficulties when trying to define connected pages

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#519]
**Problem**

There is a number of oddities when trying to define "Connected pages" for a navigation node:
- The popup for selecting a page ("Select from list" for "ID of linked record") is too small
- (Pressing return in the search field might switch to the page's settings page - leaving "Navigation")
- The option "Create link" will be shown in the table as "active or disabled" in the column "active"
- (detail) The display of the content of the active column is a green small icon for active and and a large black one for "disabled"

**Affected versions**
6.3+

**Comment by UlrichKu** [comment]
> * Pressing return in the search field might switch to the page's settings page - leaving "Navigation"

Handled in #520

**Comment by bestform** [comment]
This seems to be handled already.
