### ISSUE TITLE
404 page for the backend

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#527]
Noticed in #514:

**Problem**
There is no 404 page in the backend or handling of NotFoundHttpExceptions.

**Describe the solution you'd like**
Not sure but maybe that is even intentional not having handling for (any) exception in the backend?

**Comment by bestform** [comment]
I cannot reproduce this. If i change the pagedef to a nonexisting one, I get a clear error message. The other option is to change the /cms path, which correctly leads to a 404 in the frontend.

If this is still an issue, feel free to open a new issue including steps to reproduce.
