### ISSUE TITLE
Backend: search suggestions too far on the left

### ISSUE THREAD

**Issue by esono-anja** [chameleon-system/chameleon-system#528]
**Describe the bug**
In some lists the search suggestions are displayed to far on the left and are therefore not readable.
Noticed with the following lists:
- Product selection filters
- Filter types
- Email profiles / templates
- CMS user rights
- SEO URL Handler
* Cronjobs
* CMS table settings
* CMS class inheritance manager

Looks like it occurs with long entries.

**Affected version(s)**
6.3+

**To Reproduce**
1. Go to one of the lists mentioned above.
2. Click into the search field.
3. the search suggestions are displayed now.
4. See that they are too far on the left and only partly displayed (as in screenshot).

**Expected behavior**
The search suggestions must be displayed more on the right so that you can read them completely.

**Screenshots**
![suchvorschlag1](https://user-images.githubusercontent.com/15125103/71076596-47abd800-2186-11ea-8fa8-6f2a7963572e.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [tested with Chrome and Firefox]

**Comment by pixeljunkie** [comment]
Same on Linux with Chrome.

**Comment by esono-anja** [comment]
not fixed yet:
- SEO URL handler
- CMS class inheritance manager
