### ISSUE TITLE
UpdateManager does not show dbal exceptions to user

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#529]
**Describe the bug**
Tested in development mode.

If an SQL error occurs during an update the DBAL exception output of this error is not shown to the backend user. There is a count of n occured errors, but you have no chance to see the error itself.

**Affected version(s)**
>6.3.x (maybe earlier)

**To Reproduce**
1. Record an update file of saving data to a record.
2. Change a field in the update to one, that does not exist
3. Run the update
4. See the message 1 error occured, but no further details.

**Expected behavior**
We don't need a full stacktrace here, so i would suggest to catch dbal exceptions and extract the error message + line number.
The errors should be listed below the queries that ran successfully.

**Comment by pixeljunkie** [comment]
Maybe this has something to do with this: #264

**Comment by UlrichKu** [comment]
Also fixes #264.
