### ISSUE TITLE
Sidebar: Longer menu items are truncated

### ISSUE THREAD

**Issue by esono-anja** [chameleon-system/chameleon-system#533]
Longer menu items are truncated when the menu is collpsed and the menu items therefore extend to the right when hovering.

**Affected version(s)**
6.3+

1. Go to the main menu.
2. Click on the arrow at the bottom left to collapse the menu.
3. Hover over the menu items and find a long item.
4. See that it is cut off.

**Expected behavior**
All menu items are fully legible.

![menü_7 0](https://user-images.githubusercontent.com/15125103/72062000-39f5f800-32d7-11ea-9544-547eef96ca6f.png)

Desktop and tablet

**Comment by UlrichKu** [comment]
Will be "handled" by #630.
