### ISSUE TITLE
Decimal fields are displayed truncated

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#534]
**Describe the bug**
Decimal fields with length longer than 8 digits are displayed truncated

**Affected version(s)**
6.3.x+

**To Reproduce**
1. Add a field of Type TCMSFieldDecimal / decimal to any table
2. configure it to length "10,2"
3. enter a record in this table and add a number with 10 digits
4. See the to small input field

**Expected behavior**
No truncation of the digits and a general wider input size or full width.

**Screenshots**
![Selection_731](https://user-images.githubusercontent.com/958920/72096156-ebb61880-3319-11ea-8f9a-1a22d7957de3.png)

**Technical details**
The reason is, that decimal fields have a 70px fixed width.
Should make use of bootstrap styles and resize the field to lg-4 or something and xs-12 or no limitation at all?

**Comment by UlrichKu** [comment]
The same is probably true for other types (i. e. date fields).

**Comment by esono-anja** [comment]
fixed in 6.3, but still occurs in 7.0

**Comment by esono-anja** [comment]
Decimal field is still truncated in 7.0

**Comment by esono-anja** [comment]
still truncated in 7.0:
![deci](https://user-images.githubusercontent.com/15125103/73194576-b2104a80-412c-11ea-9c09-1ab8fc9d05b3.png)
