### ISSUE TITLE
TCMSFieldLookup: onchange event in lookup fields missing

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#536]
**Describe the bug**
TCMSFieldLookup renders lookups using a twig template now, but the html template misses to output the optional onchange save event.

**Affected version(s)**
6.3.x

**To Reproduce**
1. Create a lookup field to any table
2. configure ReloadOnChange=true in the field settings
4. Nothing happens on change

**Expected behavior**
The record should reload and force a save.

**Technical details**
The twig template gets the variable onchangeAttr but does not output it in the select input html code.

**Comment by UlrichKu** [comment]
Note this is only fixed (relevant?) for the type "Value list from table".

(An example can be found for "Shipping groups" > "Shipping group handler")

**Comment by esono-anja** [comment]
@pixeljunkie If possible, please write an example of where to find such a field in the ticket description (like Ulrich did in his latest comment), thank you
