### ISSUE TITLE
TCMSFieldText: textarea heights are not dynamic anymore

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#537]
**Describe the bug**
Since the upgrade to the new backend theme the textarea heights have a min-height of 200px, which is quite big in some cases. The old default was 100px.
TCMSFieldText does a calculation of the needed line heights based on the text lines currently set.
So the height was dynamic.
The code for this calculation is still in place, but is overwritten by a min-height set in the theme CSS.

**Affected version(s)**
6.3.x

**To Reproduce**
1. Go to any record with a long text (plaintext not wysiwyg)
2. Enter 5 lines of text
3. Save the record
4. Reload the record
5. The height of the textarea is always 200px

**Expected behavior**
The idea of this calculation was to save screen space especially in tables with a lot of fields.

**Technical details**
![Selection_733](https://user-images.githubusercontent.com/958920/72155356-418acf00-33b3-11ea-90de-d25f38fb71d9.png)

A hotfix to restore the previous functionality would be to either remove the min-height from the style (tableeditcontainer.css) or change the height to min-height in TCMSFieldText.

But i would propose to remove the calculation and instead set a min-height of 100px or something like line-height + paddings * 3 rows as default and add a solution that resizes the textarea while writing like this: https://jsfiddle.net/djibe89/bofcrp8v/

**Comment by pixeljunkie** [comment]
Small additional small bug in the same line. If $cssWidth is empty (which is the default) the style attributes starts with a ";".
Instead the semicolon needs to move here: $cssWidth = 'width: '.$this->fieldCSSwidth.'; ';

**Comment by UlrichKu** [comment]
Not so easy to find that field type: 2 of these text areas can befound for example for email templates.
