### ISSUE TITLE
Backend: Modules can neither be created nor loaded in editing language English

### ISSUE THREAD

**Issue by esono-anja** [chameleon-system/chameleon-system#544]
Modules created or loaded in the editing language English are not saved. It occurs in both backend languages English and German, with editing language set to English.

**Affected version(s)**
6.3+

**To Reproduce**
- set editing language to English
- create a module, e.g. a text module
- go back to the page where you inserted the module
=> see that the module spot is empty

**Expected behavior**
The module slot should be filled with the text module, as it is when using the editing language German.

**Comment by UlrichKu** [comment]
Happens for me for every edit language.

But it is only a browser cache problem? Reloading the page will show the module.

**Comment by esono-anja** [comment]
I tested with https://demo.chameleon-system.de/ which is 6.3.3. 
Tested now again with 6.3 and 7.0 and don't see it happen
