### ISSUE TITLE
Frontend: Dropdown in top navigation doesn't work

### ISSUE THREAD

**Issue by esono-anja** [chameleon-system/chameleon-system#547]
The drop-down menu in the top navigation can no longer be opened after setting the language to English.

**Affected version(s)**
6.3+

![dropdown](https://user-images.githubusercontent.com/15125103/73439636-3858a680-4350-11ea-8a50-59bafe9779b6.png)

**Desktop (please complete the following information):**
- Windows 10
- all browsers

**Smartphone (please complete the following information):**
 - all devices

**Comment by esono-anja** [comment]
Update: just tested it now again with 7.0 => now it works. Still doesn't work in 6.3. I don't know what made it work again in 7.0, I don't recall changing anything.

**Comment by UlrichKu** [comment]
I deleted the cache on both stage servers. Now it works.
