### ISSUE TITLE
Navigation: nameof most nodes is displayed in one language only

### ISSUE THREAD

**Issue by esono-anja** [chameleon-system/chameleon-system#548]
The name of a created nodes is displayed in only one language, i.e. in the currently used backend language. For example, if the backend language is English, the German editing language will not display the German name, but only the English name (or "unnamed" if English is empty). However, this only affects the tree, in the opened navigation node (overlay) the correct name is displayed, as well as in the frontend. 

**Affected version(s)**
6.3+

**To Reproduce**
- set backend and editing language to English
- open navigation tree and create a new node
- switch editing language to German
- translate name of the node and save
- see that the name of the node is still displayed in English
- open the node again and see that the translation was actually successfully saved
- see that also the frontend displays the translated name => it only concerns the tree

**Expected behavior**
The translated name must be displayed in the tree.

**Comment by UlrichKu** [comment]
Note this bug is true for nearly all navigation tree nodes at all times.
