### ISSUE TITLE
Navigation: Confirm and cancel buttons are missing

### ISSUE THREAD

**Issue by esono-anja** [chameleon-system/chameleon-system#550]
The overlay does not show the confirm and cancel buttons in the "assign secondary navigation nodes" function (as opposed to the field above where you only assign one navigation node). This is irritating because you don't know if your input has been saved.

**Affected version(s)**
6.3+

**To Reproduce**
- go to any page settings
- go to the field "primary navigation tree node"
- assign secondary navigation nodes
- see that there is no confirm button
- close overlay
- the page settings do not yet show the newly connected navigation nodes (in contrast to when you assign the primary node). You must first save and then reload the page. That's too complicated because you think the changes have not been applied.

**Expected behavior**
The buttons are also available for the secondary nodes.
The behavior should be the same as for "assign primary navigation node" field. 

![mit_buttons](https://user-images.githubusercontent.com/15125103/73459666-8c2ab600-4377-11ea-8085-72dc8aa39ac5.png)
![ohne_buttons](https://user-images.githubusercontent.com/15125103/73459675-8f25a680-4377-11ea-96a4-1897377ffd8a.png)

**Comment by pixeljunkie** [comment]
I don`t think so, because you select not one additional node here, but multiple. This has not changed to the old version, or did it?

**Comment by esono-anja** [comment]
You are right, it's the same in the old version. 
From a user's point of view I don't understand the difference in behaviour. Thinking about it: I have always been confused with this feature since I never understood how it worked.

**Comment by esono-anja** [comment]
Is it actually working in 6.2? I don't know how to assign more than one secondary node.

**Comment by pixeljunkie** [comment]
There is a primary node (only on is possible) and you may habe 100 additional tree nodes attached to one page.
I would suggest to change the behavior to the possibility to click on the checkbox, which triggers the state change in the background. So no confirm is needed. Same behavior for selecting the single note. Checked -> saved. 
But i would move this to the following release.

**Comment by pixeljunkie** [comment]
After looking into this issue the real bug/misunderstanding is something else.
In the secondary navigation dialog the click on the checkbox already saves the selection. This is better than in version 6.2.
But 2 things are missing: 

- The save success response is missing in the modal window (instead this is triggered after reloading the main page record)
- The field needs to be updated with the multiple assigned tree node breadcrumb so the user knows that the changes where successful.

Additionally the confirm/cancel buttons in the primary selection mode are obsolet if the add the save event to the checkbox like in the secondary node tree mode. So this should be changed, too.

**Comment by ckleis** [comment]
With issue https://github.com/chameleon-system/chameleon-system/issues/572
the buttons "Confirm Selection" and "Cancel" were removed at primary node selection.

Now the primary node selection works exactly the same way as the additional nodes selection.
The click on a selectable node saves this change automatically in the background and updates the breadcrumb of the selected path. Furthermore at primary node selection the iframe will be closed immediately after selection. So no confrim button is needed anymore.

When selecting additional nodes, the selection is also saved in the background, but the iframe remains open. 
As Sven suggested, we can think about a success message for saving within the iframe and maybe a button for closing to make it clear that there is no automatic closing.

**Comment by esono-anja** [comment]
> After looking into this issue the real bug/misunderstanding is something else.
> In the secondary navigation dialog the click on the checkbox already saves the selection. This is better than in version 6.2.
> But 2 things are missing:
> 
> * The save success response is missing in the modal window (instead this is triggered after reloading the main page record)

The save-success-response is still missing.

> * The field needs to be updated with the multiple assigned tree node breadcrumb so the user knows that the changes where successful.

The field is not updated with the assigned node - only after reloading the page.

**Comment by ckleis** [comment]
With issue #572 and PR (https://github.com/chameleon-system/chameleon-base/pull/470) the breadcrumbs are correctly updated again. 
When assigning the primary node, the window is no longer closed immediately to better correct a wrong selection.
