### ISSUE TITLE
deprecated workflow email templates were not removed with v7 release

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#551]
**Describe the bug**
We removed the deprecated workflow feature from the core in version 7.0.0, but we missed to delete 3 e-mail templates.

Template System Names:
- workflowTransactionPublished
- GetWorkflowTransactionOwnership
- workflowTransactionForward

**Affected version(s)**
7.0.x

**To Reproduce**
1. Go to email templates
2. Search for "workflow"
3. See 2 templates showing up

**Expected behavior**
Should not exist anymore.

**Technical details**
Add technical context about the problem here.

**Comment by UlrichKu** [comment]
There is already an update for this: 1471527481
