### ISSUE TITLE
Change Request: rename the 049_helptext field in cms_tbl_conf

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#554]
**Describe the bug**
There is some legacy field name, that triggers me for years now. 
In cms_tbl_conf is a helptext field and the name is 049_helptext. This may be so old, that we had no field bases translation. But now wie should deprecate the field. Create a new one called 'helptext' and move all texts to this field.

**Affected version(s)**
7.0.x

**Expected behavior**
The field should not have 049_ in its name.

**Technical details**
To prevent a BC break the TCMSLogChange insert and update methods need to map the field name. I think this is already possible.

**Comment by bestform** [comment]
We will not fix this. I am aware that this is very annoying, but it has practically no consequences whereas the suggested solution will introduce a special case handling in TCMSLogChange. The drawback for a rename is too substential in this case. Feel free to open a new issue if you can find a less invasive solution.
