### ISSUE TITLE
less compiler no longer maintained / does not support php 7.4

### ISSUE THREAD

**Issue by rnuernberg** [chameleon-system/chameleon-system#555]
**Describe the bug**
Chameleon currently uses https://github.com/oyejorge/less.php to compile less. The library is no longer maintained, but there is a well maintained fork under https://github.com/wikimedia/less.php

I tested it ("wikimedia/less.php": "^2.0") with the demo Shop - worked without problems - even with php 7.4

**Affected version(s)**
7.x

**To Reproduce**
1. call the console command `app/console chameleon_system:less:compile` with php 7.4
2. See error

Workaround:
require  "wikimedia/less.php": "^2.0" and add a replace block to the projects composer.json:

```
    "replace": {
        "oyejorge/less.php": "~1.5"
    }
```

**Comment by UlrichKu** [comment]
Note: That pacakge is "only" required by the theme (here chameleon-shop-theme-bundle). Many projects which do not use it require the old less compiler package directly.

**Comment by pixeljunkie** [comment]
Works fine in demo shop and 2 other projects... no 100% guarantee the compiler has no issues with special cases.
