### ISSUE TITLE
Backend: Layout inconsistency - missing content top padding

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#560]
**Describe the bug**
The content modules have no top margin/padding to the breadcrumb.

**Affected version(s)**
6.3.x

**To Reproduce**
1. Go to backend home and any record edit view
2. See the difference in top padding

**Expected behavior**
There should always be a top border in the content container.

**Screenshots**
![Selection_778](https://user-images.githubusercontent.com/958920/74341200-9309ed80-4da7-11ea-8393-784ed702c523.png)

**Desktop (please complete the following information):**
 - OS: Linux
- Browser: Chrome + FF

**Technical details**
I'm not sure where to add the padding. Below the header toolbar/breadcrumb or for the content container. This would lead to additional space above the record edit button toolbar and would need a minus margin or something.

**Comment by pixeljunkie** [comment]
See coreUI demo how it should look like: https://coreui.io/demo/2.0/#main.html

**Comment by UlrichKu** [comment]
As a note: This is correct on all entry or list pages: There is a line of buttons on top and bottom leading to the "correct" distance to the container borders.
