### ISSUE TITLE
Backend: Cronjob lock error shown too often and unstyled

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#564]
**Describe the bug**
The success/error messages running a cronjob in the backend are not styled anymore.

**Affected version(s)**
6.3.x

**To Reproduce**
1. Go to any cronjob
2. Click on run cronjob now
3. See message output with no styling

**Expected behavior**
Styled message output. (success and error different outpu)

**Screenshots**
![Selection_805](https://user-images.githubusercontent.com/958920/75989311-54250e80-5ef3-11ea-8515-9c04e9ab71bc.png)

**Technical details**
src/CoreBundle/private/modules/CMSRunCrons/views/standard.view.php
The div container should be:
``<div class="alert alert-primary" role="alert">
``
Note: It would be nice to differ message types here and use the flashmessage service in cronjobs.
But the reason to not use messages here is, that these would popup in the backend on any cronjob that is running if you are logged in, because the messages will not be consumed if called wie cronjob and not manually.
So, if we want to change this behavior we would need to create these messages only in manual mode and log otherwise only. Should be possible to change this.

**Comment by UlrichKu** [comment]
Probably more important: This message is shown wrongly in some cases (ie timeout when the job takes long).
This should be fixed first.

Styling can be done with it.

**Comment by UlrichKu** [comment]
After discussion: We shouldn't solve any of theses two problems as this location (and the times when this error appears) is rather special.

But especially the whole cronjob solution should be adapted (#637) and then these problems will no longer occur / should be adressed.
