### ISSUE TITLE
Backend: Template Preview not working

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#571]
**Describe the bug**
In the template selection dialog the Preview button always reloads the active page template and not the clicked template.

**Affected version(s)**
6.3.x

**To Reproduce**
1. Go to any page
2. Click on page templates
3. Click on the button "preview" of any template that is not currently active
4. The currently active template is reloaded

**Expected behavior**
Show the clicked template as preview

**Screenshots**
![Selection_891](https://user-images.githubusercontent.com/958920/78174209-2fbc4380-7459-11ea-9937-1b0bedc5d84c.png)

**Technical details**
Looks like the preview URL is wrong. I would make a diff with a 6.2 version.

**Comment by UlrichKu** [comment]
Introduced with #452 (faulty type in comparisson).

**Comment by bestform** [comment]
I don't know, why I closed this. This should be in test.
