### ISSUE TITLE
NavigationTree with multiple icons for different states

### ISSUE THREAD

**Issue by ckleis** [chameleon-system/chameleon-system#572]
**Describe the solution you'd like**
The properties of a node are currently only represented by one icon, because jstree offers by default only one icon before the node title. 
However, a node can have several states, such as folder, folder with page, page, page hidden, node hidden, external link, locked.
More than one icons per node are required to display the different states.

**Possible solution (if any)**
Add the special states with additional icons before or after the title.

**Comment by ckleis** [comment]
Here's what I did:

1. what the ticket actually says and can be seen under "Navigation":
- First I checked which different states a node can have at the same time and put them in a reasonable order. These are: Node is a folder, is hidden, is an external link, has no/an assigned page, assigned page is locked, is an extranetPage
- Write a method that assigns the first state to the jstree-icon, all further states are collected and finally put in front of the name.

2. NavigationTree.php is also used in Pages and "assign further navigation nodes". So, the different status icons are now also visible here.
- I gave the primary assigned navigation node an extra css class and highlighted it with styling, also in the legend.
- It doesn't make sense that a navigation node is assigned to several pages, so now only navigation nodes can be selected that have NO assigned page.
- Up to now, every select/delect did not update the breadcrumbs on the current page. To make this possible, a breadcrumb storage is now written in advance. Now the breadcrumb-update works.

3. the class NavigationTreeSingleSelect, which is mainly used to assign the primary navigation point of a page, did not yet contain any of the above mentioned changes.
It wasn't easy to adopt, because this class still built an HTML with many data attributes and unfortunately did NOT use the much better way to pass a json object to jstree. To make it consistent with NavigationTree.php and to have these extended possibilities with the json object, I have completely rewritten NavigationTreeSingleSelect to the json method.
This was the most work in this ticket.

4. Afterwards I integrated the different statuses also at NavigationTreeSingleSelect
Also new: 
- a navigation point that already has a page assignment can no longer be selected.
- the buttons "Apply selection" and "Cancel" were removed, instead a change of the selection is now immediately saved via ajax and the window is closed. 
- the breadcrumb is now also updated here using a breadcrumb storage

5. the class "NavigationTreeSingleSelectWysiwyg" is an extension of "NavigationTreeSingleSelect". 
 All own methods had to be adapted to the json-method, furthermore all nodes must be selectable, no matter if they have a page or not.

6. navigationTreeSingleSelect is also used 3 times within the portals.
- assign portal record to a portal
- assign a start page for the portal
- assign a 404 page for the portal
Depending on the case, different navigation levels must be selectable.
Automatic saving of the portal data record after selection: Here the table name had to be available whether a page or a portal is saved.

7. Every new call of jstree must contain the current field data, even if the page is not reloaded from the server in the meantime. To do this, the field(s) must first be read out by JS every time the iframe is loaded and not initially transferred from the server.

**Comment by UlrichKu** [comment]
Test notes:

- Icons have no title: you cannot know what they mean. For example what does the "document" symbol on a folder mean?

**Comment by esono-anja** [comment]
> Test notes:
> 
> * On page settings: Assign navigation node (and additional): The whole tree is shown disabled except for the currently selected entry (not sure if that is correct; are the disabled ones the ones that already have a page connection?). 

**=> That's correct (as mentioned above) because one node can be assigned to one page only.**


> That sole option can be disabled which then directly closes the dialog - I would probably expect an "Are you sure?" here. When reopening the dialog that entry is still the only selectable everything else is disabled.

**=> This concerns assigning a primary node and the usability is in fact not very clear. If you deselect a primary navigation node, the layover closes immediately. However, it should remain open, since you certainly want to assign another node as primary node to the page. Closing the overlay can then be done with the close-x. Then the usage would be the same as assigning the other navigation nodes: the overlay opens, I select or deselect nodes. The overlay remains open the whole time until I close it deliberately.**

> * The "breadcrumb" on the page page is updated when deselecting a page connection but not anymore when selecting one again.

**=> is handled in issue #550**  

> * The breadcrumb on the portal page (for 404 page) is not updated when changing the selection.

**=> should be solved with #550** 

> * Icons have no title: you cannot know what they mean. For example what does the "document" symbol on a folder mean?

**=> there is a legend next to the tree, in my opinion sufficient**

**Comment by ckleis** [comment]
> That sole option can be disabled which then directly closes the dialog - I would probably expect an "Are you sure?" here. When reopening the dialog that entry is still the only selectable everything else is disabled.

The selection and deselection is saved in the background immediately after the click. We should avoid too many clicks here in Svens opinion.

But when assigning the primary node, an immediate closing of the modal is really surprising for the user.  Especially if it is mistakenly deselected. That's why I leave the modal open now until the user closes it with the X himself.
So the usage is also the same as assigning the further navigation nodes.
 
> * The "breadcrumb" on the page page is updated when deselecting a page connection but not anymore when selecting one again.
> 
> * The breadcrumb on the portal page (for 404 page) is not updated when changing the selection.

That was a mistake. I corrected it.

> * Icons have no title: you cannot know what they mean. For example what does the "document" symbol on a folder mean?

When assigning the primary navigation node and in the wysiwyg editor the legend was missing. I added it.
