### ISSUE TITLE
Login user name is case sensitive handled

### ISSUE THREAD

**Issue by michaelcmichaelis** [chameleon-system/chameleon-system#575]
**Describe the bug**
Login with a user name, using different up- or lowercase letters than the _registered_ user name, leads to a login error.

**Affected version(s)**
7.x (may be also earlier)

**To Reproduce**
1. Go to the login page (e.g. https://demo.chameleon-system.de/Login/)
2. Enter your _user name_ differently from the registered one (e.g. "Myname@home.org" instead of "myname@home.org")
3. Press the login button
4. See the login error message (e.g. "Login or password wrong")

**Expected behavior**
The login username have to be ignored respect to upper- or lowercase typing (case insensitive).
For example, typing "myname@home.org" (as registered) or "MyName@home.Org" (at login) shouldn't matter.

**Screenshots**
![Username-Field-Login-Error](https://user-images.githubusercontent.com/6185613/78784249-4ad10b00-79a5-11ea-8667-cc88e539cea4.png)

**Comment by UlrichKu** [comment]
Problem "fixed" by setting an existing config flag to true for any new project / in the demo shop.
