### ISSUE TITLE
Automatic login post registration when confirmation email is required fails

### ISSUE THREAD

**Issue by rnuernberg** [chameleon-system/chameleon-system#578]
**Describe the bug**
If the extranet is configured to require the user to click on a double opt in link post registration, then the user should be logged in once they click on the link. 

The current link will confirm the user, but fails to auto login requiring the user to switch to the login page and manually login from there.

**Affected version(s)**
7.0+

**Technical details**

I think the problem is, that we call a Logout on the user - instead of calling the extranet provider reset method in \MTExtranetCoreEndPoint::ConfirmUser

**Comment by esono-anja** [comment]
7.1:
I did not receive an email and therefore couldn't check if one is logged in with the link (in 7.0 I received the mail. In both versions I have stored in the extranet that the user has to confirm the registration).

7.0 and 7.1:
After registering, one goes directly to the login page. Wouldn't it be better if instead of the login you get a message that you receive an email with a confirmation link for the registration?

**Comment by UlrichKu** [comment]
> 7.1: I did not receive an email and therefore couldn't check if one is logged in with the link (in 7.0 I received the mail. In both versions I have stored in the extranet that the user has to confirm the registration).

Who receives mails on test systems is a system configuration (should now be corrected).

> 7.0 and 7.1: After registering, one goes directly to the login page. Wouldn't it be better if instead of the login you get a message that you receive an email with a confirmation link for the registration?

That sounds like a new feature.
This issue here is a bug fix.

**Comment by rnuernberg** [comment]
@UlrichKu I disagree. When a post registration is required, the system used to show a message, that a confirmation email is underway. Not doing so, will confuse the user.

**Comment by UlrichKu** [comment]
What message is this?
I couldn't find any message (in Portals > System messages) that might have been used here.
There is only one being shown when the email was changed and that needs to be confirmed.

From a code perspective any e-mail sending was very likely not affected here.

**Comment by esono-anja** [comment]
7.1: Email sending works now.


> @UlrichKu I disagree. When a post registration is required, the system used to show a message, that a confirmation email is underway. Not doing so, will confuse the user.

Is this going to be implemented with this ticket? The status is not clear to me, therefore I cannot close this ticket.

**Comment by esono-anja** [comment]
follow-up ticket #748
