### ISSUE TITLE
Adjust error message for vouchers with minimum order value

### ISSUE THREAD

**Issue by esono-anja** [chameleon-system/chameleon-system#584]
from #540: This concerns the error message for vouchers with minimum order value, if the minimum order value is not reached.

I find the error message VOUCHER-ERROR-2 problematic:

> To use this voucher a minimum order value of XX € is required. Please note that book-price-bound articles are only counted towards the value of goods in the case of sponsored vouchers.

This message appears when the minimum order value has been fallen below, for both sponsored and non-sponsored vouchers. In my opinion, it makes no sense in case of a sponsored voucher. Furthermore I find the wording sponsored / not sponsored difficult. Would a customer know what that means? We should change this to sponsored = purchase voucher and not sponsored = promotion voucher.

Here's what I would do:
1. in the case of sponsored vouchers with a minimum order value, the following message should appear if the minimum order value is not reached:
A minimum order value of XX € is required to use this voucher.

2. for non-sponsored vouchers with a minimum order value, the message should read
For the use of this voucher a minimum order value of XX € is required. Please note that book-price-bound articles are only counted towards the value of goods in the case of purchased vouchers. Unfortunately, book-price related articles cannot be included in promotion vouchers.

Concerns: 6.2 / 6.3 / 7.0

**Comment by UlrichKu** [comment]
Are "book-price-bound articles" and "book-price related articles" the same as the current "fixed retail prices such as books"?

**Comment by UlrichKu** [comment]
What would be the relevant formulation in German?
"Bitte beachten Sie, dass buchpreisgebundene Artikel nur bei gesponserten Gutscheinen zum Warenwert gezählt werden."

**Comment by pixeljunkie** [comment]
We need a different word for "sponsored". Nobody knows what this means.

**Comment by esono-anja** [comment]
> What would be the relevant formulation in German?
> "Bitte beachten Sie, dass buchpreisgebundene Artikel nur bei gesponserten Gutscheinen zum Warenwert gezählt werden."

1. Bei gesponsorten Gutscheinen mit Mindestbestellwert soll folgende Meldung erscheinen, wenn der Mindestbestellwert unterschritten wird:
_Für die Verwendung dieses Gutscheins ist ein Mindestbestellwert von XX € erforderlich._

2. Bei nicht gesponsorten Gutscheinen mit Mindestbestellwert soll die Meldung lauten:
_Für die Verwendung dieses Gutscheins ist ein Mindestbestellwert von XX € erforderlich. Bitte beachten Sie, dass buchpreisgebundene Artikel nur bei gekauften Gutscheinen zum Warenwert gezählt werden. Auf Aktionsgutscheine können buchpreisgebundene Artikel leider nicht berücksichtigt werden._

**Comment by UlrichKu** [comment]
As there is no difference in messages based on the voucher type: Message changed to the text for promotion vouchers - if it has not been changed otherwise yet.

**Comment by esono-anja** [comment]
> As there is no difference in messages based on the voucher type: Message changed to the text for promotion vouchers - if it has not been changed otherwise yet.

From my point of view, the distinction between the two types of vouchers makes sense.

For purchase vouchers, it is sufficient to indicate that the minimum order value has not been reached. More information at this point is totally confusing.
In the case of promotion vouchers, it is pointed out that they are only valid for articles without fixed book prices (because of the price fixing) - and this information is not needed for a purchased voucher.

That is why I would make the distinction.

However, the question arises whether this notification regarding fixed book prices should only be applied in shops that also sell books? I would find it totally confusing if I received this message in a clothes shop where there are no books to buy.
It would make more sense to have only the general message _A minimum order value of XX € is required to use this voucher._ And the reference to fixed book prices only in shops for which this is relevant.
