### ISSUE TITLE
TCMSImageEndpoint: Loading failure is not properly detected

### ISSUE THREAD

**Issue by kzorluoglu** [chameleon-system/chameleon-system#590]
**Describe the bug**
TCMSImageEndpoint Trying to access array offset on value of type bool notice

**Affected version(s)**
The All Chameleon version with PHP 7.4

**To Reproduce**
1. Set your PHP version for the project 7.4.X, 
2. go to homepage
3. It's coming as ContextException.

**Expected behavior**
Script/Method tries to read "path" value from _arrayable_ $this->aData.. But isn't array, it's a boolean.

Actually, i don't know in which stations this variable will be setted as an array, but **In normally request** this is empty array.

**Technical details**
This variable aData setted false, if the file not exists.
![Screenshot from 2020-06-05 15-27-15](https://user-images.githubusercontent.com/5286454/83881538-209b8f80-a741-11ea-9909-1ee1da233931.png)

**Comment by UlrichKu** [comment]
Doesn't really have to do with php 7.4 but is (only) an insufficient handling of a failure during image loading.
