### ISSUE TITLE
Backend: Refactor update recorder

### ISSUE THREAD

**Issue by FinnBrackrock** [chameleon-system/chameleon-system#591]
**Describe the solution you'd like**
It would be quite useful if only the db entries that have really been changed ended up in the update script

**Comment by UlrichKu** [comment]
Only some refactoring (variable renaming, earlier check) was done here.

**Comment by fabianbarth-esono** [comment]
The change from 

```php
$bIsUpdateCall = (($bIsUpdateCall && $bRecordExists && $bForceInsert) || ($bIsUpdateCall && !$bForceInsert));
```

to 

```php
$bIsUpdateCall = $bIsUpdateCall && ($bRecordExists && $bForceInsert) || (!$bForceInsert);
```
is a logic change, because $bIsUpdateCall is now true, if !$bForceInsert

**Comment by UlrichKu** [comment]
> is a logic change, because $bIsUpdateCall is now true, if !$bForceInsert

It is / should be logically equivalent: the bIsUpdateCall ist just moved out of both brackets.
