### ISSUE TITLE
Backend: Connections with "cms_field_conf" are not rendered properly

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#593]
**Problem**

A table field with name "cms_field_conf_mlt" which is display as a (list) matrix of checkboxes ist not rendered properly. (For example found for Variant sets > .. > Fields of variant which may differ from parent item)

- Not sorted by tab
- Not sorted by name
- Multi-line entries break the whole block

**Technical details**

This is handled by TCMSFieldLookupMultiselectCheckboxes.

**Comment by fabianbarth-esono** [comment]
The grouping of the checkboxes works now. But the CSS styling is off:

![CheckboxStyle](https://user-images.githubusercontent.com/17163435/101756493-5e091d00-3ad6-11eb-82e2-0a47cd833d8e.png)

![CheckboxStyle1](https://user-images.githubusercontent.com/17163435/101756490-5d708680-3ad6-11eb-9874-7c77d433cdf5.png)

**Comment by UlrichKu** [comment]
Your Browser cache probably.

**Comment by fabianbarth-esono** [comment]
> Your Browser cache probably.

Sorry, had the browser cache still enabled from another test.
