### ISSUE TITLE
Limit product preorder retention time

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#60]
**Describe the solution you'd like**
When a customer registers to be notified when a product currently sold out is available again, this registration might stay for a long time (if the product doesn't get available again). The retention time should be limited so that records get deleted after some time.

**Possible solution (if any)**
We could implement a cronjob that periodically cleans pkg_shop_article_preorder. The retention time could be configurable in the backend.

**Comment by bestform** [comment]
I don't see why I as a customer would not want to be notified after a certain amount of time. I in fact would be surprised to see the product back in stock after - say - a year and I wasn't notified.
