### ISSUE TITLE
NotFoundException in the log for every 404 page access

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#605]
**Describe the bug**
Depending on (logging) configuration there might be an error log entry for every time a page is not found.

**Affected version(s)**
6.3+

**Technical details**

There is an old solution for this problem in (ChameleonExceptionListener). However this does not work (anymore?) because it tries to overwrite a class (Symfony\ExceptionListener) with the help of a parameter.

**Comment by UlrichKu** [comment]
There is already a solution for this in the current demo shop (chameleon-system): Use a fingers_crossed logger with option excluded_404s set.

**Comment by fabianbarth-esono** [comment]
Didn't see any log messages when calling invalid URLs that returned 404 codes.
