### ISSUE TITLE
Backend: sidebar: element border on focus

### ISSUE THREAD

**Issue by FinnBrackrock** [chameleon-system/chameleon-system#609]
**Problem**

Once you click a menu item on the sidebar, there is now some weird looking rounded border around the list item.
It seems like, due to some recent update, chrome is now adding that border to any element that is being focused.

**Affected version(s)**

6.3+

**Possible solution**

Adding outline: none; should do the job.

**Comment by UlrichKu** [comment]
Do you have a screen shot for me?

I'm not sure I'm seeing this problem.

**Comment by pixeljunkie** [comment]
![Selection_999(166)](https://user-images.githubusercontent.com/958920/89150737-851b7500-d55f-11ea-8907-78d76b7f60a0.png)

**Comment by pixeljunkie** [comment]
It is a :focus browser style.

![Selection_999(167)](https://user-images.githubusercontent.com/958920/89150869-dfb4d100-d55f-11ea-8c5e-16f3c9e6258b.png)

**Comment by UlrichKu** [comment]
Ok, also happens for me.
(But only for the folder entry and only when closing and opening it after page (re) load.)
