### ISSUE TITLE
restriction parameter does not work for field type CMSFIELD_EXTENDEDTABLELIST

### ISSUE THREAD

**Issue by rnuernberg** [chameleon-system/chameleon-system#610]
**Describe the bug**
If you try to restrict the records available in the extended table list field type by providing a field from the current record, then the restriction is always taken as a literal value - it is no longer possible to reference a field value from the current record.

**Affected version(s)**
7.0.x

**To Reproduce**
1, create a table 'contact'
2. create a table 'person' with 'contact' being a property table of 'person'
3. add an extended lookup that allows the user to select only entries from 'contact' that are assigned to the current person by adding `restriction=person_id=[{id}]`
4. When you now view the list of contacts to select from you will get zero hits (because the list is restricted to all contacts having a `person_id` with the value `[{id}]`. Instead we would expect the list of contacts to be restricted to all contacts with field `person_id` being equal to the id of the person we are currently editing.

**Technical details**
The field type `CMSFIELD_TABLELIST` correctly replaces `[{id}]` by the id of the person being edited in `\TCMSFieldLookup::GetOptionsQuery`
Unfortunately, the extended lookup does not (it should in `\TCMSFieldExtendedLookup::_GetOpenWindowJS`)

**Comment by UlrichKu** [comment]
Tested with 7.0. 

Works with restriction being present on the extended lookup field: only showing some entries.

With no restriction: all entries are shown.
