### ISSUE TITLE
Missing icons due to icon path change

### ISSUE THREAD

**Issue by swiesamstag** [chameleon-system/chameleon-system#612]
**Describe the bug**
Some views use non-existent icons

**Affected version(s)**
7.0

**Technical details**
The icons-Folder has been (re)moved in newer versions of chameleon.

Affected files:
- /vendor/chameleon-system/chameleon-base/src/CoreBundle/private/rendering/objectviews/THTMLTable/THTMLTableColumn/filter.view.php
- /vendor/chameleon-system/chameleon-base/src/CoreBundle/private/rendering/objectviews/THTMLTable/THTMLTableColumnDate/filter.view.php
- /vendor/chameleon-system/chameleon-base/src/CoreBundle/private/rendering/objectviews/THTMLTable/THTMLTableColumnNumber/filter.view.php

All of them have a reference to
`<img src="/chameleon/blackbox/images/icons/magnifier.png" ...`

But the "images" folder below path to "/chameleon/blackbox/" (symlinked to /vendor/chameleon-system/chameleon-base/src/CoreBundle/Resources/public/) does not contain an "icons"-Folder anymore.

**Possible solution**
Most icons have been moved to "/chameleon/blackbox/themes/standard/images/icons/.." but according to mapping, those 3 icons should be replaced by "'magnifier.png' => 'fas fa-search'," style.

**Comment by pixeljunkie** [comment]
This component should be deprecated and removed or moved to a legacy bundle.
I would not recommend to make any effort to maintain this very old component in the core anymore.
I you need this component you should copy and rename it in your project context as a quick solution.

**Comment by swiesamstag** [comment]
Alright. Thanks.
