### ISSUE TITLE
Backend: list shows tooltip.css not found in console

### ISSUE THREAD

**Issue by rnuernberg** [chameleon-system/chameleon-system#616]
**Describe the bug**
When viewing a listing (suche as the product listing) the browser will show an error in its console, that the file /chameleon/blackbox//themes/standard/css/tooltip.css could not be loaded.

**Affected version(s)**
7.0.x

**To Reproduce**
1. Open product listing
2. view browser console output
3. see 404 message

**Expected behavior**
If the file is still needed, then I would expect it to be loaded. If it is no longer needed, then it should not be loaded.

**Comment by pixeljunkie** [comment]
I'm very sure this file is deprecated and was removed in 7.0.x but the reference was not removed.

**Comment by UlrichKu** [comment]
This doesn't happen in the demo shop.

I see one search hit for "tooltip.css" (\CMSModuleImageManager::GetHtmlHeadIncludes) but that doesn't seem to be used (anymore?).

**Comment by rnuernberg** [comment]
I was able to reproduce in the demo shop (version 7.0) by viewing the product listing.

![image](https://user-images.githubusercontent.com/1104497/90023288-dcce8480-dcb3-11ea-8c8c-6f9f4b8382da.png)
