### ISSUE TITLE
Backend: NavigationTreeSingleSelectWysiwyg injected services incompatible to parent class

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#620]
**Describe the bug**
NavigationTreeSingleSelectWysiwyg extends NavigationTreeSingleSelect but the injected services differ and this leads to incompatibilities.

**Affected version(s)**
6.3.x

**To Reproduce**
1. Go to any record with a field of type "wysiwyg text"
2. Click on the link icon in the wysiwyg toolbar 
3. Click on CMS source

**Expected behavior**
Show the tree selection.

**Technical details**
Add technical context about the problem here.

`Type error: Argument 1 passed to ChameleonSystem\CoreBundle\Bridge\Chameleon\Module\NavigationTreeSingleSelect\NavigationTreeSingleSelect::__construct() must implement interface ChameleonSystem\CoreBundle\Util\InputFilterUtilInterface, instance of Doctrine\DBAL\Connection given, called in vendor/chameleon-system/chameleon-base/src/CoreBundle/Bridge/Chameleon/Module/NavigationTreeSingleSelectWysiwyg/NavigationTreeSingleSelectWysiwyg.php on line 52
`

**Comment by ckleis** [comment]
After a Symfony and PHP update, it is no longer tolerated that a child class has different service parameters than its parent. This now leads to an error.
I have removed the unnecessary services in NavigationTreeSingleSelectWysiwyg
