### ISSUE TITLE
Error in BasketVariableReplacer if request contains none utf-8 encoded paramter 

### ISSUE THREAD

**Issue by pSpeck** [chameleon-system/chameleon-system#622]
**Describe the bug**
BasketVariableReplacer replaces a twig variable with request paramters. If one parmater contains a none utf-8 encoded parameter the entire replace will fail. So on a add to basket click all paramters will be lost.

**Affected version(s)**
6.2 (fixed for 7.0)

**To Reproduce**
1. enter url with a parmter like test=test%F6
2. BasketVariableReplacer->handleRequest logs an error
3. Parameter test is not added to hidden basket parameter and is lost on click add to basket

**Expected behavior**
Maybe the shop should recognice the paramter ist not utf-8 endcoded and should do the right encoding.

**Comment by UlrichKu** [comment]
Test details:

1. Open page with an "add to basket" button
2. Add "?test=test%F6&test2=test2 to the url and press enter (reload page)
3. Inspect the source code of the "add to basket" button: it should contain the test2 as a hidden input field
