### ISSUE TITLE
Basket variable replacer: Improve output performance

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#629]
Noticed in #622:

**Problem**

Introduced in #582 and fixed in #622: the basket variable replacer renders every request parameter - even if there is finally no need for that

**Affected version(s)**

7.0

**Describe the solution you'd like**

This should be done only if needed - check for the existence of the placeholder first.

**Comment by fabianbarth-esono** [comment]
Tested if the request parameters were still present as expected.
