### ISSUE TITLE
Backend: Disable reduced sidebar

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#630]
Replaces #366 #533 

**Problem**
There are a number of problems with the reduced sidebar that can only be resolved with large effort (e. g. #366).

**Possible solution (if any)**
Disable reduced sidebar; theres is already / still the possibility to remove the sidebar (and thus make room) with clickingn the burger menu.

**Comment by bestform** [comment]
The problems in #366 #533 do not value the proposed solution.
