### ISSUE TITLE
Error in cron job scheduler: Cannot compare DateInterval

### ISSUE THREAD

**Issue by rnuernberg** [chameleon-system/chameleon-system#631]
**Describe the bug**
There are errors in customer logs of the form:
 PHP message: PHP Warning: Cannot compare DateInterval objects in /usr/local/apache2/htdocs/releases/build-43/customer/vendor/chameleon-system/chameleon-base/src/CoreBundle/CronJob/CronJobScheduler.php on line 89

The Tests for \ChameleonSystem\CoreBundle\CronJob\CronJobScheduler also brake (due to the same error)

**Affected version(s)**
6.3

**To Reproduce**
run the tests for the class: ./vendor/bin/phpunit vendor/chameleon-system/chameleon-base/src/CoreBundle/Tests/CronJob/CronJobSchedulerTest.php

**Comment by UlrichKu** [comment]
Tested with 7.0 and some local debugging of method `calculateCurrentPlannedExecutionDate`
