### ISSUE TITLE
Backend: Cannot Change Value of Color Picker via Text Field

### ISSUE THREAD

**Issue by fabianbarth-esono** [chameleon-system/chameleon-system#644]
**Describe the bug**
When a color picker field already has a value, the value cannot be changed via the text input field: As soon as the value is changed to a invalid color (for example while typing), the value is changed back to the old value.

**Affected version(s)**
6.3 and up

**To Reproduce**
1. Open any record in the backend with a color picker field (color code in shop categories for example)
2. Select a color and save.
3. Reload
4. Try to change the color by first removing the old value from the input field -> value is changed back to old value.

**Expected behavior**
Should be able to change the value directly in the input field.

**Screenshot / Animated Gif**

![ColorPicker](https://user-images.githubusercontent.com/17163435/94551730-1c4a3380-0256-11eb-9d56-eda49b699c2f.gif)

**Comment by esono-anja** [comment]
Until now you could change the color using the text field, but you had to press the Enter button a bit longer. Now the behavior is such that when deleting the individual letter/number values, other colors appear. To enter the correct color via the text field, you have to press the Enter button longer. So there is no real difference to the behaviour before. Is this how it is meant to be after the fix?

![chrome-capture](https://user-images.githubusercontent.com/15125103/95843888-867bd180-0d48-11eb-9709-466c690521f9.gif)

**Comment by UlrichKu** [comment]
> you have to press the Enter button longer. So there is no real difference to the behaviour before. Is this how it is meant to be after the fix?

I never knew that thing with the Enter key longer. (not old and not new behavior)

The bug before was that a change with keyboard was not possible at all.

Entering a correct code (with 6 digits) should now work / be sufficient?

**Comment by esono-anja** [comment]
Above I actually meant the backspace key (not Enter).

What does work is to copy a color value into the field. But this worked also before (I tested it with 7.0.9). 
Deleting the characters one by one does not work -> instead different color suggestions are inserted.
Or start typing #FFF - it is autocompleted to # FFFFFF.

**Comment by fabianbarth-esono** [comment]
It is not working for me, either. The way I got it to work as I would expect was to display the picker directly like this:
![ColorPickerField](https://user-images.githubusercontent.com/17163435/97009503-746a1200-1544-11eb-956f-450342c0e7c7.png)
This is the way it's done in the pickers documentation. Are there any objection to just showing it this way?

**Comment by pixeljunkie** [comment]
The inline widget would be totally o.k. with me. Go for it.
