### ISSUE TITLE
Backend: bundle resource view files not automatically found

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#648]
**Describe the bug**
If you want to use bundles in the backend the we always need a symlink to the bundles' twig snippets directory in a deprecated path.

Example: 
```
Path: src/extensions/snippets-cms/imageCrop

Symlink to: ../../../vendor/chameleon-system/chameleon-base/src/ImageCropBundle/Resources/views/snippets-cms/imageCrop
```

**Affected version(s)**
7.0.x and earlier

**To Reproduce**
1. Open src/extensions/snippets-cms/
2. Try to overwrite the TCMSFIeldWYSGWYG field
3. You need a symlink to the twig template here, like several bundles (imageCrop, mediaManager etc.)

**Expected behavior**
The renderer should look into any bundle and try to find a directory "Resources/views/snippets-cms"

**Technical details**
For themes in the frontend, we configure the snippet paths, so we are able to load them in a custom order.
I don`t think this is necessary for the backend at this point, because it is not possible yet, too, but maybe we should take this in count for a solution.

**Comment by UlrichKu** [comment]
Note: For frontend themes this looking into <bundle>/Resources/views only works if this bundle is listed in the theme's snippet chain.

However the issue is still valid: for any backend view you'll need a symlink in src/extensions

**Comment by UlrichKu** [comment]
This leads to problems during (first) update execution: the auto class TdbCmsConfig is not yet updated.

(and thus a problem triggered by this and #529)

**Comment by UlrichKu** [comment]
> This leads to problems during (first) update execution: the auto class TdbCmsConfig is not yet updated.

Solved by another service.
