### ISSUE TITLE
Service for unused / collision free table id

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#656]
**Problem**
For any added database entry there is the need to generate an unused id in that table.

**Describe the solution you'd like**
Add a dedicated service for this.
There is already code for this in \TCMSLogChange::createUnusedRecordId() however that is only intended for update files (and should use the new service then).

**Testing**
This is a code-only change.

**Comment by UlrichKu** [comment]
Question here again: Why not use a true GUID here?

(Instead of simply a random number that could conflict.)

**Comment by bestform** [comment]
Tested ok.
