### ISSUE TITLE
Adding new items to tables with active changelog settings leads to an error

### ISSUE THREAD

**Issue by punixde** [chameleon-system/chameleon-system#658]
**Describe the bug**

You want to save a new item to a table via frontend (not CMS).
The table-configuration settings for the item to be created has an active changelog setting.
The save path will lead to a critical error.

`request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getFieldsIndexed() on null"`

**Affected version(s)**

Reproduced with 7.0.8.2 and 7.0.9.2

**To Reproduce**

Add a new item with a process like this and call it from a shop or website (not CMS):

`$tableConf = new \TCMSTableConf();`
`$tableConf->LoadFromField('name', $item->table);`
`$tableEditorManager = new \TCMSTableEditorManager();`
`$tableEditorManager->Init($tableConf->id, $item->id);`
`$tableEditorManager->Save($item->sqlData);`

When `Init()` returns false, meaning we have a new item, the `Save()` will fail.

Because it is a new item, `oTablePreChangeData` won't be created. But during execution, following the `PostSaveHook`-path, the respective Hook of the `TCMSTableEditorChangeLog` processes this field with the settings for `$oTableConf->fieldChangelogActive` being set to true. In the end, it will call for `oTablePreChangeData->getFieldsIndexed()` and dies.

**Expected behavior**

PreChangeData should not be required for creating new items.

**Technical details**

Entry-Point: \TCMSTableEditorManager::Save
Error in: \TCMSTableEditorChangeLog::getOldFields

**Comment by UlrichKu** [comment]
You would call $tableEditorManager->Insert instead of Save if it is a new dataset.
