### ISSUE TITLE
Cross domain frontend user impersonation

### ISSUE THREAD

**Issue by j6s** [chameleon-system/chameleon-system#661]
**Describe the bug**
When trying to impersonate a frontend user on a portal that runs on a different domain than the backend, the login fails since the session is not persisted across domains.

**Affected version(s)**
all

**To Reproduce**
1. Create a frontend / extranet user that is assigned a portal id of a portal that runs on a different domain than the backend
2. In the backend, open the user edit view
3. Click the "Login as User" button
4. You are redirected to the home page of the portal associated with the user but that user is not logged in.

**Expected behavior**
 You are redirected to the home page of the portal associated with the user logged in as that user.

**Technical details**
This is due to the user being logged in while being in one session but the new domain context opens a new session.

**Comment by pixeljunkie** [comment]
I think this is a problem of cross domain cookie security. I`m not sure if there is a solution for this without lowering the security settings.

**Comment by rnuernberg** [comment]
@pixeljunkie I would suggest working with a temporary login token. This would avoid the cross cookie problematic.
