### ISSUE TITLE
TCMSLogChange::GetMessageTypeByName no longer works

### ISSUE THREAD

**Issue by rnuernberg** [chameleon-system/chameleon-system#662]
**Describe the bug**
Calling `TCMSLogChange::GetMessageTypeByName('Error')` returns am empty string instead of an ID.

**Affected version(s)**
7.0.x

**To Reproduce**
1. call TCMSLogChange::GetMessageTypeByName('Error')
2. see that it returns an empty value instead of an ID

**Expected behavior**
The ID should be returned.

**Technical details**
It may be worthwhile to also address #126 when looking at this issue.

**Comment by pixeljunkie** [comment]
Looks like the reason for this behavior is the introduction of the multilingual name field and changed defaults (english).
We should add a fallback here to search in the active language and in the base language so this BC break gets fixed and then we should add a language independent systemname field which is searched in the first place.
