### ISSUE TITLE
Date field: Delete key cannot be used to empty date

### ISSUE THREAD

**Issue by fabianbarth-esono** [chameleon-system/chameleon-system#665]
From: https://github.com/chameleon-system/chameleon-system/issues/624#issuecomment-739804368

**Describe the bug**
In any date field in the backend you cannot reset it to empty.

**Affected version(s)**
7.0

**To Reproduce**

Go to any data set with a date - an easy example is found for "Search > Shop search index status"
Empty the content of a date field with the keyboard using the delete key.
Click Save
Reload the page
-> the date field's contents are restored

**Technical details**

Tempusdominus does not correctly trigger its change.datetimepicker event when only the DELETE key is used.
It works for example with the BACKSPACE key.

Eonasdan/tempus-dominus#1976

The issue at tempus-dominus was closed without any changes.

**Comment by UlrichKu** [comment]
It works better with an updates version (5.39 of Tempusdominus). Esp. resetting the date (in the hidden field) already on the first attempt and when pressing the DELETE key.

However it still can be made to have different contents displayed and in the hidden field.
For example deleting the last character in the field (i. e. the M of AM) will set the hidden field to empty (and that is used on save) but the visible date field still shows the old date (with the M again added).
