### ISSUE TITLE
Backend: DB update recorder does not record MLT insertion

### ISSUE THREAD

**Issue by j6s** [chameleon-system/chameleon-system#667]
**Describe the bug**
When creating a new related record while in the edit view of another record (clicking the "new" button on a relation),
the new record is inserted into the database along with the MLT-Table row linking the two records together.

If a DB-Logger is active during this time, the MLT-insertion is not recorded into the migration.

**Affected version(s)**
* 7.1
* 7.0
* 6.3

**To Reproduce**
1. Activate DB-Logger
2. Open the edit view of a record with relations (e.g. Edit a product)
3. While in the edit view of the record, click the "new" button on a relation (e.g. "new" button on the relation "group" on products)
4. Fill out the new form and save it
5. Open the migration generated by the DB-Logger. It will contain 2 items:
    * Insertion of the new record
    * Update of the new record.

When resetting the database back to it's original state and applying the migration,
the new record (e.g. the group) will be created but never linked to the original
record (e.g. the product).

**Expected behavior**
When recording the insertion of a new relation, the DB-Logger should contain 3 items:
* Insertion of new record
* Update of the new record
* __Insertion into `*_mlt` table linking the 2 records together__

The latter currently does not exist

**In code**

The generated migration correctly contains the following:

```php
// Insertion of related model
$data = TCMSLogChange::createMigrationQueryData('shop_article_group', 'en')
  ->setFields([ /* ... */ ]);
TCMSLogChange::insert(__LINE__, $data);

// Updating of related model
$data = TCMSLogChange::createMigrationQueryData('shop_article_group', 'de')
  ->setFields([ /* ... */ ])
  ->setWhereEquals([ /* ... */ ]);
TCMSLogChange::update(__LINE__, $data);
```

What is missing however is the insertion into the MLT table:

```php
// Missing:
// Insertion into MLT table linking the group to the product
// that was edited in the first place.
$data = TCMSLogChange::createMigrationQueryData('shop_article_shop_article_group_mlt', 'de')
  ->setFields([
      'source_id' => '3e95d854-9b7b-85a1-5e6e-d790f3b84b15',
      'target_id' => '4b894a71-228f-790d-1ae1-ac2106a7b9bf',
      'entry_sort' => '0',
  ]);
TCMSLogChange::insert(__LINE__, $data);
```

**Comment by UlrichKu** [comment]
Can confirm this (for "related products").

Interestingly upon delete all the (potential) mlt deletes are in the recorded update.

**Comment by UlrichKu** [comment]
See \TCMSTableEditorManager::Insert()

The insert of the data set is handled \TCMSTableEditorEndPoint::Insert() -> \TCMSTableEditorEndPoint::_WriteDataToDatabase() which writes the update log.

However the insert in the mlt is done a few lines later directly to the database.
