### ISSUE TITLE
Set email security to strict by default

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#68]
**Describe the solution you'd like**
The configuration value chameleon_system_core.mailer.peer_security is set to "permissive" by default (for BC reasons). We should set "strict" as default in the future.

**Comment by umulmrum** [comment]
I set 6.3.0 as milestone, because it is a BC break that can easily be communicated to and averted by developers - should only be set to 7.0.0 if we're really strict about BC (but I prefer security by default).

**Comment by UlrichKu** [comment]
This can be found in \ChameleonSystem\CoreBundle\DependencyInjection\Configuration::getMailerConfig().
