### ISSUE TITLE
Websites in production mode show empty spot message in html source code

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#682]
**Describe the bug**
If you use a page template that has module spots set in the template, that have no corresponding configuration record in the database, the website outputs a notification in form of: 
```html
<!-- ERROR: unable to find module [spot1] -->
```
There should not be a discrepancy between spots and spot config record in theory, but the reality looks different.

**Affected version(s)**
7.0.x and earlier

**To Reproduce**
1. Look into your websites HTML source code
2. I`m sure you will find the described error comment.
3. If not, remove a spot config record from one layout.
4. Now see the output in the source code

**Expected behavior**
The output might be o.k., so you are able to fix the problem, but please only in dev mode and not prod.

**Technical details**
We need a single if statement to fix this by checking for prod mode.

**Comment by UlrichKu** [comment]
This only happens for configuration errors. Ie requesting a module that is not defined as spot in the page template or its theme blocks.

It is fixed for those.
