### ISSUE TITLE
Cronjobs extended from TCMSCronJob cannot be executed

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#689]
**Describe the bug**
When executing certain cronjobs an error message will appear (in the log):
An exception occurred while executing 'UPDATE `` SET `lock` = '1' WHERE `id` = ?' with params ["278e6c9f-19e4-5fcc-ddfe-f32cb5a374c0"]:  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' 

**Affected version(s)**
7.1

**To Reproduce**
1. Execute the cronjob "Order confirmations"

**Expected behavior**
- Fix for every core cronjob.
- Fix for every code location using cronjobs.
- Document this as a necessary upgrade step for customer projects.

**Technical details**
The problem only occurs for those cronjobs which also overwrite the constructor.

The problem occurs in \TCMSCronJob::_Lock(). Here the table name is empty.

Many locations falsely expect a cronjob to be TCMSCronJob, for example:
\ChameleonSystem\CoreBundle\CronJob\CronJobFactory::constructCronJob()

**Comment by rnuernberg** [comment]
* all cron jobs should extend `TdbCmsCronjobs`
* Cron jobs that still use a named constructor should be changed to use `__construct`

**Comment by UlrichKu** [comment]
Anything to be done about the wrong (annotation) types?

> Many locations falsely expect a cronjob to be TCMSCronJob, for example:

**Comment by UlrichKu** [comment]
Please also change any false annotation type (that uses TCMSCronJob).

And could you write a check (in an update) that iterates all cronjobs (from db table) and checks if they all extend correctly TdbCmsCronjob. Otherwise output an error message.
