### ISSUE TITLE
Backend: List display: Wrong callback for active icon

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#692]
**Describe the bug**
Displaying boolean fields in backend lists normally shows only the text 1 or 0. To make this more readable it is normally replaced by a green or red icon.
This does not work anymore in different locations (i. e. "active" field for tracker) since 6.3.

This can easily fixed in any project (see below) however it should also be done in the basic demo database to have it correct for any new project.

Thus with this the next release also that db dump in chameleon-resources should be updated.

**Affected version(s)**
7.0+

**Technical details**
At those locations the deprecated callback function gcf_GetPublishedIcon (from workflow) is used. It should be replaced by gcf_GetAciveIcon (with the typo).

**Comment by esono-anja** [comment]
**7.1**
1/0 still occurs with 
- Product categories
- External tracking services

**7.0 and 7.1**
I also noticed that the icons are not consistently used for active/not active, but sometimes Yes/No. This occurs with
- Products
- Voucher series
- Shipping groups
=> maybe a new ticket for this issue?

**Comment by esono-anja** [comment]
7.1 was not correctly deployed when I was testing. It is ok!

Change request for wording yes / no see #703
