### ISSUE TITLE
Error Locking/Unlocking CronJobs

### ISSUE THREAD

**Issue by rnuernberg** [chameleon-system/chameleon-system#694]
**Describe the bug**
I have found multiple log entries that indicate that cronjobs cannot be locked/unlocked properly. The entries look like this:

`An exception occurred while executing 'UPDATE `` SET `lock` = '1' WHERE `id` = ?' with params [...]`

It appears, that there are several jobs that extend `TCMSCronJob` instead of `TdbCmsCronjobs` - causing that problem (`$this->table` so set the lock in the correct table)

**Affected version(s)**
7.1

**Comment by UlrichKu** [comment]
Fixed by the other ticket (also in master).
