### ISSUE TITLE
UniversalUploader\UploaderController must be Registered as Service

### ISSUE THREAD

**Issue by kzorluoglu** [chameleon-system/chameleon-system#702]
**Describe the bug**
Actually if we want to upload a file with Media Manager, the file is not uploaded an we do not get an error message about it.

**Affected version(s)**
The Chameleon version 7.1.x

**To Reproduce**
1. Go to 'CMS >  Content > Media > Select Directory (or Create a Example)'
2. Click on 'Upload File(s)'
3. Select File and Click on 'Upload File(s)'
4. See error under Browser > Requests > upload > Response

**Expected behavior**
The Class `ChameleonSystem\CoreBundle\UniversalUploader\Controller\UploaderController` must be registered as service.

**Screenshots**
![Screenshot from 2021-05-03 15-32-32](https://user-images.githubusercontent.com/5286454/116883918-6e0ccf00-ac26-11eb-9c27-e43f0a572de6.png)

**Technical details**
`The controller for URI "/cms/upload" is not callable: Controller "chameleon_system_core.universal_uploader.uploader_controller" cannot be fetched from the container because it is private. Did you forget to tag the service with "controller.service_arguments"?`

**Comment by fabianbarth-esono** [comment]
After some discussion, we came to the conclusion that the tag `controller.service_arguments` should only be used in case we need to use dependency injection for controller actions. This is the original intention of the tag, making the service public is just a side effect. 
In this case, we want to keep the previous solution of just making the service public.
