### ISSUE TITLE
Backend: Error in the products list view

### ISSUE THREAD

**Issue by esono-anja** [chameleon-system/chameleon-system#704]
After today's deploy (12.05. approx. 3 p.m.) this error appears:

Go to the menu item _products_:

Error while rendering view userInput/form/select.html.twig: Template "/userInput/form/text.html.twig" is not defined in "userInput/form/select.html.twig" at line 14.

**Affected version(s)**
7.0+

**To Reproduce**
1. Go to the menu item _products_:'...'
2. See error in the list view

![2021-05-12 17_10_21-IhrName - Chameleon CMS V  7 0 10 (IP_ 10 42 9 59)](https://user-images.githubusercontent.com/15125103/118000196-e3268580-b345-11eb-9f39-9a97e7537ef9.png)

 - Version [e.g. 62]

**Technical details**
Add technical context about the problem here.

**Comment by bestform** [comment]
This should be solved by upgrading twig to the non-broken current version
