### ISSUE TITLE
Frontend is broken

### ISSUE THREAD

**Issue by esono-anja** [chameleon-system/chameleon-system#706]
I see only twig error messages in the frontend.

**Affected version(s)**
7.0+

![2021-05-17 11_41_27-IhrName Shop - Home](https://user-images.githubusercontent.com/15125103/118468409-06b24d00-b705-11eb-9254-b5601bc82b40.png)

**Comment by esono-anja** [comment]
twig errors can be found in the backend as well, e.g. above the product list

**Comment by pixeljunkie** [comment]
This is because of a change in the last twig version (paths with absolute paths do not work anymire). The breaking change was rolled back by the maintainers. We need to redeploy to the stage system.
