### ISSUE TITLE
imagemagick thumbnailing hangs with high pixel images

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#709]
**Describe the bug**
The backend has a limit set to 1024kb for images to prevent problems with high CPU load and RAM usage during the creation of thumbnails. But there is a problem if you upload a logo in b&w with 5000x5000px. The upload limitation will not work here, because the file has only a few kb, but imagemagick will need a high amount of RAM.

**Affected version(s)**
7.1.x and lower

**To Reproduce**
1. Create an image with only 2 colors and a very high pixel width and height like 5000x5000 px
2. Upload the image
3. The backend will try to create a thumbnail in the image list and will fail
4. If your PHP timeout is set to a high value the process will not end and if the image is used on a website the process will start with every user that opens the page.

**Expected behavior**
Even images with high pixel rates should be able to get thumbnails. This is possible by limiting the ram usage in the convert call of imagemagick.

**Technical details**
This works: convert -limit memory 100MB -limit map 100MB -strip -quality 90 -geometry 532x487 test.png testresult.png
With the limit parameters imagemagick will use swap space if the memory limit will exceed.

We should set a memory limit via config and default it to something that uses the RAM most of the time, so we don't get any performance issues. Maybe we should use this option only for images with pixel rates above 2000x2000px.

src/CoreBundle/private/library/classes/components/imageMagick/imageMagick.class.php:504

**Comment by UlrichKu** [comment]
I didn't have problems with an image with 5000x4000 white pixels. (Memory usage was 190mb)
So I guess this is also a "configuration" problem of the respective system.

However to catch really extreme cases it doesn't hurt to add a high-ish memory limit here.
