### ISSUE TITLE
Remove the experimental flag from console database update command

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#710]
**Describe the solution you'd like**
The shell command chameleon_system:update:run which executes all database updates is marked as "experimental". We use this in live environments for years now, so it is the right time to tell the people it is usable with no limitations now.

**Affected version(s)**
7.1 +

**Possible solution (if any)**
remove the "experimental" of the commands description

**Comment by UlrichKu** [comment]
The command list ("app/console") does not show an experimental mark anymore.
