### ISSUE TITLE
Backend: Field type Images / media management with no image: exception Undefined index width

### ISSUE THREAD

**Issue by ckleis** [chameleon-system/chameleon-system#716]
**Describe the bug**
Empty default image id or non existing image id causes mapper exception in dev mode, because $oImage->aData is empty.

**To Reproduce**

Show a record with an image field that is empty without a default value.

![Selection_317](https://user-images.githubusercontent.com/26296728/126170772-7c6ceea1-0bdb-4938-8e80-6dccb72c3c12.png)

OR

You have an image field with an correct image id and within the image record, there's an empty field cms_media_id, you get the same error, too.

![Selection_318](https://user-images.githubusercontent.com/26296728/126171881-74b12276-4828-478c-8c7e-03223288f22e.png)

Also in Media Manager, if you try to show Details of an image with an empty field cms_media_id:

![Selection_316](https://user-images.githubusercontent.com/26296728/126170346-91a2d2d9-10ba-400b-8537-b3d1c826126f.png)

**Affected version(s)**
7.0.x and higher

**Comment by UlrichKu** [comment]
The field type used here is "Images / media management".

It works with the normal type "Image".
