### ISSUE TITLE
PHP8: call_user_func(): Argument #1 ($callback) must be a valid callback

### ISSUE THREAD

**Issue by j6s** [chameleon-system/chameleon-system#726]
**Describe the bug**
When running on PHP8, opening a list that uses `TCMSRecord::callBackUuid` to format IDs (e.g. List of Order Steps) `call_user_func` will throw an error.

**Affected version(s)**
* 7.1

**To Reproduce**
* Set the PHP version to 8.0
* Open the backend
* Open the list of order steps. You will see an error (see below)

**Expected behavior**
Lists should behave the same in PHP7.4 and PHP8.0

**Screenshots**
![2021-09-15_17-33](https://user-images.githubusercontent.com/3374170/133463808-207f0206-6721-40d5-9b8e-40b4c64abc4e.png)

**Technical details**
Calling instance methods statically has been removed in PHP8. In this case it seems that changing `TCMSRecord::callBackUuid` and `TCMSRecord::getShortUuid` to be static solves the issue. The only invocation of the method seems to be generated by `TCMSRecord::getCellFormattingFunction`

**Comment by UlrichKu** [comment]
Will be solved with https://github.com/chameleon-system/chameleon-system/issues/749
