### ISSUE TITLE
Sending login data from Chameleon backend

### ISSUE THREAD

**Issue by esono-anja** [chameleon-system/chameleon-system#729]
Login data for a Chameleon user account can be send via mail. Above the user data record there is a button "Send login data".
An email is then sent to the user with the access data to the Chameleon backend. 

I use this function to inform a new user of his or her access data.
Unfortunately, this does not work reliably in all systems, i.e. no mail is sent. In some systems it works, in some not.

**Comment by pixeljunkie** [comment]
Nope. It doesn't. This is a different problem.

**Comment by UlrichKu** [comment]
This is partly only a configuration problem: if an invalid sender address is used in the respective email template ("new-registration") then this is probably filtered by subsequent email systems.
