### ISSUE TITLE
Broken Font Style in backend user right copy dialog

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#734]
**Describe the bug**
The "copy rights from user" dialog in the CMS backend has a font style issue

**Affected version(s)**
7.0.x

**To Reproduce**
1. Open the backend user management
2. Click on any user
3. Click the "copy rights from user" button
4. See misplaced user names

**Expected behavior**
A nice and shiny layout

**Screenshots**
![Selection_1194](https://user-images.githubusercontent.com/958920/136780209-55fed5de-4fe2-4439-ad16-f7c25e11c580.png)

**Comment by ckleis** [comment]
The popup to copy the backend user rights was still the old styling from chameleon 6.x
Bootstrap4 was not yet considered and there was some deprecated code which I updated.
