### ISSUE TITLE
TPkgCmsTextBlock renderer doesn't pass through replacement variables to the wysiwyg text field renderer

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#736]
**Describe the bug**
TPkgCmsTextBlock uses the old TViewParser which works with PHP files.
Inside the PHP template it calls the wysiwyg text render method for the textblock.
But it does not pass the variables you can set as third parameter for the Render method to the wysiwyg renderer. So your parameters are only usable inside the PHP templates, which means, it is impossible to replace placeholder variables inside a wysiwyg text block. Only in the PHP file itself. That's unexpected, but the fix is easy.

**Affected version(s)**
7.0.x

**To Reproduce**
1. Create a text block entry in the database.
2. Add a placeholder like [{testPlaceholder}].
3. Init the Text Block by its systemname and render it.
4. Add the testPlaceHolder as aCallTimeVars with a value.
5. See, that it is not replaced in the text.

**Expected behavior**
aCallTimeVars should be passed to the wysiwyg text for placeholder replacement.

**Technical details**
We only need to add a variable "data" with all the aCallTimeVars to the Render method, so we can pass the array to the text renderer inside the PHP template.

**Comment by UlrichKu** [comment]
NOTE this only applies to this use case:

`TdbPkgCmsTextBlock::GetInstanceFromSystemName()
->Render('standard', 'Customer', [additional variables])`
