### ISSUE TITLE
Last textfield in tab does not allow linebreaks

### ISSUE THREAD

**Issue by j6s** [chameleon-system/chameleon-system#741]
**Describe the bug**
When adding a field of the type `CMSFIELD_TEXT` (Long text) to a model with the field being the last field of a tab, then adding linebreaks in that field will not be possible for a user editing the record.

**Affected version(s)**
* Tested with 7.0

**To Reproduce**
1. Add a `CMSFIELD_TEXT` (Long text) to a record
2. Change the order to ensure that it is the last field in a tab
3. Save the changes
4. Edit a record, try adding linebreaks in the field

**Expected behavior**
Pressing the enter key should allow adding linebreaks

**Actual behavior**
Nothing happens when pressing the enter key 

**Technical details**
This comes from `fields.inc.php` of `MTTableEditor`: The last textfield in a tab is supposed to press the save button on enter. This makes sense for regular textfields but not for `CMSFIELD_TEXT` as it blocks the native behaviour of adding linebreaks.

Furthermore, the clicking of the save button uses the selector `.btn-group button.itemsave` which does not seem to exist. 
As far as I have looked at this, there are 2 ways of solving this:

1. Remove the Javascript for enter -> click since it's behaviour wasn't working before anyways
2. Fix the behaviour of the JS for enter and remove `CMSFIELD_TEXT` from the array of `$aAllowedTypes` in `fields.inc.php`

**Footnote**
I described this issue as occurring if the field is the last field in a tab as that is very easy to explain. In reality it also happens if the field is not the last field of the tab - it just needs to be the last field of the tab who's type is in `$aAllowedTypes = array('CMSFIELD_STRING', 'CMSFIELD_TEXT', 'CMSFIELD_STRING_UNIQUE');`

**Comment by ckleis** [comment]
The handling to "save the record if Enter key is pressed in last text field" works again. 
There was a wrong class selector in query selector (selector changed with Chameleon 7.0).
But these handling never makes sense for textareas (CMSFIELD_TEXT), because textareas have mostly several lines. So I removed it from $aAllowedTypes.

Furthermore, it should not only be the last **text** field, but the last field in general to save the form on event Enter key.  I have also changed this.

**Comment by ckleis** [comment]
There is a new decision to remove this functionality completely. There's no need to save the record automatically with Enter in last text field.

**Comment by esono-anja** [comment]
I just noticed that saving is no longer possible. 

- enter a text in a field of the type CMSFIELD_TEXT
- save
- refresh page
- => the changes have disappeared

I'm not sure if it has to do with this fix or if it's another problem though.
