### ISSUE TITLE
Possibility to disable jQuery in frontend

### ISSUE THREAD

**Issue by ckleis** [chameleon-system/chameleon-system#751]
**Describe the bug**
I need different jquery-Versions depending on the active portal. The portals are using diffent themes. So I cannot define the jquery path in the global config.inc.php and jquery is included within the layout files.

If I set CHAMELEON_URL_JQUERY = "" in config.inc.php I get a SyntaxError "Uncaught SyntaxError: Unexpected token '<'" in the Browser Console.

![Selection_429](https://user-images.githubusercontent.com/26296728/150498965-0ce416ac-354d-4a94-8d01-836052117511.png)

If I don't define the variable in config.inc.php a default value will be set. That causes an Error, too. (Error 404)

In case you don't want to load jQuery at all, not even a fallback, you should also be able to set the variable to nothing.

In /chameleon-base/src/CoreBundle/EventListener/AddJqueryIncludeListener.php in Line 33 we need an additonal if-clause to prevent setting an empty script tag. Like this:

``` 
if ('' !== CHAMELEON_URL_JQUERY) {
    $sInclude = '<script src="' . TGlobal::GetStaticURL(CHAMELEON_URL_JQUERY) . '" type="text/javascript"></script><!--#GLOBALRESOURCECOLLECTION#-->';
} else {
    $sInclude = '';
}
``` 

**Affected version(s)**
7.x

**Comment by UlrichKu** [comment]
As a short fix: you can overwrite the include listener (chameleon_system_core.event_listener.add_jquery_include).

**Comment by UlrichKu** [comment]
Setting CHAMELEON_URL_JQUERY to false (and CHAMELEON_URL_GOOGLE_JQUERY) allows for disabling of the include listener.
