### ISSUE TITLE
Wrong display of selected CMS fields

### ISSUE THREAD

**Issue by michaelcmichaelis** [chameleon-system/chameleon-system#758]
**Describe the bug**
In some cases, a selected and saved field of type "Werteliste aus Tabelle" is displayed wrong as another selection.

**Affected version(s)**
7.0.x

**To Reproduce**
1. Go to any table, for example "Produktattribute" in Chamelon Shop 7.0
2. Click "Tabelleneigenschaften" to change the table structure
3. Add a field of type "Log-Ausgabe", save the record
4. Reload the page
5. See the selected type is "Zahl"

**Expected behavior**
The selected field has the selection "Log-Ausgabe"

**Comment by bestform** [comment]
Tested ok
