### ISSUE TITLE
Reduce checkout routing to short variant for first step

### ISSUE THREAD

**Issue by kzorluoglu** [chameleon-system/chameleon-system#774]
**Describe the solution you'd like**
The actual route for DE ` .'|((?i:|/|/Uebersicht)/?)(*:560)'`
The last part of the URL is the name of the checkout step. The first one is the URL to the page without the module, the second one with the module.

If we call the shopping cart, then we land on the module without step, therefore we take the first step as default.

Problem is, if we click later on "back", then we land in the other URL.

**Possible solution (if any)**
We can reduce the routing to the short variant for the first step.

**Comment by bestform** [comment]
@kzorluoglu unfortunately this breaks the basket. To reproduce:
* add something to the basket
* open the basket overview
* change the amount of the item
