### ISSUE TITLE
FlashMessageManager without session crashes

### ISSUE THREAD

**Issue by pSpeck** [chameleon-system/chameleon-system#782]
**Describe the bug**
If you use the flash message service without a session, for example within a console command, the service will crash because it cannot load the message handler.
One possible solution is to decorate the Flash service with a silent service that doesn't use the session

**Affected version(s)**
7.1

**To Reproduce**
1. Create a console command
2. Use the TableeditorManager to delet an table entry
3. Error in flash service -> cant load session

**Comment by UlrichKu** [comment]
This is now solved differently: All problems are only internal problems of FlashMessageManager as this does not check the return value of "getHandler()". So it is now fixed locally there.

**Comment by UlrichKu** [comment]
Another observation remains true however: There are many usages of \TCMSMessageManager::GetInstance() which will return null if there is no session and most calling locations do not check for null. This is fully separate of the implementation in FlashMessageService.
