### ISSUE TITLE
TShopShippingGroupList::GetAvailableShippingGroups crashes if no user is present (no session)

### ISSUE THREAD

**Issue by pSpeck** [chameleon-system/chameleon-system#784]
**Describe the bug**
GetAvailableShippingGroups checks if shipping groups are available for an active user. If there is no user (no active session), the process crashes because the active user is not checked for null before using any functions on it.

**Affected version(s)**
7.1

**To Reproduce**
1. Create a console command
2. Call TdbShopShippingGroupList::GetAvailableShippingGroups()
3. Error ->  Call to a member function IsLoggedIn() on null 

**Expected behavior**
If ther is no user ignore userrestricted shipping groups

**Comment by UlrichKu** [comment]
This is now solved differently: ExtranetUserProvider always returns an (empty) user

Also \TShopShippingGroupList::RemoveInvalidItems() is fixed. This was the only location where a standard shop has problems with the GetAvailableShippingGroups call.
