### ISSUE TITLE
Php 8: Avoid optional parameters before mandatory in functions

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#790]
**Problem**
There should be no optional parameters before mandatory ones in a function declaration.

This occurs for example in \TCMSLogChange::SetTableRolePermissions()

**Affected version(s)**
7.+ (fixed for)

**Comment by UlrichKu** [comment]
Another location that a search with this regex yields  function .+\(\$[a-zA-z_ ]+=.+,[$A-Za-z_ ]+,

\TCMSRecordWritable::UploadCMSDocumentFromURL

**Comment by j6s** [comment]
Also, the following for `chameleon-system/chameleon-shop`:

* `TPKGShopMapper_OrderArticleListSummary::getVoucherList`
* `TPKGShopMapper_OrderArticleListSummary::getDataFromVoucher`
* `TShopArticle::generateLinkForToBasketParameters`
* `TShopPaymentHandlerIPaymentEndPoint::GetPayFieldParameter`
* `TShopPaymentHandlerPayOne::PayOnePreauthorization`

**Comment by bestform** [comment]
Thanks to both of you.
