### ISSUE TITLE
Chameleon search with custom keyword leads to error

### ISSUE THREAD

**Issue by michaelcmichaelis** [chameleon-system/chameleon-system#825]
**Describe the bug**
The Chameleon-own search leads to an error if a custom search keyword was found.

**Affected version(s)**
7.0.x

**To Reproduce**

enter a shop entry (mostly the most upper/first/id=1) where to perform the search/ tab "Sucheinstellungen" / field "Von Hand selektierte Suchergebnisse"

1. In CMS, go to menu "System"/"Shop-Konfiguration"
2. Open the shop entry where to perform the search (mostly the "main shop" with id 1)
3. Open the tab "Sucheinstellungen"
4. Inspect field "Von Hand selektierte Suchergebnisse"
5. Create a new test keyword, say "hazelnut": select a language, enter the keyword, select any article to be found by the keyword, and save it
6. Go to the page where to perform the search, mainly the home page with a search field
7. Enter "hazelnut" in the search field and start the search
8. See an exception like "Call to a member function rowCount() on bool"

**Expected behavior**
The previously connected article is shown as a result.

**Comment by pixeljunkie** [comment]
merged into 7.0.x and 7.1.x
