### ISSUE TITLE
Variant table display: images break line

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#87]
**Describe the bug**
Most variant table displays have the table line content moved too low. Especially the image is too low and overlaps the next line.

**Affected version(s)**
6.2

**Technical detail**
There is an explicit styling for those images (height: 0px on the surrounding a tag) causing this.

![selection_089](https://user-images.githubusercontent.com/20949224/46060255-db008400-c162-11e8-829b-1f3e3d25b1e6.png)

**Comment by kzorluoglu** [comment]
it is out of date.
