### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#92]
**Describe the solution you'd like**
Currently the logs are split into multiple destinations such as the database (table pkg_cms_core_log) and various log files. Logging is also not really configurable as concrete logging services are used instead of channels.

**Possible solution (if any)**
- Use a generic logger where possible (inject `logger` service).
- Define a number of channels that make sense and use these channels (tag `monolog.logger` in service definitions).
- Provide a default monolog config in chameleon-system/chameleon-system and in the migration guide. This config should either log to stdout (--> 12-factor app rule) or to the default Symfony logs (as logging to stdout with PHP-FPM is a hassle).
- Mark logger services (basically everything in CoreBundle/Resources/config/logging.xml) as deprecated but preserve their functionality if possible.
- Mark the database log as deprecated, including the table and all corresponding code (maybe the complete CmsCoreLogBundle).
- Adjust all logging calls in Chameleon to use the new logging. Ideally the only logging dependency in the code base is to `Psr\Log\LoggerInterface` and neither monolog classes nor IPkgCmsCoreLog.
- Consider removing the fatal-error log including email sending if there is appropriate replacement.
- Make sure to retain the request ID as it is currently generated by TPkgCmsCoreLog. This helps in grouping log messages even if external systems are called (as long as this ID is passed to the respective calls of course).
- Ideally the log level should be configurable in the environment. Unfortunately my PR for the MonologBundle supporting this isn't merged yet (https://github.com/symfony/monolog-bundle/pull/245).

In addition, we need to find a solution for cases where logger injection is not possible (Tdbs etc). We should use log channels, too, but cannot rely on DI to handle this for us.

We should also define a common baseline for what to log, with which detail level, on which error level, but maybe this should be moved to another ticket.

**Comment by UlrichKu** [comment]
Also take a look at database logging (if that would be working; with exceptions/stack traces).

**Comment by UlrichKu** [comment]
Replaced all usages of IPkgCmsCoreLog, TPkgCmsCoreLog.
Replaced most usages of TTools::WriteLogEntry, TTools::WriteLogEntrySimple - all of the ones with a log file as parameter.
Searched an replaced any service usage of (prefix) cmsPkgCore.log.
Add documentation for logging in general, interface changes and deprecations.
Added upgrade examples.
