### ISSUE TITLE
Allow deactivation of routing config

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#95]
**Describe the solution you'd like**
Routing configuration cannot be deactivated; this should be added to reach feature parity with SEO URL handlers, so we can safely remove that legacy feature.

**Possible solution (if any)**
Note that activating/deactivating will affect the Symfony routing cache which needs to be invalidated/deleted.

**Comment by UlrichKu** [comment]
What's the normal / expected behavior once routing is deactivated that means "missing"?

Deactivating for example "shop_article" results in a number of "RouteNotFoundExceptions" on the start page.

**Comment by umulmrum** [comment]
@UlrichKu When deactivating routes that are needed codewise, it's OK to throw those exceptions. The routes ARE missing after all.
