### ISSUE TITLE
Provide session service

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#97]
**Describe the solution you'd like**
In standard Symfony the service "session" is a regular service that can be injected into other services. In Chameleon this is a synthetic service and can therefore not be injected but only retrieved from the ServiceLocator at runtime. Although this service is quite controversial, we should still provide it in the same way Symfony does, so that 3rd party bundles can rely on it.

At current time there are no complaints about the "missing" service. Unless this changes, we should only try to find a simple solution and not put much effort in it. We should watch progress in Symfony (see https://github.com/symfony/symfony/issues/10557) and follow their solution (in the long run I'd prefer to get rid of custom session handling and only use the Symfony mechanism).

**Comment by umulmrum** [comment]
Stopped working on this, see comment in https://github.com/chameleon-system/chameleon-base/pull/81

**Comment by umulmrum** [comment]
There is some progress in Symfony's attempt to remove the `session` service (see linked issue above). Maybe we can wait it out.

**Comment by UlrichKu** [comment]
Ok, not necessary at the moment.
